#!/usr/bin/env bash
# vim: set ft=bash :

# Open a Git remote in the browser

set -e

declare -a LicenseArray=("MIT" "BSD" "GPLv2" "GPLv3" "Apache" "AGPLv3" "LGPLv2" "LGPLv3" "EPL" "CC0" "WTFPL")

put_license()
{
    cp $HOME/.dotfiles/share/license/$1 $(pwd)/LICENSE
}

read_license()
{
    for License in ${LicenseArray[@]}; do

        if  [[ $1 -eq $License ]]
        then
            if [[ -f $HOME/.dotfiles/share/license/$1 ]]
            then
                less $HOME/.dotfiles/share/license/$1
                exit 0
            else
                echo "License file \"$1\" not exists."
                exit 1
            fi
        fi
    done

    echo "License \"$1\" not found. "

    exit 1
}

if_license()
{
    for License in ${LicenseArray[@]}; do

        if  [[ $1 -eq $License ]]
        then
            if [[ -f $HOME/.dotfiles/share/license/$1 ]]
            then
                put_license $1
                echo "Your repository licensed with \"$1\" license agreement."
                exit 0
            else
                echo "License file \"$1\" not exists."
                exit 1
            fi
        fi
    done
    echo "License \"$1\" not found. "

    exit 1
}

list()
{
    for val in ${LicenseArray[@]}; do
       echo $val
    done
}

if [[ -z "$1" ]]; then
    echo -e "You must be give an license."
    exit 1
fi
while [ "$1" != "" ];
do
    case $1 in
        -l | --list )           shift
                                list
                                ;;
        -h | --help )           git help license
                                exit
                                ;;
        -r | --read )           read_license $1
                                exit
                                ;;
        * )                     if_license $1
                                exit 1
    esac
    shift
done



