# 7zr
# Autogenerated from man page /usr/share/man/man1/7zr.1.gz
complete -c 7zr -o 'ai[r[-' --description 'Include archives.'
complete -c 7zr -o 'ax[r[-' --description 'eXclude archives.'
complete -c 7zr -o bd --description 'Disable percentage indicator.'
complete -c 7zr -o 'i[r[-' --description 'Include filenames.'
complete -c 7zr -s l --description 'don\'t store symlinks; store the files/directories they point to (CAUTION : th…'
complete -c 7zr -o mhe --description '7z format only : enables or disables archive header encryption (Default : off…'
complete -c 7zr -o 'r[-' --description 'Recurse subdirectories (CAUTION: this flag does not do what you think, avoid …'
complete -c 7zr -o sfx --description 'Create SFX archive.'
complete -c 7zr -o si --description 'Read data from StdIn (eg: tar cf - directory | 7zr a -si directory. tar. 7z).'
complete -c 7zr -o so --description 'Write data to StdOut (eg: 7zr x -so directory. tar. 7z | tar xf -).'
complete -c 7zr -o slt --description 'Sets technical mode for l (list) command.'
complete -c 7zr -s u --description 'Update options.'
complete -c 7zr -s w --description 'Set Working directory.'
complete -c 7zr -o 'x[r[-' --description 'Exclude filenames.'
complete -c 7zr -s y --description 'Assume Yes on all queries.'
complete -c 7zr -o t7z --description '7z archive.'
complete -c 7zr -o m0 --description 'lzma method.'
complete -c 7zr -o mx --description 'level of compression = 9 (Ultra).'
complete -c 7zr -o mfb --description 'number of fast bytes for LZMA = 64.'
complete -c 7zr -o md --description 'dictionary size = 32 megabytes.'
complete -c 7zr -o ms --description 'solid archive = on EXAMPLE 2 7zr a -sfx archive.'

