# aconnect
# Autogenerated from man page /usr/share/man/man1/aconnect.1.gz
complete -c aconnect -s d -l disconnect --description 'Disconnect the given subscription.'
complete -c aconnect -s e -l exclusive --description 'Connect ports with exclusive mode.'
complete -c aconnect -s r -l real --description 'Convert time-stamps of event packets to the current value of the given  real-…'
complete -c aconnect -s t -l tick --description 'Like  -r option, but  time-stamps are converted to the current value of the g…'
complete -c aconnect -s i -l input --description 'List existing input (readable) ports.  This option is exclusive to  -o.'
complete -c aconnect -s o -l output --description 'List existing output (writable) ports.  This option is exclusive to  -i.'
complete -c aconnect -s l -l list --description 'List the current connection status.'
complete -c aconnect -s x --description 'option.'
complete -c aconnect -l removeall --description 'Remove all exported connections.'

