# alsa-info
# Autogenerated from man page /usr/share/man/man1/alsa-info.sh.1.gz
complete -c alsa-info -l upload --description 'Upload contents to the server (www. alsa-project. org or pastebin. ca).'
complete -c alsa-info -l no-upload --description 'Do not upload contents to the remote server.'
complete -c alsa-info -l stdout --description 'Print information to standard output.'
complete -c alsa-info -l output --description 'Specify file for output in no-upload mode.'
complete -c alsa-info -l debug --description 'Run utility as normal, but will not delete file (usually /tmp/alsa-info. txt).'
complete -c alsa-info -l with-aplay --description 'Includes output from aplay -l.'
complete -c alsa-info -l with-amixer --description 'Includes output from amixer.'
complete -c alsa-info -l with-alsactl --description 'Includes output from alsactl.'
complete -c alsa-info -l with-configs --description 'Includes output from ~/. asoundrc and /etc/asound. conf if they exist.'
complete -c alsa-info -l update --description 'Check server for updates.'
complete -c alsa-info -l about --description 'Print information about authors.'

