# analyzevmcore
# Autogenerated from man page /usr/share/man/man8/analyzevmcore.8.gz
complete -c analyzevmcore -s h --description 'This screen.'
complete -c analyzevmcore -s c --description 'Analyze the specified vmcore directory, rather than all cores found on the sy…'
complete -c analyzevmcore -s d --description 'This option extracts the vmlinux-*.'
complete -c analyzevmcore -s k --description 'The vmlinux-[version] file which created the core.'
complete -c analyzevmcore -s r --description 'Remove and recreate existing analysis files.   AUTHORS.'

