# aplaymidi
# Autogenerated from man page /usr/share/man/man1/aplaymidi.1.gz
complete -c aplaymidi -s h -l help --description 'Prints a list of options.'
complete -c aplaymidi -s V -l version --description 'Prints the current version.'
complete -c aplaymidi -s l -l list --description 'Prints a list of possible output ports.'
complete -c aplaymidi -s p -l port --description 'Sets the sequencer port(s) to which the events in the MIDI file(s) are sent.'
complete -c aplaymidi -s d -l delay --description 'Specifies how long to wait after the end of each MIDI file, to allow the last…'

