# apparmor_notify
# Autogenerated from man page /usr/share/man/man8/apparmor_notify.8.gz
complete -c apparmor_notify -s p -l poll --description 'poll AppArmor logs and display desktop notifications.'
complete -c apparmor_notify -l display --description 'el.'
complete -c apparmor_notify -s f -l file --description 'search \\s-1FILE\\s0 for AppArmor messages.'
complete -c apparmor_notify -s l -l since-last --description 'show summary since last login.'
complete -c apparmor_notify -s s -l since-days --description 'show summary for last \\s-1NUM\\s0 of days.'
complete -c apparmor_notify -s u -l user --description 'user to drop privileges to when running privileged.'
complete -c apparmor_notify -s w -l wait --description 'wait \\s-1NUM\\s0 seconds before displaying notifications (for use with -p).'
complete -c apparmor_notify -s v -l verbose --description 'show messages with summaries.'

