# arch
# Autogenerated from man page /usr/share/man/man1/arch.1.gz
complete -c arch -l help --description 'display this help and exit.'
complete -c arch -l version --description 'output version information and exit AUTHOR Written by David MacKenzie and Kar…'

