# arcstat
# Autogenerated from man page /usr/share/man/man1/arcstat.1.gz
complete -c arcstat -s a --description 'Print all possible stats.'
complete -c arcstat -s f --description 'Display only specific fields.  See DESCRIPTION for supported statistics.'
complete -c arcstat -s h --description 'Display help message.'
complete -c arcstat -s o --description 'Report statistics to a file instead of the standard output.'
complete -c arcstat -s p --description 'Disable auto-scaling of numerical fields (for raw, machine-parsable values).'
complete -c arcstat -s s --description 'Display data with a specified separator (default: 2 spaces).'
complete -c arcstat -s x --description 'Print extended stats (same as -f time,mfu,mru,mfug,mrug,eskip,mtxmis,dread,pr…'
complete -c arcstat -s v --description 'Show field headers and definitions OPERANDS.'

