# aria_ftdump
# Autogenerated from man page /usr/share/man/man1/aria_ftdump.1.gz
complete -c aria_ftdump -s '?' -s h -l help --description 'Display help and exit.'
complete -c aria_ftdump -s c -l count --description 'Calculate per-word stats (counts and global weights).'
complete -c aria_ftdump -s d -l dump --description 'Dump index (incl.  data offsets and word weights).'
complete -c aria_ftdump -s l -l length --description 'Report length distribution.'
complete -c aria_ftdump -s s -l stats --description 'Report global stats.'
complete -c aria_ftdump -s v -l verbose --description 'Be verbose.'

