# aria_dump_log
# Autogenerated from man page /usr/share/man/man1/aria_dump_log.1.gz
complete -c aria_dump_log -s '#' -l debug --description 'Output debug log.  Often the argument is \'d:t:o,filename\'.'
complete -c aria_dump_log -s f -l file --description 'Path to file which will be read.'
complete -c aria_dump_log -s '?' -l help --description 'Display this help and exit.'
complete -c aria_dump_log -s o -l offset --description 'Start reading log from this offset.'
complete -c aria_dump_log -s n -l pages --description 'Number of pages to read.'
complete -c aria_dump_log -s U -l unit-test --description 'Use unit test record table (for logs created by unittests.'
complete -c aria_dump_log -s V -l version --description 'Print version and exit.'
complete -c aria_dump_log -l print-defaults --description 'Print the program argument list and exit.'
complete -c aria_dump_log -l no-defaults --description 'Don\'t read default options from any option file.'
complete -c aria_dump_log -l defaults-file --description 'Only read default options from the given file #.'
complete -c aria_dump_log -l defaults-extra-file --description 'Read this file after the global files are read.'

