# aseqnet
# Autogenerated from man page /usr/share/man/man1/aseqnet.1.gz
complete -c aseqnet -s p --description 'Specify the TCP port number or TCP service name.'
complete -c aseqnet -s s --description 'Subscribe to the given address for read automatically.'
complete -c aseqnet -s d --description 'Subscribe to the given address for write automatically.'
complete -c aseqnet -s v --description 'Verbose mode.'

