# augmatch
# Autogenerated from man page /usr/share/man/man1/augmatch.1.gz
complete -c augmatch -s a -l all --description 'Print all tree nodes, even ones without an associated value.'
complete -c augmatch -s e -l exact --description 'Only print the parts of the tree that exactly match the expression provided w…'
complete -c augmatch -s I -l include --description 'Add \\s-1DIR\\s0 to the module loadpath.  Can be given multiple times.'
complete -c augmatch -s l -l lens --description 'Use \\s-1LENS\\s0 for the given file; without this option, augmatch tries to gu…'
complete -c augmatch -s L -l print-lens --description 'Print the name of the lens that will be used with the given file and exit.'
complete -c augmatch -s m -l match --description 'Only print the parts of the tree that match the path expression \\s-1EXPR.'
complete -c augmatch -s r -l root --description 'Use directory \\s-1ROOT\\s0 as the root of the filesystem.'
complete -c augmatch -s S -l nostdinc --description 'Do not search any of the default directories for lenses.'

