# augtool
# Autogenerated from man page /usr/share/man/man1/augtool.1.gz
complete -c augtool -s c -l typecheck --description 'Typecheck lenses.'
complete -c augtool -s b -l backup --description 'When files are changed, preserve the originals in a file with extension \'.'
complete -c augtool -s n -l new --description 'Save changes in files with extension \'.'
complete -c augtool -s r -l root --description 'Use directory \\s-1ROOT\\s0 as the root of the filesystem.'
complete -c augtool -s I -l include --description 'Add \\s-1DIR\\s0 to the module loadpath.  Can be given multiple times.'
complete -c augtool -s t -l transform --description 'Add a file transform; uses the \'transform\' command syntax, e. g.'
complete -c augtool -s l -l load-file --description 'Load an individual \\s-1FILE\\s0 into the tree.'
complete -c augtool -s f -l file --description 'Read commands from \\s-1FILE. \\s0.'
complete -c augtool -s i -l interactive --description 'Read commands from the terminal.'
complete -c augtool -s e -l echo --description 'When reading commands from a file via stdin, echo the commands before printin…'
complete -c augtool -s s -l autosave --description 'Automatically save all changes at the end of the session.'
complete -c augtool -s S -l nostdinc --description 'Do not search any of the default directories for modules.'
complete -c augtool -s L -l noload --description 'Do not load any files on startup.'
complete -c augtool -s A -l noautoload --description 'Do not load any lens modules, and therefore no files, on startup.'
complete -c augtool -l span --description 'Load span positions for nodes in the tree, as they relate to the original fil…'
complete -c augtool -l timing --description 'After executing each command, print how long, in milliseconds, executing the …'

