# aulast
# Autogenerated from man page /usr/share/man/man8/aulast.8.gz
complete -c aulast -l bad --description 'Report on the bad logins.'
complete -c aulast -l extract --description 'Write raw audit records used to create the displayed report into a file aulas…'
complete -c aulast -s f --description 'Use the file instead of the audit logs for input.'
complete -c aulast -l proof --description 'Print out the audit event serial numbers used to determine the preceding line…'
complete -c aulast -l stdin --description 'Take audit records from stdin.  The audit events must be in the raw format.'
complete -c aulast -l tty --description 'Limit the report to a specific tty\'s activity.'
complete -c aulast -l user --description 'Limit the report to a specific user.'

