# automount
# Autogenerated from man page /usr/share/man/man8/automount.8.gz
complete -c automount -s h -l help --description 'Print brief help on program usage.'
complete -c automount -s p -l pid-file --description 'Write the pid of the daemon to the specified file.'
complete -c automount -s t -l timeout --description 'Set the global minimum timeout, in seconds, until directories are unmounted.'
complete -c automount -s M -l master-wait --description 'Set the maximum time to wait for the master map to become available if it can…'
complete -c automount -s n -l negative-timeout --description 'Set the default timeout for caching failed key lookups.'
complete -c automount -s v -l verbose --description 'Enables logging of general status and progress messages for all autofs manage…'
complete -c automount -s d -l debug --description 'Enables logging of general status and progress messages as well as debugging …'
complete -c automount -o Dvariable -l define --description 'Define a global macro substitution variable.'
complete -c automount -s f -l foreground --description 'Run the daemon in the foreground and log to stderr instead of syslog. ".'
complete -c automount -s r -l random-multimount-selection --description 'Enables the use of ramdom selection when choosing a host from a list of repli…'
complete -c automount -s m -l dumpmaps --description 'With no parameters, list information about the configured automounter maps, t…'
complete -c automount -s O -l global-options --description 'Allows the specification of global mount options used for all master map entr…'
complete -c automount -s V -l version --description 'Display the version number, then exit.'
complete -c automount -s l -l set-log-priority --description 'Set the daemon log priority to the specified value.'
complete -c automount -s C -l dont-check-daemon --description 'Don\'t check if the daemon is currently running (see NOTES).'
complete -c automount -s F -l force --description 'Force an unlink umount of existing mounts under autofs managed mount points d…'

