# auvirt
# Autogenerated from man page /usr/share/man/man8/auvirt.8.gz
complete -c auvirt -l all-events --description 'Show records for all virtualization related events.'
complete -c auvirt -l debug --description 'Print debug messages to standard output.'
complete -c auvirt -s f -l file --description 'Read records from the given file instead from the system audit log file.'
complete -c auvirt -s h -l help --description 'Print help message and exit.'
complete -c auvirt -l proof --description 'Add after each event a line containing all the identifiers of the audit recor…'
complete -c auvirt -l show-uuid --description 'Add the guest\'s UUID to each record.'
complete -c auvirt -l stdin --description 'Read records from the standard input instead from the system audit log file.'
complete -c auvirt -l summary --description 'Print a summary with information about the events found.'
complete -c auvirt -o te -l end --description 'Search for events with time stamps equal to or before the given end time.'
complete -c auvirt -o ts -l start --description 'Search for events with time stamps equal to or after the given end time.'
complete -c auvirt -s u -l uuid --description 'Only show events related to the guest with the given UUID.'
complete -c auvirt -s v -l vm --description 'Only show events related to the guest with the given name.'

