# bcomps
# Autogenerated from man page /usr/share/man/man1/bcomps.1.gz
complete -c bcomps -s s --description 'No output graph is printed.  Implies the  -v  flag.'
complete -c bcomps -s t --description 'Print the underlying block-cutvertex tree.'
complete -c bcomps -s x --description 'Each biconnected component is printed as a separate root graph.'
complete -c bcomps -s v --description 'Prints number of blocks and cutvertices.'
complete -c bcomps -s o --description 'If specified, each root graph will be written to a different file with the na…'

