# bibtex
# Autogenerated from man page /usr/share/man/man1/bibtex.1.gz
complete -c bibtex -o min-crossrefs --description 'option defines the minimum number of crossref required for automatic inclusio…'
complete -c bibtex -o terse --description 'option,  operates silently.'

