# blogger
# Autogenerated from man page /usr/share/man/man8/blogger.8.gz
complete -c blogger -s n --description 'Declare the following message as a  <notice> .  This is the default.'
complete -c blogger -s d --description 'Use thist to add the leading string  <done> to the message.'
complete -c blogger -s f --description 'Use thist to add the leading string  <failed> to the message.'
complete -c blogger -s s --description 'Use thist to add the leading string  <skipped> to the message.'
complete -c blogger -s u --description 'Use thist to add the leading string <unused> to the message.'

