# btrfs-replace
# Autogenerated from man page /usr/share/man/man8/btrfs-replace.8.gz
complete -c btrfs-replace -s r --description '.'
complete -c btrfs-replace -s f --description '.'
complete -c btrfs-replace -s B --description '.'
complete -c btrfs-replace -s 1 --description '.'

