# btrfs-scrub
# Autogenerated from man page /usr/share/man/man8/btrfs-scrub.8.gz
complete -c btrfs-scrub -s c --description 'and.'
complete -c btrfs-scrub -s n --description 'options.'
complete -c btrfs-scrub -s B --description '.'
complete -c btrfs-scrub -s d --description '.'
complete -c btrfs-scrub -s q --description '.'
complete -c btrfs-scrub -s r --description '.'
complete -c btrfs-scrub -s R --description '.'
complete -c btrfs-scrub -s f --description '.'

