# bznew
# Autogenerated from man page /usr/share/man/man1/bznew.1.gz
complete -c bznew -s f --description 'Force recompression from . gz to . bz2 format even if a .'
complete -c bznew -s t --description 'Tests the new files before deleting originals.'
complete -c bznew -s v --description 'Verbose.  Display the name and percentage reduction for each file compressed.'
complete -c bznew -s 9 --description 'Use the slowest compression method (optimal compression).'
complete -c bznew -s P --description 'Use pipes for the conversion to reduce disk space usage.'
complete -c bznew -s K --description 'Keep a . gz file when it is smaller than the .'

