# chcp
# Autogenerated from man page /usr/share/man/man8/chcp.8.gz
complete -c chcp -s h -l help --description 'Display help message and exit.'
complete -c chcp -s V -l version --description 'Display version and exit.'

