# chfn
# Autogenerated from man page /usr/share/man/man1/chfn.1.gz
complete -c chfn -s f -l full-nameFULL_NAME --description 'Change the user\\*(Aqs full name.'
complete -c chfn -s h -l home-phoneHOME_PHONE --description 'Change the user\\*(Aqs home phone number.'
complete -c chfn -s o -l otherOTHER --description 'Change the user\\*(Aqs other GECOS information.'
complete -c chfn -s r -l roomROOM_NUMBER --description 'Change the user\\*(Aqs room number.'
complete -c chfn -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c chfn -s u -l help --description 'Display help message and exit.'
complete -c chfn -s w -l work-phoneWORK_PHONE --description 'Change the user\\*(Aqs office phone number.'
complete -c chfn -l full-name --description '.'
complete -c chfn -l home-phone --description '.'
complete -c chfn -l other --description '.'
complete -c chfn -l room --description '.'
complete -c chfn -l root --description '.'
complete -c chfn -l work-phone --description '.'

