# chkbin
# Autogenerated from man page /usr/share/man/man8/chkbin.8.gz
complete -c chkbin -s h --description 'This screen.'
complete -c chkbin -s a --description 'Include all: The system library cache and all open files REPORTING BUGS Pleas…'

