# chkstat
# Autogenerated from man page /usr/share/man/man8/chkstat.8.gz
complete -c chkstat -l system --description 'Run in system mode.'
complete -c chkstat -l set --description 'Actually apply the file permissions.'
complete -c chkstat -l warn --description 'Opposite of --set, ie warn only but don\'t make actual changes.'
complete -c chkstat -l noheader --description 'Omit printing the output header lines.'
complete -c chkstat -l fscaps -l no-fscaps --description 'Enable or disable use of fscaps.'
complete -c chkstat -l examinefile --description 'Check permissions for this file instead of all files listed in the permission…'
complete -c chkstat -l filesfilelist --description 'Check permissions for the files listed in R filelist and instead of all files…'
complete -c chkstat -l examine --description 'Check permissions for this file instead of all files listed in the permission…'
complete -c chkstat -l files --description 'Check permissions for the files listed in filelist and instead of all files l…'
complete -c chkstat -l root --description 'Check files relative to the specified directory.'

