# chmod
# Autogenerated from man page /usr/share/man/man1/chmod.1.gz
complete -c chmod -s c -l changes --description 'like verbose but report only when a change is made.'
complete -c chmod -s f -l silent -l quiet --description 'suppress most error messages.'
complete -c chmod -s v -l verbose --description 'output a diagnostic for every file processed.'
complete -c chmod -l no-preserve-root --description 'do not treat \'/\' specially (the default).'
complete -c chmod -l preserve-root --description 'fail to operate recursively on \'/\'.'
complete -c chmod -l reference --description 'use RFILE\'s mode instead of MODE values.'
complete -c chmod -s R -l recursive --description 'change files and directories recursively.'
complete -c chmod -l help --description 'display this help and exit.'
complete -c chmod -l version --description 'output version information and exit.'

