# choom
# Autogenerated from man page /usr/share/man/man1/choom.1.gz
complete -c choom -s p -l pid --description 'Specifies process ID.'
complete -c choom -s n -l adjust --description 'Specify the adjust score value.'
complete -c choom -s h -l help --description 'Display help text and exit.'
complete -c choom -s V -l version --description 'Display version information and exit.'

