# chooser
# Autogenerated from man page /usr/share/man/man1/chooser.1.gz
complete -c chooser -o config --description 'Names the configuration file, which specifies resources to control the behavi…'
complete -c chooser -o nodaemon --description 'Specifies ``false\'\' as the value for the DisplayManager. daemonMode resource.'
complete -c chooser -o debug --description 'Specifies the numeric value for the DisplayManager. debugLevel resource.'
complete -c chooser -o error --description 'Specifies the value for the DisplayManager. errorLogFile resource.'
complete -c chooser -o resources --description 'Specifies the value for the DisplayManager*resources resource.'
complete -c chooser -o server --description 'Specifies the value for the DisplayManager. servers resource.'
complete -c chooser -o udpPort --description 'Specifies the value for the DisplayManager. requestPort resource.'
complete -c chooser -o session --description 'Specifies the value for the DisplayManager*session resource.'
complete -c chooser -o xrm --description 'Allows an arbitrary resource to be specified, as in most X Toolkit applicatio…'

