# chsh
# Autogenerated from man page /usr/share/man/man1/chsh.1.gz
complete -c chsh -s h -l help --description 'Display help message and exit.'
complete -c chsh -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c chsh -s s -l shellSHELL --description 'The name of the user\\*(Aqs new login shell.'
complete -c chsh -l root --description '.'
complete -c chsh -l shell --description '.'

