# ciptool
# Autogenerated from man page /usr/share/man/man1/ciptool.1.gz
complete -c ciptool -s h --description 'Gives a list of possible commands.'
complete -c ciptool -s i --description 'The command is applied to device.'

