# codepage
# Autogenerated from man page /usr/share/man/man1/codepage.1.gz
complete -c codepage -s c --description 'Input file is a single codepage.'
complete -c codepage -s L --description 'Print header info (you don\'t want to see this).'
complete -c codepage -s l --description 'List all codepages contained in the file.'
complete -c codepage -s a --description 'Extract all codepages from the file.'

