# convertquota
# Autogenerated from man page /usr/share/man/man8/convertquota.8.gz
complete -c convertquota -s u -l user --description 'convert user quota file.  This is the default.'
complete -c convertquota -s g -l group --description 'convert group quota file.'
complete -c convertquota -s f -l convert-format --description 'convert quota file from  oldformat to R newformat .'
complete -c convertquota -s e -l convert-endian --description 'convert vfsv0 file format from big endian to little endian (old kernels had a…'
complete -c convertquota -s V -l version --description 'print version information.  FILES.'

