# cpupower-idle-info
# Autogenerated from man page /usr/share/man/man1/cpupower-idle-info.1.gz
complete -c cpupower-idle-info -s f -l silent --description 'Only print a summary of all available C-states in the system.'

