# cpupower-frequency-info
# Autogenerated from man page /usr/share/man/man1/cpupower-frequency-info.1.gz
complete -c cpupower-frequency-info -s e -l debug --description 'Prints out debug information.'
complete -c cpupower-frequency-info -s f -l freq --description 'Get frequency the CPU currently runs at, according to the cpufreq core.'
complete -c cpupower-frequency-info -s w -l hwfreq --description 'Get frequency the CPU currently runs at, by reading it from hardware (only av…'
complete -c cpupower-frequency-info -s l -l hwlimits --description 'Determine the minimum and maximum CPU frequency allowed.'
complete -c cpupower-frequency-info -s d -l driver --description 'Determines the used cpufreq kernel driver.'
complete -c cpupower-frequency-info -s p -l policy --description 'Gets the currently used cpufreq policy.'
complete -c cpupower-frequency-info -s g -l governors --description 'Determines available cpufreq governors.'
complete -c cpupower-frequency-info -s a -l related-cpus --description 'Determines which CPUs run at the same hardware frequency.'
complete -c cpupower-frequency-info -l affected-cpus --description 'Determines which CPUs need to have their frequency coordinated by software.'
complete -c cpupower-frequency-info -s s -l stats --description 'Shows cpufreq statistics if available.'
complete -c cpupower-frequency-info -s y -l latency --description 'Determines the maximum latency on CPU frequency changes.'
complete -c cpupower-frequency-info -s o -l proc --description 'Prints out information like provided by the /proc/cpufreq interface in 2. 4.'
complete -c cpupower-frequency-info -s m -l human --description 'human-readable output for the -f, -w, -s and -y parameters.'
complete -c cpupower-frequency-info -s n -l no-rounding --description 'Output frequencies and latencies without rounding off values.'

