# cpupower
# Autogenerated from man page /usr/share/man/man1/cpupower.1.gz
complete -c cpupower -l help -s h --description '.'
complete -c cpupower -l cpu -s c --description '.'
complete -c cpupower -l version -s v --description '.'
complete -c cpupower -l perf-bias --description 'Thomas Renninger <trenn@suse. de>.'

