# cupstestppd
# Autogenerated from man page /usr/share/man/man1/cupstestppd.1.gz
complete -c cupstestppd -s I --description 'Ignores all PCFileName warnings.'
complete -c cupstestppd -s R --description 'Specifies an alternate root directory for the filter, pre-filter, and other s…'
complete -c cupstestppd -s W --description 'Report all UIConstraint errors as warnings.'
complete -c cupstestppd -s q --description 'Specifies that no information should be displayed.'
complete -c cupstestppd -s r --description 'Relaxes the PPD conformance requirements so that common whitespace, control c…'
complete -c cupstestppd -s v --description 'Specifies that detailed conformance testing results should be displayed rathe…'
complete -c cupstestppd -o vv --description 'Specifies that all information in the PPD file should be displayed in additio…'

