# cupsd
# Autogenerated from man page /usr/share/man/man8/cupsd.8.gz
complete -c cupsd -s c --description 'Uses the named cupsd. conf configuration file.'
complete -c cupsd -s f --description 'Run  cupsd in the foreground; the default is to run in the background as a "d…'
complete -c cupsd -s F --description 'Run  cupsd in the foreground but detach the process from the controlling term…'
complete -c cupsd -s h --description 'Shows the program usage.'
complete -c cupsd -s l --description 'This option is passed to  cupsd when it is run from  launchd (8) or  systemd …'
complete -c cupsd -s s --description 'Uses the named cups-files. conf configuration file.'
complete -c cupsd -s t --description 'Test the configuration file for syntax errors.  FILES.'

