# cupsfilter
# Autogenerated from man page /usr/share/man/man8/cupsfilter.8.gz
complete -c cupsfilter -l list-filters --description 'Do not actually run the filters, just print the filters used to stdout.'
complete -c cupsfilter -s D --description 'Delete the input file after conversion.'
complete -c cupsfilter -s U --description 'Specifies the username passed to the filters.'
complete -c cupsfilter -s c --description 'Uses the named cups-files. conf configuration file.'
complete -c cupsfilter -s d --description 'Uses information from the named printer.'
complete -c cupsfilter -s e --description 'Use every filter from the PPD file.'
complete -c cupsfilter -s i --description 'Specifies the source file type.'
complete -c cupsfilter -s j --description 'Converts document N from the specified job.'
complete -c cupsfilter -s m --description 'Specifies the destination file type.'
complete -c cupsfilter -s n --description 'Specifies the number of copies to generate.'
complete -c cupsfilter -s o --description 'Specifies options to pass to the CUPS filters.'
complete -c cupsfilter -s p --description 'Specifies the PPD file to use.'
complete -c cupsfilter -s t --description 'Specifies the document title.'
complete -c cupsfilter -s u --description 'Delete the PPD file after conversion.'

