# cups-genppdupdate
# Autogenerated from man page /usr/share/man/man8/cups-genppdupdate.8.gz
complete -c cups-genppdupdate -s h --description 'Show a help message.'
complete -c cups-genppdupdate -s n --description 'No action.   The program will run, but the old PPD files will not be replaced.'
complete -c cups-genppdupdate -s q --description 'Quiet mode.   No messages will be issued, apart from errors.'
complete -c cups-genppdupdate -s v --description 'Verbose mode.   More informative messages will be issued.'
complete -c cups-genppdupdate -s s --description 'Use ppd-directory as the base directory to read PPD files from.'
complete -c cups-genppdupdate -s o --description 'Place updated PPD files in output-directory.'
complete -c cups-genppdupdate -s N --description 'Reset all options to their defaults (do not merge options from the current PP…'

