# cupsctl
# Autogenerated from man page /usr/share/man/man8/cupsctl.8.gz
complete -c cupsctl -s E --description 'Enables encryption on the connection to the scheduler.'
complete -c cupsctl -s U --description 'Specifies an alternate username to use when authenticating with the scheduler.'
complete -c cupsctl -s h --description 'Specifies the server address.'
complete -c cupsctl -l debug-logging --description 'Enables (disables) debug logging to the error_log file.'
complete -c cupsctl -l remote-admin --description 'Enables (disables) remote administration.'
complete -c cupsctl -l remote-any --description 'Enables (disables) printing from any address, e. g. , the Internet.'
complete -c cupsctl -l share-printers --description 'Enables (disables) sharing of local printers with other computers.'
complete -c cupsctl -l user-cancel-any --description 'Allows (prevents) users to cancel jobs owned by others.'

