# cvsbug
# Autogenerated from man page /usr/share/man/man8/cvsbug.8.gz
complete -c cvsbug -s f --description 'specify a file (problem-report) which already contains a complete problem rep…'
complete -c cvsbug -s t --description 'Change mail address at the support site for problem reports.'
complete -c cvsbug -s P --description 'print the form specified by the environment variable   PR_FORM  on standard o…'
complete -c cvsbug -s L --description 'print the list of available categories.   No mail is sent.'
complete -c cvsbug -l request-id --description 'sends mail to the default support site, or  site if specified, with a request…'
complete -c cvsbug -s v --description 'Display the  cvsbug version number.'

