# ddns-confgen
# Autogenerated from man page /usr/share/man/man8/ddns-confgen.8.gz
complete -c ddns-confgen -s a --description 'Specifies the algorithm to use for the TSIG key.'
complete -c ddns-confgen -s h --description 'Prints a short summary of options and arguments.'
complete -c ddns-confgen -s k --description 'Specifies the key name of the DDNS authentication key.'
complete -c ddns-confgen -s q --description '(ddns-confgen only.'
complete -c ddns-confgen -s s --description '(ddns-confgen only.'
complete -c ddns-confgen -s z --description '(ddns-confgen only.'

