# desktoptojson
# Autogenerated from man page /usr/share/man/man8/desktoptojson.8.gz
complete -c desktoptojson -l input --description 'The . desktop file to convert.'
complete -c desktoptojson -l output --description 'The file to write the generated JSON data to.'
complete -c desktoptojson -l help --description 'Show a brief help text.'
complete -c desktoptojson -l version --description 'Show version information.'

