# dnsdomainname
# Autogenerated from man page /usr/share/man/man1/dnsdomainname.1.gz
complete -c dnsdomainname -s a -l alias --description 'Display the alias name of the host (if used).'
complete -c dnsdomainname -s A -l all-fqdns --description 'Displays all FQDNs of the machine.'
complete -c dnsdomainname -s b -l boot --description 'Always set a hostname; this allows the file specified by -F to be non-existan…'
complete -c dnsdomainname -s d -l domain --description 'Display the name of the DNS domain.'
complete -c dnsdomainname -s f -l fqdn -l long --description 'Display the FQDN (Fully Qualified Domain Name).'
complete -c dnsdomainname -s F -l file --description 'Read the host name from the specified file.'
complete -c dnsdomainname -s i -l ip-address --description 'Display the network address(es) of the host name.'
complete -c dnsdomainname -s I -l all-ip-addresses --description 'Display all network addresses of the host.'
complete -c dnsdomainname -s s -l short --description 'Display the short host name.  This is the host name cut at the first dot.'
complete -c dnsdomainname -s V -l version --description 'Print version information on standard output and exit successfully.'
complete -c dnsdomainname -s y -l yp -l nis --description 'Display the NIS domain name.'
complete -c dnsdomainname -s h -l help --description 'Print a usage message and exit.'

