# dnssec-keymgr
# Autogenerated from man page /usr/share/man/man8/dnssec-keymgr.8.gz
complete -c dnssec-keymgr -s c --description 'If -c is specified, then the DNSSEC policy is read from file.'
complete -c dnssec-keymgr -s f --description 'Force: allow updating of key events even if they are already in the past.'
complete -c dnssec-keymgr -s g --description 'Specifies a path to a dnssec-keygen binary.  Used for testing.'
complete -c dnssec-keymgr -s h --description 'Print the dnssec-keymgr help summary and exit.'
complete -c dnssec-keymgr -s K --description 'Sets the directory in which keys can be found.'
complete -c dnssec-keymgr -s k --description 'Only apply policies to KSK keys.  See also the -z option.'
complete -c dnssec-keymgr -s q --description 'Quiet: suppress printing of dnssec-keygen and dnssec-settime.'
complete -c dnssec-keymgr -s s --description 'Specifies a path to a dnssec-settime binary.  Used for testing.'
complete -c dnssec-keymgr -s v --description 'Print the dnssec-keymgr version and exit.'
complete -c dnssec-keymgr -s z --description 'Only apply policies to ZSK keys.  See also the -k option.'

