# dnssec-revoke
# Autogenerated from man page /usr/share/man/man8/dnssec-revoke.8.gz
complete -c dnssec-revoke -s h --description 'Emit usage message and exit.'
complete -c dnssec-revoke -s K --description 'Sets the directory in which the key files are to reside.'
complete -c dnssec-revoke -s r --description 'After writing the new keyset files remove the original keyset files.'
complete -c dnssec-revoke -s v --description 'Sets the debugging level.'
complete -c dnssec-revoke -s V --description 'Prints version information.'
complete -c dnssec-revoke -s E --description 'Specifies the cryptographic hardware to use, when applicable.'
complete -c dnssec-revoke -s f --description 'Force overwrite: Causes dnssec-revoke to write the new key pair even if a fil…'
complete -c dnssec-revoke -s R --description 'Print the key tag of the key with the REVOKE bit set but do not revoke the ke…'

