# dnssec-importkey
# Autogenerated from man page /usr/share/man/man8/dnssec-importkey.8.gz
complete -c dnssec-importkey -s f --description 'Zone file mode: instead of a public keyfile name, the argument is the DNS dom…'
complete -c dnssec-importkey -s K --description 'Sets the directory in which the key files are to reside.'
complete -c dnssec-importkey -s L --description 'Sets the default TTL to use for this key when it is converted into a DNSKEY R…'
complete -c dnssec-importkey -s h --description 'Emit usage message and exit.'
complete -c dnssec-importkey -s v --description 'Sets the debugging level.'
complete -c dnssec-importkey -s V --description 'Prints version information.'
complete -c dnssec-importkey -s P --description 'Sets the date on which a key is to be published to the zone.'
complete -c dnssec-importkey -s D --description 'Sets the date on which the key is to be deleted.'

