# dnssec-verify
# Autogenerated from man page /usr/share/man/man8/dnssec-verify.8.gz
complete -c dnssec-verify -s c --description 'Specifies the DNS class of the zone.'
complete -c dnssec-verify -s E --description 'Specifies the cryptographic hardware to use, when applicable.'
complete -c dnssec-verify -s I --description 'The format of the input zone file.'
complete -c dnssec-verify -s o --description 'The zone origin.'
complete -c dnssec-verify -s v --description 'Sets the debugging level.'
complete -c dnssec-verify -s V --description 'Prints version information.'
complete -c dnssec-verify -s q --description 'Quiet mode: Suppresses output.'
complete -c dnssec-verify -s x --description 'Only verify that the DNSKEY RRset is signed with key-signing keys.'
complete -c dnssec-verify -s z --description 'Ignore the KSK flag on the keys when determining whether the zone if correctl…'

