# dotty
# Autogenerated from man page /usr/share/man/man1/dotty.1.gz
complete -c dotty -s V --description 'Prints the version.'
complete -c dotty -o lm --description 'Sets the layout mode.  The mode can be sync or async.  The default is async.'
complete -c dotty -o el --description 'Sets the mesage level.  The lev can be 0 or 1.  The default is 0.'

