# driverless
# Autogenerated from man page /usr/share/man/man1/driverless.1.gz
complete -c driverless -s h -l help -l version --description 'Show help page, including version number.'
complete -c driverless -s v -s d -l debug --description 'Debug mode, verbose logging to stderr.'

