# dump_xsettings
# Autogenerated from man page /usr/share/man/man1/dump_xsettings.1.gz
complete -c dump_xsettings -s h -l help --description 'Display a help message and exit.'
complete -c dump_xsettings -s s -l screen --description 'Use the X screen numbered SCREEN (default is 0).'

