# dumpseg
# Autogenerated from man page /usr/share/man/man8/dumpseg.8.gz
complete -c dumpseg -s h -l help --description 'Display help message and exit.'
complete -c dumpseg -s V -l version --description 'Display version and exit.'

