# ebrowse
# Autogenerated from man page /usr/share/man/man1/ebrowse.1.gz
complete -c ebrowse -s a -l append --description 'append output to existing file.'
complete -c ebrowse -s f -l files --description 'read input file names from  FILE.'
complete -c ebrowse -s I -l search-path --description 'set search path for input files.'
complete -c ebrowse -s m -l min-regexp-length --description 'set minimum regexp length to  N.'
complete -c ebrowse -s M -l max-regexp-length --description 'set maximum regexp length to  N.'
complete -c ebrowse -s n -l no-nested-classes --description 'exclude nested classes.'
complete -c ebrowse -s o -l output-file --description 'set output file name to  FILE.'
complete -c ebrowse -s p -l position-info --description 'print info about position in file.'
complete -c ebrowse -s s -l no-structs-or-unions --description 'don\'t record structs or unions.'
complete -c ebrowse -s v -l verbose --description 'be verbose.'
complete -c ebrowse -s V -l very-verbose --description 'be very verbose.'
complete -c ebrowse -s x -l no-regexps --description 'don\'t record regular expressions.'
complete -c ebrowse -l help --description 'display this help.'
complete -c ebrowse -l version --description 'display version info SEE ALSO emacs (1), etags (1), and the full documentatio…'

