# emacsclient
# Autogenerated from man page /usr/share/man/man1/emacsclient.1.gz
complete -c emacsclient -s a -l alternate-editor --description 'if the Emacs server is not running, run the specified editor instead.'
complete -c emacsclient -s c -l create-frame --description 'create a new frame instead of trying to use the current Emacs frame.'
complete -c emacsclient -s F -l frame-parameters --description 'set the parameters of a newly-created frame.'
complete -c emacsclient -s d -l display --description 'tell the server to display the files on the given display.'
complete -c emacsclient -s e -l eval --description 'do not visit files but instead evaluate the arguments as Emacs Lisp expressio…'
complete -c emacsclient -s f -l server-file --description 'use TCP configuration file FILENAME for communication.'
complete -c emacsclient -s n -l no-wait --description 'returns immediately without waiting for you to "finish" the buffer in Emacs.'
complete -c emacsclient -o nw -s t -l tty --description 'open a new Emacs frame on the current terminal.'
complete -c emacsclient -s s -l socket-name --description 'use socket named FILENAME for communication.'
complete -c emacsclient -s V -l version --description 'print version information and exit.'
complete -c emacsclient -s H -l help --description 'print this usage information message and exit EXIT STATUS Normally, the exit …'

