# ether-wake
# Autogenerated from man page /usr/share/man/man8/ether-wake.8.gz
complete -c ether-wake -s b --description 'Send the wake-up packet to the broadcast address.'
complete -c ether-wake -s D --description 'Increase the Debug Level.'
complete -c ether-wake -s i --description 'Use interface ifname instead of sending a wake packet to all interfaces.'
complete -c ether-wake -s p --description 'Append a four or six byte password to the packet.'
complete -c ether-wake -s V --description 'Show the program version information.'

