# eventlogadm
# Autogenerated from man page /usr/share/man/man8/eventlogadm.8.gz
complete -c eventlogadm -s s --description 'The -s option causes eventlogadm to load the configuration file given as FILE…'
complete -c eventlogadm -s d --description 'The -d option causes eventlogadm to emit debugging information.'
complete -c eventlogadm -s o --description 'The -o addsource option creates a new event log source.'
complete -c eventlogadm -s h --description 'Print usage information.'

