# extlinux
# Autogenerated from man page /usr/share/man/man1/extlinux.1.gz
complete -c extlinux -s H -l heads --description 'Force the number of heads.'
complete -c extlinux -s i -l install --description 'Install over the current bootsector.'
complete -c extlinux -s O -l clear-once --description 'Clear the boot-once command.'
complete -c extlinux -s o -l once --description 'Execute a command once upon boot.'
complete -c extlinux -s M -l menu-save --description 'Set the label to select as default on the next boot.'
complete -c extlinux -s r -l raid --description 'Fall back to the next device on boot failure.'
complete -c extlinux -l reset-adv --description 'Reset auxiliary data.'
complete -c extlinux -s S -l sectors --description 'Force the number of sectors per track.'
complete -c extlinux -s U -l update --description 'Updates a previous EXTLINUX installation.'
complete -c extlinux -s z -l zip --description 'Force zipdrive geometry (-H 64 -S 32).'

