# extractres
# Autogenerated from man page /usr/share/man/man1/extractres.1.gz
complete -c extractres -s m --description 'option combines the resources of the same name into one file; this must be us…'

