# fbtest
# Autogenerated from man page /usr/share/man/man8/fbtest.8.gz
complete -c fbtest -s f -l fb --description 'This option specifies an other frame buffer device than the default R /dev/fb…'
complete -c fbtest -s C -l vc --description 'This option specifies an other virtual console than the default /dev/tty1 .'

