# fc-cat
# Autogenerated from man page /usr/share/man/man1/fc-cat.1.gz
complete -c fc-cat -s r --description 'Recurse into subdirectories.'
complete -c fc-cat -s v --description 'Be verbose.'
complete -c fc-cat -s h --description 'Show summary of options.'

