# fc-cache
# Autogenerated from man page /usr/share/man/man1/fc-cache.1.gz
complete -c fc-cache -s E --description 'Raise an error if there are no fonts in dir or directories in the configurati…'
complete -c fc-cache -s f --description 'Force re-generation of apparently up-to-date cache files, overriding the time…'
complete -c fc-cache -s r --description 'Erase all existing cache files and rescan.'
complete -c fc-cache -s s --description 'Only scan system-wide directories, omitting the places located in the user\'s …'
complete -c fc-cache -s v --description 'Display status information while busy.'
complete -c fc-cache -s y --description 'Prepend dir to all paths for scanning.'
complete -c fc-cache -s h --description 'Show summary of options.'
complete -c fc-cache -s V --description 'Show version of the program and exit.'

