# fc-list
# Autogenerated from man page /usr/share/man/man1/fc-list.1.gz
complete -c fc-list -s v --description 'Print verbose output of the whole font pattern for each match, or elements if…'
complete -c fc-list -s f --description 'Format output according to the format specifier format.'
complete -c fc-list -s q --description 'Suppress all normal output.  returns 1 as the error code if no fonts matched.'
complete -c fc-list -s V --description 'Show version of the program and exit.'
complete -c fc-list -s h --description 'Show summary of options.'

