# fc-match
# Autogenerated from man page /usr/share/man/man1/fc-match.1.gz
complete -c fc-match -s a --description 'Displays sorted list of best matching fonts, but do not do any pruning on the…'
complete -c fc-match -s s --description 'Displays sorted list of best matching fonts.'
complete -c fc-match -s v --description 'Print verbose output of the whole font pattern for each match, or elements if…'
complete -c fc-match -s f --description 'Format output according to the format specifier format.'
complete -c fc-match -s V --description 'Show version of the program and exit.'
complete -c fc-match -s h --description 'Show summary of options.'

