# fc-scan
# Autogenerated from man page /usr/share/man/man1/fc-scan.1.gz
complete -c fc-scan -s f --description 'Format output according to the format specifier format.'
complete -c fc-scan -s V --description 'Show version of the program and exit.'
complete -c fc-scan -s h --description 'Show summary of options.'

