# fiascotopnm
# Autogenerated from man page /usr/share/man/man1/fiascotopnm.1.gz
complete -c fiascotopnm -s o -l output --description 'Write decompressed image to the file name. ppm (if PPM) or name. pgm (if PGM).'
complete -c fiascotopnm -s z -l fast --description 'Decompress images in the 4:2:0 format; i. e.'
complete -c fiascotopnm -s d -l double --description 'Double the size of the X11 window both in width and height; no pixel interpol…'
complete -c fiascotopnm -s p -l panel --description 'Show a panel with play, stop, pause, record and exit buttons to control the d…'
complete -c fiascotopnm -s m -l magnify --description 'Set magnification of the decompressed image.'
complete -c fiascotopnm -s s -l smoothing --description 'Smooth decompressed image(s) along the partitioning borders by the given amou…'
complete -c fiascotopnm -s F -l fps --description 'Set number of frames per second to N.'
complete -c fiascotopnm -l verbose --description 'Set verbose of fiascotopnm to N.'
complete -c fiascotopnm -s v -l version --description 'Print fiascotopnm version number, then exit.'
complete -c fiascotopnm -s f -l config --description 'Load parameter file name to initialize the options of fiascotopnm.'
complete -c fiascotopnm -s h -l info --description 'Print brief help, then exit.'
complete -c fiascotopnm -s H -l help --description 'Print detailed help, then exit.  EXAMPLES fiascotopnm foo. wfa >foo.'

