# fipshmac
# Autogenerated from man page /usr/share/man/man8/fipshmac.8.gz
complete -c fipshmac -s d --description 'option, the \\&.'
complete -c fipshmac -s s --description 'option allows to specify the suffix of the hmac file names.'

