# fireworkx
# Autogenerated from man page /usr/share/man/man6/fireworkx.6x.gz
complete -c fireworkx -o visual --description 'Specify which visual to use.'
complete -c fireworkx -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c fireworkx -o root --description 'Draw on the root window.'
complete -c fireworkx -o no-flash --description 'Turn off light flash effect.  (Runs faster).'
complete -c fireworkx -o shoot --description 'Fire shells up using mortar.'
complete -c fireworkx -o delay --description 'Delay between frames.  In microseconds.  (Default: 10000).'
complete -c fireworkx -o maxlife --description 'Maximum decay period for an explosion.  (Range: 0-100).'
complete -c fireworkx -o verbose --description 'For scientific research purposes only. !.'
complete -c fireworkx -o fps --description 'Display the current frame rate and CPU load.'
complete -c fireworkx -l ------------------------------------------------------------------ --description '.'

