# flatpak-remote-ls
# Autogenerated from man page /usr/share/man/man1/flatpak-remote-ls.1.gz
complete -c flatpak-remote-ls -s h -l help --description 'Show help options and exit.'
complete -c flatpak-remote-ls -l user --description 'Use the per-user configuration.'
complete -c flatpak-remote-ls -l system --description 'Use the default system-wide configuration.'
complete -c flatpak-remote-ls -l installation --description 'Use a system-wide installation specified by NAME among those defined in /etc/…'
complete -c flatpak-remote-ls -l cached --description 'Prefer to use locally cached information if possible, even though it may be o…'
complete -c flatpak-remote-ls -s d -l show-details --description 'Show arches, branches and commit ids, in addition to the names.'
complete -c flatpak-remote-ls -l runtime --description 'Show only runtimes, omit applications.'
complete -c flatpak-remote-ls -l app --description 'Show only applications, omit runtimes.'
complete -c flatpak-remote-ls -l all -s a --description 'Show everything.'
complete -c flatpak-remote-ls -l updates --description 'Show only those which have updates available.'
complete -c flatpak-remote-ls -l arch --description 'Show only those matching the specified architecture.'
complete -c flatpak-remote-ls -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-remote-ls -l ostree-verbose --description 'Print OSTree debug information during command processing.'
complete -c flatpak-remote-ls -l app-runtime --description 'List applications that use the given runtime.'
complete -c flatpak-remote-ls -l columns --description 'Specify what information to show about each ref.'

