# flatpak-remotes
# Autogenerated from man page /usr/share/man/man1/flatpak-remotes.1.gz
complete -c flatpak-remotes -s h -l help --description 'Show help options and exit.'
complete -c flatpak-remotes -l user --description 'Show the per-user configuration.'
complete -c flatpak-remotes -l system --description 'Show the default system-wide configuration.'
complete -c flatpak-remotes -l installation --description 'Show a system-wide installation by NAME among those defined in /etc/flatpak/i…'
complete -c flatpak-remotes -s d -l show-details --description 'Show more information for each repository in addition to the name.'
complete -c flatpak-remotes -l show-disabled --description 'Show disabled repos.'
complete -c flatpak-remotes -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-remotes -l ostree-verbose --description 'Print OSTree debug information during command processing.'
complete -c flatpak-remotes -l columns --description 'Specify what information to show about each ref.'

