# flatpak-permission-set
# Autogenerated from man page /usr/share/man/man1/flatpak-permission-set.1.gz
complete -c flatpak-permission-set -s h -l help --description 'Show help options and exit.'
complete -c flatpak-permission-set -l data --description 'Associate DATA with the entry.  The data must be a serialized GVariant.'
complete -c flatpak-permission-set -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-permission-set -l ostree-verbose --description 'Print OSTree debug information during command processing.'

