# flatpak-list
# Autogenerated from man page /usr/share/man/man1/flatpak-list.1.gz
complete -c flatpak-list -s h -l help --description 'Show help options and exit.'
complete -c flatpak-list -l user --description 'List per-user installations.'
complete -c flatpak-list -l system --description 'List the default system-wide installations.'
complete -c flatpak-list -l installation --description 'List a system-wide installation specified by NAME among those defined in /etc…'
complete -c flatpak-list -l arch --description 'List apps/runtimes for this architecture.'
complete -c flatpak-list -s d -l show-details --description 'Show origin, sizes and other extra information.  Equivalent to --columns=all.'
complete -c flatpak-list -l app --description 'List applications.'
complete -c flatpak-list -l runtime --description 'List runtimes.'
complete -c flatpak-list -l all -s a --description 'List all installed runtimes, including locale and debug extensions.'
complete -c flatpak-list -l app-runtime --description 'List applications that use the given runtime.'
complete -c flatpak-list -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-list -l ostree-verbose --description 'Print OSTree debug information during command processing.'
complete -c flatpak-list -l columns --description 'Specify what information to show about each ref.'

