# flatpak-permission-reset
# Autogenerated from man page /usr/share/man/man1/flatpak-permission-reset.1.gz
complete -c flatpak-permission-reset -l all --description 'Remove permissions for all applications.'
complete -c flatpak-permission-reset -s h -l help --description 'Show help options and exit.'
complete -c flatpak-permission-reset -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-permission-reset -l ostree-verbose --description 'Print OSTree debug information during command processing.'

