# flatpak-search
# Autogenerated from man page /usr/share/man/man1/flatpak-search.1.gz
complete -c flatpak-search -l user --description 'Only search through remotes in the per-user installation.'
complete -c flatpak-search -l system --description 'Only search through remotes in the default system-wide installation.'
complete -c flatpak-search -l installation --description 'Show a system-wide installation by NAME among those defined in /etc/flatpak/i…'
complete -c flatpak-search -s h -l help --description 'Show help options and exit.'
complete -c flatpak-search -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-search -l ostree-verbose --description 'Print OSTree debug information during command processing.'
complete -c flatpak-search -l columns --description 'Specify what information to show about each result.'

