# flatpak-permission-remove
# Autogenerated from man page /usr/share/man/man1/flatpak-permission-remove.1.gz
complete -c flatpak-permission-remove -s h -l help --description 'Show help options and exit.'
complete -c flatpak-permission-remove -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-permission-remove -l ostree-verbose --description 'Print OSTree debug information during command processing.'

