# flatpak-documents
# Autogenerated from man page /usr/share/man/man1/flatpak-documents.1.gz
complete -c flatpak-documents -s h -l help --description 'Show help options and exit.'
complete -c flatpak-documents -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-documents -l ostree-verbose --description 'Print OSTree debug information during command processing.'

