# flatpak-build-bundle
# Autogenerated from man page /usr/share/man/man1/flatpak-build-bundle.1.gz
complete -c flatpak-build-bundle -s h -l help --description 'Show help options and exit.'
complete -c flatpak-build-bundle -l runtime --description 'Export a runtime instead of an application.'
complete -c flatpak-build-bundle -l arch --description 'The arch to create a bundle for.'
complete -c flatpak-build-bundle -l repo-url --description 'The URL for the repository from which the application can be updated.'
complete -c flatpak-build-bundle -l runtime-repo --description 'The URL for a .'
complete -c flatpak-build-bundle -l gpg-keys --description 'Add the GPG key from FILE (use - for stdin).'
complete -c flatpak-build-bundle -l gpg-homedir --description 'GPG Homedir to use when looking for keyrings.'
complete -c flatpak-build-bundle -l from-commit --description 'The OSTree commit to create a delta bundle from.'
complete -c flatpak-build-bundle -l oci --description 'Export to an OCI image instead of a Flatpak bundle.'
complete -c flatpak-build-bundle -s v -l verbose --description 'Print debug information during command processing.'
complete -c flatpak-build-bundle -l ostree-verbose --description 'Print OSTree debug information during command processing.'

