# flurry
# Autogenerated from man page /usr/share/man/man6/flurry.6x.gz
complete -c flurry -o visual --description 'Specify which visual to use.'
complete -c flurry -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c flurry -o root --description 'Draw on the root window.'
complete -c flurry -o preset --description 'Select a preset (classic, fire, water, psychedelic, rgb, binary, random, insa…'
complete -c flurry -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

