# freetype-config
# Autogenerated from man page /usr/share/man/man1/freetype-config.1.gz
complete -c freetype-config -l prefix --description 'Return the prefix value of the installed FreeType library (the default prefix…'
complete -c freetype-config -l exec-prefix --description 'Return the executable prefix value of the installed FreeType library (will of…'
complete -c freetype-config -l ftversion --description 'Return the FreeType version number, directly derived from file `freetype. h\'.'
complete -c freetype-config -l version --description 'Return the `libtool version\' of the FreeType library.'
complete -c freetype-config -l libtool --description 'Return the library name for linking with libtool.'
complete -c freetype-config -l libs --description 'Return compiler flags for linking with the installed FreeType library.'
complete -c freetype-config -l cflags --description 'Return compiler flags for compiling against the installed FreeType library.'
complete -c freetype-config -l static --description 'Make command line options display flags for static linking.'
complete -c freetype-config -l help --description 'Show help and exit. SS Path override options .'

