# fstobdf
# Autogenerated from man page /usr/share/man/man1/fstobdf.1.gz
complete -c fstobdf -o server --description 'This option specifies the server from which the font should be read.'
complete -c fstobdf -o fn --description 'This option specifies the font for which a BDF file should be generated.'
complete -c fstobdf -o version --description 'This option prints the program version and then exits without generating a BD…'

