# fwupdmgr
# Autogenerated from man page /usr/share/man/man1/fwupdmgr.1.gz
complete -c fwupdmgr -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c fwupdmgr -s v -l verbose --description 'Show extra debugging information.'
complete -c fwupdmgr -l version --description 'Show client and daemon versions.'
complete -c fwupdmgr -l offline --description 'Schedule installation for next reboot when possible.'
complete -c fwupdmgr -l allow-reinstall --description 'Allow re-installing existing firmware versions.'
complete -c fwupdmgr -l allow-older --description 'Allow downgrading firmware versions.'
complete -c fwupdmgr -l force --description 'Override warnings and force the action.'
complete -c fwupdmgr -s y -l assume-yes --description 'Answer yes to all questions.'
complete -c fwupdmgr -l sign --description 'Sign the uploaded data with the client certificate.'
complete -c fwupdmgr -l no-unreported-check --description 'Do not check for unreported history.'
complete -c fwupdmgr -l no-metadata-check --description 'Do not check for old metadata.'
complete -c fwupdmgr -l no-reboot-check --description 'Do not check for reboot after update.'
complete -c fwupdmgr -l no-history --description 'Do not write to the history database.'
complete -c fwupdmgr -l show-all-devices --description 'Show devices that are not updatable.'

