# g3topbm
# Autogenerated from man page /usr/share/man/man1/g3topbm.1.gz
complete -c g3topbm -o kludge --description 'Tells g3topbm to ignore the first few lines of the file; sometimes fax files …'
complete -c g3topbm -o reversebits --description 'Tells g3topbm to interpret bits least-significant first, instead of the defau…'
complete -c g3topbm -o stretch --description 'This option tells g3topbm to stretch the image vertically by duplicating each…'
complete -c g3topbm -o width --description 'This option tells g3topbm that the image is supposed to be pixels pixels wide.'
complete -c g3topbm -o paper_size --description 'This option tells g3topbm for what size paper this image is supposed to be fo…'
complete -c g3topbm -o stoperror --description 'file, it will not tell you of your mistake.'
complete -c g3topbm -o stop_error --description '.'

