# gc
# Autogenerated from man page /usr/share/man/man1/gc.1.gz
complete -c gc -s n --description 'Count nodes.'
complete -c gc -s e --description 'Count edges.'
complete -c gc -s c --description 'Count connected components.'
complete -c gc -s C --description 'Count clusters.'
complete -c gc -s a --description 'Count all.  Equivalent to  -encC.'
complete -c gc -s r --description 'Recursively analyze subgraphs.'
complete -c gc -s s --description 'Print no output.  Only exit value is important.'
complete -c gc -s D --description 'Only analyze directed graphs.'
complete -c gc -s U --description 'Only analyze undirected graphs.'
complete -c gc -s v --description 'Verbose output.'
complete -c gc -o encC --description '.'
complete -c gc -s '?' --description 'Print usage information.'
complete -c gc -s E --description 'option was used, and a graph of the wrong type was encountered.'

