# gcab
# Autogenerated from man page /usr/share/man/man1/gcab.1.gz
complete -c gcab -s c -l create --description 'create a new cabinet archive.'
complete -c gcab -s x -l extract --description 'extract files from a cabinet archive.'
complete -c gcab -s t -l list --description 'list files of a cabinet archive.'
complete -c gcab -s n -l nopath --description 'create files without pathnames.'
complete -c gcab -s C -l directory --description 'change or extract to directory DIR.'
complete -c gcab -s v -l verbose --description 'verbosely list files processed.'
complete -c gcab -s z -l zip --description 'use zip compression AUTHOR Written by Marc-AndrÃ© Lureau <marcandre.'

