# getappcore
# Autogenerated from man page /usr/share/man/man8/getappcore.8.gz
complete -c getappcore -s h --description 'The help screen.'
complete -c getappcore -s b --description 'Path to the binary which generated the application core file.'
complete -c getappcore -s r --description 'SUSE Service Request number associated with this issue.'
complete -c getappcore -s j --description 'Specifies a coredump PID number from the journal to extract, instead of speci…'
complete -c getappcore -s u --description 'Automatically uploads archive to the SUSE FTP server using HTTPS.'
complete -c getappcore -s f --description 'Automatically uploads archive to the SUSE FTP server using FTPES.'
complete -c getappcore -s v --description 'Enable verbose messages EXAMPLES getappcore -ur 00123456 -b /bin/rpm /core.'

