# getunimap
# Autogenerated from man page /usr/share/man/man8/getunimap.8.gz
complete -c getunimap -s C --description 'option may be used with Linux 2. 6.'
complete -c getunimap -s s --description 'option will sort and merge elements, sorting on font character.'

