# gftodvi
# Autogenerated from man page /usr/share/man/man1/gftodvi.1.gz
complete -c gftodvi -o overflow-label-offset --description 'specifies the distance from the right edge of the character bounding box at w…'
complete -c gftodvi -o verbose --description 'option, gftodvi operates silently.'

