# giftopnm
# Autogenerated from man page /usr/share/man/man1/giftopnm.1.gz
complete -c giftopnm -l alphaout --description 'giftopnm  creates a PBM file containing the transparency information from the…'
complete -c giftopnm -o verbose --description 'Produce verbose output about the GIF file input.'
complete -c giftopnm -o comments --description 'With this option, giftopnm issues messages showing the GIF comments (A GIF89 …'
complete -c giftopnm -o image --description 'This option identifies which image from the GIF stream you want.'
complete -c giftopnm -o repair --description 'This option makes giftopnm try to salvage what it can from an invalid GIF inp…'
complete -c giftopnm -o quitearly --description 'This option makes giftopnm stop reading its input file as soon as it has conv…'

