# git-commit-graph
# Autogenerated from man page /usr/share/man/man1/git-commit-graph.1.gz
complete -c git-commit-graph -l object-dir --description 'Use given directory for the location of packfiles and commit-graph file.'
complete -c git-commit-graph -l progress --description 'Turn progress on/off explicitly.'
complete -c git-commit-graph -l stdin-packs --description 'option, generate the new commit graph by walking objects only in the specifie…'
complete -c git-commit-graph -l stdin-commits --description 'or.'
complete -c git-commit-graph -l reachable --description '.'
complete -c git-commit-graph -l append --description 'option, include all commits that are present in the existing commit-graph fil…'
complete -c git-commit-graph -l split --description 'option, write the commit-graph as a chain of multiple commit-graph files stor…'
complete -c git-commit-graph -l size-multiple --description 'is not specified, let X equal 2.'
complete -c git-commit-graph -l max-commits --description 'is specified with M a positive integer, and the new tip file would have more …'
complete -c git-commit-graph -l expire-time --description 'is not specified, let datetime be the current time.'
complete -c git-commit-graph -l shallow --description 'option, only check the tip commit-graph file in a chain of split commit-graph…'

