# git-bundle
# Autogenerated from man page /usr/share/man/man1/git-bundle.1.gz
complete -c git-bundle -l progress --description 'Progress status is reported on the standard error stream by default when it i…'
complete -c git-bundle -l all-progress --description 'When --stdout is specified then progress report is displayed during the objec…'
complete -c git-bundle -l all-progress-implied --description 'This is used to imply --all-progress whenever progress display is activated.'
complete -c git-bundle -s q -l quiet --description 'This flag makes the command not to report its progress on the standard error …'

