# git-stash
# Autogenerated from man page /usr/share/man/man1/git-stash.1.gz
complete -c git-stash -s a -l all --description 'This option is only valid for push and save commands.'
complete -c git-stash -s u -l include-untracked --description 'This option is only valid for push and save commands.'
complete -c git-stash -l index --description 'This option is only valid for pop and apply commands.'
complete -c git-stash -s k -l keep-index -l no-keep-index --description 'This option is only valid for push and save commands.'
complete -c git-stash -s p -l patch --description 'This option is only valid for push and save commands.'
complete -c git-stash -l pathspec-from-file --description 'This option is only valid for push command.'
complete -c git-stash -l pathspec-file-nul --description 'This option is only valid for push command.'
complete -c git-stash -s q -l quiet --description 'This option is only valid for apply, drop, pop, push, save, store commands.'
complete -c git-stash -l literal-pathspecs --description '.'
complete -c git-stash -l ---H----I --description 'where H is the HEAD commit, I is a commit that records the state of the index…'

