# git-restore
# Autogenerated from man page /usr/share/man/man1/git-restore.1.gz
complete -c git-restore -s s -l source --description 'Restore the working tree files with the content from the given tree.'
complete -c git-restore -s p -l patch --description 'Interactively select hunks in the difference between the restore source and t…'
complete -c git-restore -s W -l worktree -s S -l staged --description 'Specify the restore location.'
complete -c git-restore -s q -l quiet --description 'Quiet, suppress feedback messages.  Implies --no-progress.'
complete -c git-restore -l progress -l no-progress --description 'Progress status is reported on the standard error stream by default when it i…'
complete -c git-restore -l ours -l theirs --description 'When restoring files in the working tree from the index, use stage #2 (ours) …'
complete -c git-restore -s m -l merge --description 'When restoring files on the working tree from the index, recreate the conflic…'
complete -c git-restore -l conflict --description 'The same as --merge option above, but changes the way the conflicting hunks a…'
complete -c git-restore -l ignore-unmerged --description 'When restoring files on the working tree from the index, do not abort the ope…'
complete -c git-restore -l ignore-skip-worktree-bits --description 'In sparse checkout mode, by default is to only update entries matched by <pat…'
complete -c git-restore -l overlay -l no-overlay --description 'In overlay mode, the command never removes files when restoring.'
complete -c git-restore -l pathspec-from-file --description 'Pathspec is passed in <file> instead of commandline args.'
complete -c git-restore -l pathspec-file-nul --description 'Only meaningful with --pathspec-from-file.'
complete -c git-restore -l literal-pathspecs --description '.'

