# gnumt
# Autogenerated from man page /usr/share/man/man1/gnumt.1.gz
complete -c gnumt -s f -l file --description 'Use  device as the file name of the tape drive to operate on.'
complete -c gnumt -l rsh-command --description 'Notifies  mt that it should use  command to communicate with remote devices i…'
complete -c gnumt -s V -l version --description 'Print the version number of mt .  BUG REPORTS Report bugs to <bug-cpio@gnu.'

