# goa-daemon
# Autogenerated from man page /usr/share/man/man8/goa-daemon.8.gz
complete -c goa-daemon -l replace --description 'Replace existing instance.'
complete -c goa-daemon -l help --description 'Show help options.'

