# gpgv2
# Autogenerated from man page /usr/share/man/man1/gpgv2.1.gz
complete -c gpgv2 -l verbose --description 'TQ   -v Gives more information during processing.'
complete -c gpgv2 -l quiet --description 'TQ   -q Try to be as quiet as possible.'
complete -c gpgv2 -l keyring --description 'Add file to the list of keyrings.'
complete -c gpgv2 -l output --description 'TQ   -o file Write output to file; to write to stdout use -.'
complete -c gpgv2 -l status-fd --description 'Write special status strings to the file descriptor n.'
complete -c gpgv2 -l logger-fd --description 'Write log output to file descriptor n and not to stderr.'
complete -c gpgv2 -l log-file --description 'Same as --logger-fd, except the logger data is written to file file.'
complete -c gpgv2 -l ignore-time-conflict --description 'GnuPG normally checks that the timestamps associated with keys and signatures…'
complete -c gpgv2 -l homedir --description 'Set the name of the home directory to dir.'
complete -c gpgv2 -l weak-digest --description 'Treat the specified digest algorithm as weak.'
complete -c gpgv2 -s v --description 'Gives more information during processing.'
complete -c gpgv2 -s q --description 'Try to be as quiet as possible.'
complete -c gpgv2 -s o --description 'Write output to file; to write to stdout use -.'
complete -c gpgv2 -l enable-special-filenames --description 'This option enables a mode in which filenames of the form `-&n\', where n is a…'

