# graphml2gv
# Autogenerated from man page /usr/share/man/man1/graphml2gv.1.gz
complete -c graphml2gv -s v --description 'Turns on verbose mode.'
complete -c graphml2gv -s '?' --description 'Prints usage information and exits.'
complete -c graphml2gv -s g --description 'The string gname is used as the name of the generated graph.'
complete -c graphml2gv -s o --description 'Prints output to the file outfile.  If not given, graphml2gv uses stdout.'

