# groupdel
# Autogenerated from man page /usr/share/man/man8/groupdel.8.gz
complete -c groupdel -s h -l help --description 'Display help message and exit.'
complete -c groupdel -s R -l rootCHROOT_DIR --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c groupdel -s P -l prefixPREFIX_DIR --description 'Apply changes in the PREFIX_DIR directory and use the configuration files fro…'
complete -c groupdel -l root --description '.'
complete -c groupdel -l prefix --description '.'

