# grub2-mkfont
# Autogenerated from man page /usr/share/man/man1/grub2-mkfont.1.gz
complete -c grub2-mkfont -s a -l force-autohint --description 'force autohint.'
complete -c grub2-mkfont -s b -l bold --description 'convert to bold font.'
complete -c grub2-mkfont -s c -l asce --description 'set font ascent.'
complete -c grub2-mkfont -s d -l desc --description 'set font descent.'
complete -c grub2-mkfont -s i -l index --description 'select face index.'
complete -c grub2-mkfont -s n -l name --description 'set font family name.'
complete -c grub2-mkfont -l no-bitmap --description 'ignore bitmap strikes when loading.'
complete -c grub2-mkfont -l no-hinting --description 'disable hinting.'
complete -c grub2-mkfont -s o -l output --description 'save output in FILE [required].'
complete -c grub2-mkfont -s r -l range --description 'set font range.'
complete -c grub2-mkfont -s s -l size --description 'set font size.'
complete -c grub2-mkfont -s v -l verbose --description 'print verbose messages.'
complete -c grub2-mkfont -s '?' -l help --description 'give this help list.'
complete -c grub2-mkfont -l usage --description 'give a short usage message.'
complete -c grub2-mkfont -s V -l version --description 'print program version.'

