# grub2-syslinux2cfg
# Autogenerated from man page /usr/share/man/man1/grub2-syslinux2cfg.1.gz
complete -c grub2-syslinux2cfg -s c -l cwd --description 'current directory of syslinux [default is parent directory of input file].'
complete -c grub2-syslinux2cfg -s i -l isolinux --description 'assume input is an isolinux configuration file.'
complete -c grub2-syslinux2cfg -s o -l output --description 'write output to FILE [default=stdout].'
complete -c grub2-syslinux2cfg -s p -l pxelinux --description 'assume input is a pxelinux configuration file.'
complete -c grub2-syslinux2cfg -s r -l root --description 'root directory of the syslinux disk [default=/].'
complete -c grub2-syslinux2cfg -s s -l syslinux --description 'assume input is a syslinux configuration file.'
complete -c grub2-syslinux2cfg -s t -l target-root --description 'root directory as it will be seen on runtime [default=/].'
complete -c grub2-syslinux2cfg -s T -l target-cwd --description 'current directory of syslinux as it will be seen on runtime  [default is pare…'
complete -c grub2-syslinux2cfg -s v -l verbose --description 'print verbose messages.'
complete -c grub2-syslinux2cfg -s '?' -l help --description 'give this help list.'
complete -c grub2-syslinux2cfg -l usage --description 'give a short usage message.'
complete -c grub2-syslinux2cfg -s V -l version --description 'print program version.'

