# grub2-fstest
# Autogenerated from man page /usr/share/man/man1/grub2-fstest.1.gz
complete -c grub2-fstest -s c -l diskcount --description 'Specify the number of input files.'
complete -c grub2-fstest -s C -l crypto --description 'Mount crypto devices.'
complete -c grub2-fstest -s d -l debug --description 'Set debug environment variable.'
complete -c grub2-fstest -s K -l zfs-key --description 'Load zfs crypto key.'
complete -c grub2-fstest -s n -l length --description 'Handle N bytes in output file.'
complete -c grub2-fstest -s r -l root --description 'Set root device.'
complete -c grub2-fstest -s s -l skip --description 'Skip N bytes from output file.'
complete -c grub2-fstest -s u -l uncompress --description 'Uncompress data.'
complete -c grub2-fstest -s v -l verbose --description 'print verbose messages.'
complete -c grub2-fstest -s '?' -l help --description 'give this help list.'
complete -c grub2-fstest -l usage --description 'give a short usage message.'
complete -c grub2-fstest -s V -l version --description 'print program version.'

