# grub2-probe
# Autogenerated from man page /usr/share/man/man8/grub2-probe.8.gz
complete -c grub2-probe -s 0 --description 'separate items in output using ASCII NUL characters.'
complete -c grub2-probe -s d -l device --description 'given argument is a system device, not a path.'
complete -c grub2-probe -s m -l device-map --description 'use FILE as the device map [default=/boot/grub2/device. map].'
complete -c grub2-probe -s t -l target --description 'print TARGET available targets: abstraction, arc_hints, baremetal_hints, bios…'
complete -c grub2-probe -s v -l verbose --description 'print verbose messages.'
complete -c grub2-probe -s '?' -l help --description 'give this help list.'
complete -c grub2-probe -l usage --description 'give a short usage message.'
complete -c grub2-probe -s V -l version --description 'print program version.'

