# grub2-editenv
# Autogenerated from man page /usr/share/man/man1/grub2-editenv.1.gz
complete -c grub2-editenv -s '?' -l help --description 'give this help list.'
complete -c grub2-editenv -l usage --description 'give a short usage message.'
complete -c grub2-editenv -s v -l verbose --description 'print verbose messages.'
complete -c grub2-editenv -s V -l version --description 'print program version.'

