# grub2-render-label
# Autogenerated from man page /usr/share/man/man1/grub2-render-label.1.gz
complete -c grub2-render-label -s b -l bgcolor --description 'use COLOR for background.'
complete -c grub2-render-label -s c -l color --description 'use COLOR for text.'
complete -c grub2-render-label -s f -l font --description 'use FILE as font (PF2).'
complete -c grub2-render-label -s i -l input --description 'read text from FILE.'
complete -c grub2-render-label -s o -l output --description 'set output filename.  Default is STDOUT.'
complete -c grub2-render-label -s t -l text --description 'set the label to render.'
complete -c grub2-render-label -s v -l verbose --description 'print verbose messages.'
complete -c grub2-render-label -s '?' -l help --description 'give this help list.'
complete -c grub2-render-label -l usage --description 'give a short usage message.'
complete -c grub2-render-label -s V -l version --description 'print program version.'

