# grub2-mkrelpath
# Autogenerated from man page /usr/share/man/man1/grub2-mkrelpath.1.gz
complete -c grub2-mkrelpath -s r -l relative --description 'use relative path on btrfs.'
complete -c grub2-mkrelpath -s '?' -l help --description 'give this help list.'
complete -c grub2-mkrelpath -l usage --description 'give a short usage message.'
complete -c grub2-mkrelpath -s V -l version --description 'print program version REPORTING BUGS Report bugs to <bug-grub@gnu. org>.'

