# grub2-macbless
# Autogenerated from man page /usr/share/man/man8/grub2-macbless.8.gz
complete -c grub2-macbless -s p -l ppc --description 'bless for ppc-based macs.'
complete -c grub2-macbless -s v -l verbose --description 'print verbose messages.'
complete -c grub2-macbless -s x -l x86 --description 'bless for x86-based macs.'
complete -c grub2-macbless -s '?' -l help --description 'give this help list.'
complete -c grub2-macbless -l usage --description 'give a short usage message.'
complete -c grub2-macbless -s V -l version --description 'print program version REPORTING BUGS Report bugs to <bug-grub@gnu. org>.'

