# gslj
# Autogenerated from man page /usr/share/man/man1/gslj.1.gz
complete -c gslj -l add-to-space --description 'add the given number of 1/72" units to the width of each space (may be negati…'
complete -c gslj -l add-to-width --description 'add the given number of 1/72" units to the width of each character (may be ne…'
complete -c gslj -l columns --description 'print in <n> columns.'
complete -c gslj -l detect --description 'treat the file as PostScript if it starts with %!.'
complete -c gslj -l first-page --description 'start printing at page <n>.'
complete -c gslj -l kern --description 'kern using information from the given . AFM file.'
complete -c gslj -l last-page --description 'stop printing after page <n>.'
complete -c gslj -o 12BclqRr -o 'b<header>' -o 'f<font>' -o 'F<hfont>' -o 'L<lines>' -o 'p<outfile>' --description 'Sun switches implemented:.'
complete -c gslj -o 'T<n>	set' --description 'Switches ignored:.'
complete -c gslj -o GghKkmow -s '#' -s C -s d -s J -s n -s P -s S -s s -s t -s v --description 'Switches added:.'
complete -c gslj -l spacing --description 'use double (n=2), triple (n=3), etc.  spacing.'

