# gst-play-1
# Autogenerated from man page /usr/share/man/man1/gst-play-1.0.1.gz
complete -c gst-play-1 -l help --description 'Print help synopsis and available command line options.'
complete -c gst-play-1 -l version --description 'Print version and exit.'
complete -c gst-play-1 -l audiosink --description 'Use the SOMESINK element as audio sink instead of autoaudiosink.'
complete -c gst-play-1 -l videosink --description 'Use the SOMESINK element as video sink instead of autovideosink.'
complete -c gst-play-1 -l volume --description 'Set initial playback volume to VOLUME, where 0. 0=silent and 1. 0=unchanged.'
complete -c gst-play-1 -l shuffle --description 'Shuffle playlist (play files in random order).'
complete -c gst-play-1 -l no-interactive --description 'Disable control through keyboard interaction in terminal (see below).'
complete -c gst-play-1 -l gapless --description 'Enable gapless playback.'
complete -c gst-play-1 -s v -l flags --description 'Control playback behaviour setting playbin \'flags\' property.'
complete -c gst-play-1 -l verbose --description 'Output status information and property notifications.'
complete -c gst-play-1 -s q -l quiet --description 'Do not print any output (apart from errors).'
complete -c gst-play-1 -l use-playbin3 --description 'Use playbin3 pipeline (default varies depending on \'USE_PLAYBIN\' env variable…'

