# gtk-update-icon-cache-2
# Autogenerated from man page /usr/share/man/man1/gtk-update-icon-cache-2.0.1.gz
complete -c gtk-update-icon-cache-2 -l force -s f --description 'Overwrite an existing cache file even if it appears to be uptodate.'
complete -c gtk-update-icon-cache-2 -l ignore-theme-index -s t --description 'Don\\*(Aqt check for the existence of \\*(Aqindex.'
complete -c gtk-update-icon-cache-2 -l index-only -s i --description 'Don\\*(Aqt include image data in the cache.'
complete -c gtk-update-icon-cache-2 -l include-image-data --description 'Include image data in the cache.'
complete -c gtk-update-icon-cache-2 -l source -s c --description 'Output a C header file declaring a constant name with the contents of the ico…'
complete -c gtk-update-icon-cache-2 -l quiet -s q --description 'Turn off verbose output.'
complete -c gtk-update-icon-cache-2 -l validate -s v --description 'Validate existing icon cache.'

