# gummi
# Autogenerated from man page /usr/share/man/man1/gummi.1.gz
complete -c gummi -s d --description 'run gummi with debug logging enabled.'
complete -c gummi -s h --description 'display command line options.'

