# gv2gml
# Autogenerated from man page /usr/share/man/man1/gv2gml.1.gz
complete -c gv2gml -s v --description 'Turns on verbose mode.'
complete -c gv2gml -s '?' --description 'Prints usage information and exits.'
complete -c gv2gml -s g --description 'The string gname is used as the name of the generated graph.'
complete -c gv2gml -s o --description 'Prints output to the file outfile.  If not given, gml2gv uses stdout.'

