# gxl2gv
# Autogenerated from man page /usr/share/man/man1/gxl2gv.1.gz
complete -c gxl2gv -s g --description 'The command name and input file extensions are ignored, the input is taken as…'
complete -c gxl2gv -s d --description 'The command name and input file extensions are ignored, the input is taken as…'
complete -c gxl2gv -s '?' --description 'Prints usage information and exits.'
complete -c gxl2gv -s o --description 'If specified, the output will be written into the file outfile.'

