# haveged
# Autogenerated from man page /usr/share/man/man8/haveged.8.gz
complete -c haveged -s b -l buffer --description 'Set collection buffer size to nnn KW.  Default is 128KW (or 512KB).'
complete -c haveged -s d -l data --description 'Set data cache size to nnn KB.  Default is 16 or as determined dynamically.'
complete -c haveged -s f -l file --description 'Set output file path for non-daemon use.'
complete -c haveged -s F -l Foreground --description 'Run daemon in foreground.  Do not fork and detach.'
complete -c haveged -s i -l inst --description 'Set instruction cache size to nnn KB.'
complete -c haveged -s n -l number --description 'Set number of bytes written to the output file.'
complete -c haveged -s o -l onlinetest --description 'Specify online tests to run.'
complete -c haveged -s p -l pidfile --description 'Set file path for the daemon pid file.  Default is "/var/run/haveged. pid",.'
complete -c haveged -s r -l run --description 'Set run level for daemon interface:  n = 0 Run as daemon - must be root.'
complete -c haveged -s v -l verbose --description 'Set diagnostic bitmap as sum of following options:  1=Show build/tuning summa…'
complete -c haveged -s w -l write --description 'Set write_wakeup_threshold of daemon interface to nnn bits.'
complete -c haveged -s '?' -l help --description 'This summary of program options.'

