# hciattach
# Autogenerated from man page /usr/share/man/man1/hciattach.1.gz
complete -c hciattach -s b --description 'Send break.'
complete -c hciattach -s n --description 'Don\'t detach from controlling terminal.'
complete -c hciattach -s p --description 'Print the PID when detaching.'
complete -c hciattach -s t --description 'Specify an initialization timeout.   (Default is 5 seconds. ).'
complete -c hciattach -s s --description 'Specify an initial speed instead of the hardware default.'
complete -c hciattach -s l --description 'List all available configurations.'
complete -c hciattach -s r --description 'Set the HCI device into raw mode (the kernel and bluetoothd will ignore it).'

