# hcitool
# Autogenerated from man page /usr/share/man/man1/hcitool.1.gz
complete -c hcitool -s h --description 'Gives a list of possible commands.'
complete -c hcitool -s i --description 'The command is applied to device.'
complete -c hcitool -l pkt-type --description 'specifies a list of allowed packet types.'
complete -c hcitool -l role --description 'can have value.'

