# hcopy
# Autogenerated from man page /usr/share/man/man1/hcopy.1.gz
complete -c hcopy -s m --description '"MacBinary II" : A popular format for binary file transfer.'
complete -c hcopy -s b --description 'BinHex : An alternative format for ASCII file transfer.'
complete -c hcopy -s t --description 'Text : Performs end-of-line translation.'
complete -c hcopy -s r --description '"Raw Data" : Performs no translation.'
complete -c hcopy -s a --description 'Automatic : A mode will be chosen automatically for each file based on a set …'

