# img2webp
# Autogenerated from man page /usr/local/share/man/man1/img2webp.1
complete -c img2webp -s o --description 'Specify the name of the output WebP file.'
complete -c img2webp -o min_size --description 'Encode images to achieve smallest size.'
complete -c img2webp -o mixed --description '.'
complete -c img2webp -o kmin --description '.'
complete -c img2webp -o kmax --description 'Specify the minimum and maximum distance between consecutive key frames (inde…'
complete -c img2webp -o loop --description 'Specifies the number of times the animation should loop.'
complete -c img2webp -s v --description 'Be more verbose.'
complete -c img2webp -s h -o help --description 'A short usage summary.'
complete -c img2webp -o version --description 'Print the version numbers of the relevant libraries used.'
complete -c img2webp -s d --description 'Specify the image duration in milliseconds.'
complete -c img2webp -o lossless -o lossy --description 'Compress the next image(s) using lossless or lossy compression mode.'
complete -c img2webp -s q --description 'Specify the compression factor between 0 and 100.  The default is 75.'
complete -c img2webp -s m --description 'Specify the compression method to use.'

