# infotopam
# Autogenerated from man page /usr/share/man/man1/infotopam.1.gz
complete -c infotopam -o forcecolor --description 'sp Forces infotopam to convert 1 bit-plane icons to color PAM   images instea…'
complete -c infotopam -o numcolors --description 'sp Tells infotopam how many colors to override.   Pixels in the   Amiga .'
complete -c infotopam -o selected --description '.'

