# innochecksum
# Autogenerated from man page /usr/share/man/man1/innochecksum.1.gz
complete -c innochecksum -s '?' -l help --description '.'
complete -c innochecksum -s c -l count --description '.'
complete -c innochecksum -s d -l debug --description '.'
complete -c innochecksum -s e -l end-page --description '.'
complete -c innochecksum -s i -l per-page-details --description '.'
complete -c innochecksum -s I -l info --description '.'
complete -c innochecksum -s l -l leaf --description '.'
complete -c innochecksum -s m -l merge --description '.'
complete -c innochecksum -s p -l page-num --description '.'
complete -c innochecksum -s s -l start-page --description '.'
complete -c innochecksum -s u -l skip-corrupt --description '.'
complete -c innochecksum -s v -l verbose --description '.'
complete -c innochecksum -s V -l version --description '.'

