# ipset
# Autogenerated from man page /usr/share/man/man8/ipset.8.gz
complete -c ipset -o exist --description 'Ignore errors when exactly the same set is to be created or already added ent…'
complete -c ipset -s o -o output --description 'Select the output format to the list command.'
complete -c ipset -s q -o quiet --description 'Suppress any output to stdout and stderr.'
complete -c ipset -s r -o resolve --description 'When listing sets, enforce name lookup.'
complete -c ipset -s s -o sorted --description 'Sorted output.  When listing sets entries are listed sorted.'
complete -c ipset -s n -o name --description 'List just the names of the existing sets, i. e.'
complete -c ipset -s t -o terse --description 'List the set names and headers, i. e.  suppress listing of set members.'

