# jjs-java-11-openjdk
# Autogenerated from man page /usr/share/man/man1/jjs-java-11-openjdk.1.gz
complete -c jjs-java-11-openjdk -o cp --description 'Specifies the path to the supporting class files To set multiple paths, the o…'
complete -c jjs-java-11-openjdk -o Dname --description 'Sets a system property to be passed to the script by assigning a value to a p…'
complete -c jjs-java-11-openjdk -o 'doe
.br
--dump-on-error' --description 'Provides a full stack trace when an error occurs.'
complete -c jjs-java-11-openjdk -o 'fv
.br
--fullversion' --description 'Prints the full Nashorn version string.'
complete -c jjs-java-11-openjdk -o fx --description 'Launches the script as a JavaFX application.'
complete -c jjs-java-11-openjdk -o 'h
.br
-help' --description 'Prints the list of options and their descriptions.'
complete -c jjs-java-11-openjdk -l language --description 'Specifies the ECMAScript language version.  The default version is ES5.'
complete -c jjs-java-11-openjdk -o 'ot
.br
--optimistic-types' --description 'Enables or disables optimistic type assumptions with deoptimizing recompilati…'
complete -c jjs-java-11-openjdk -o scripting --description 'Enables shell scripting features.'
complete -c jjs-java-11-openjdk -o strict --description 'Enables strict mode, which enforces stronger adherence to the standard (ECMAS…'
complete -c jjs-java-11-openjdk -s t --description 'Sets the specified time zone for script execution.'
complete -c jjs-java-11-openjdk -o 'v
.br
-version' --description 'Prints the Nashorn version string.'
complete -c jjs-java-11-openjdk -o classpath --description '.'
complete -c jjs-java-11-openjdk -o doe --description '.'
complete -c jjs-java-11-openjdk -l dump-on-error --description '.'
complete -c jjs-java-11-openjdk -o fv --description '.'
complete -c jjs-java-11-openjdk -l fullversion --description '.'
complete -c jjs-java-11-openjdk -s h --description '.'
complete -c jjs-java-11-openjdk -o help --description '.'
complete -c jjs-java-11-openjdk -o ot --description '.'
complete -c jjs-java-11-openjdk -l optimistic-types --description '.'
complete -c jjs-java-11-openjdk -o timezone --description '.'
complete -c jjs-java-11-openjdk -s v --description '.'
complete -c jjs-java-11-openjdk -o version --description '.'

