# jpeg2ktopam
# Autogenerated from man page /usr/share/man/man1/jpeg2ktopam.1.gz
complete -c jpeg2ktopam -o verbose --description 'This option causes jpeg2ktopam to issue informational messages about the conv…'
complete -c jpeg2ktopam -o debuglevel --description 'This option controls debug messages from the Jasper library.'

