# killproc
# Autogenerated from man page /usr/share/man/man8/killproc.8.gz
complete -c killproc -s G --description 'Sends the signal to all session followers (children) of the identified proces…'
complete -c killproc -s g --description 'Sends the signal to all members of the session including the identified proce…'
complete -c killproc -s L --description 'This option causes symlinks to be followed, as the like-named option in  ls (…'
complete -c killproc -s p --description '(Former option  -f changed due to the LSB specification.'
complete -c killproc -s i --description 'The pid found in this file is used as  session id of the same binary program …'
complete -c killproc -s c --description 'Change root directory to  root for services which have been started with this…'
complete -c killproc -s n --description 'This option indicates that a kernel thread should be signaled.'
complete -c killproc -s N --description 'With this option the location of the executable is checked about NFS file sys…'
complete -c killproc -o '<SIG>' --description 'Signals  can be specified either by name . RB (e. g.'
complete -c killproc -o 't<sec>' --description 'The number  <sec> specifies the seconds to wait between the default signal  S…'
complete -c killproc -s q --description 'This option is ignored.'
complete -c killproc -s v --description 'Be more verbose. \\".'
complete -c killproc -s l --description 'This option list all available signals and some of their synonyms by their nu…'
complete -c killproc -s t --description 'If a program has been terminated successfully and a verified pid file was fou…'
complete -c killproc -s f --description 'changed due to the LSB specification).'
complete -c killproc -s x --description 'Tells killproc to use the upto 15 byte long filename name found in /proc/<pid…'

