# kpsetool
# Autogenerated from man page /usr/share/man/man1/kpsetool.1.gz
complete -c kpsetool -s m --description 'set Metafont mode.'
complete -c kpsetool -s n --description 'pretend to be progname to kpathsea.'
complete -c kpsetool -s p --description 'act like kpsepath(1).'
complete -c kpsetool -s v --description 'act like kpsexpand(1).'

