# lav2yuv
# Autogenerated from man page /usr/share/man/man1/lav2yuv.1.gz
complete -c lav2yuv -s m --description 'Force mono-chrome.'
complete -c lav2yuv -s c --description 'Conceal frames containing corrupt MJPEG data by repeating the preceeding good…'
complete -c lav2yuv -s S --description 'Output a scene list with scene detection.'
complete -c lav2yuv -s T --description 'Set scene detection threshold to num (default: 4).'
complete -c lav2yuv -s D --description 'Width decimation to use for scene detection (default: 2).'
complete -c lav2yuv -s o --description 'Frame offset - skip num frames at the beginning.'
complete -c lav2yuv -s f --description 'Only num frames are written to stdout.  0 means that all frames are processed.'
complete -c lav2yuv -s A --description 'Set/override the sample aspect ratio (SAR) emitted in the output stream heade…'
complete -c lav2yuv -s P --description 'Set the intended/approximate display aspect ratio (DAR) for the stream.'
complete -c lav2yuv -s C --description 'Set output chroma (default: \'420jpeg\').'

