# lavpipe
# Autogenerated from man page /usr/share/man/man1/lavpipe.1.gz
complete -c lavpipe -s o --description 'This is the frame offset of the output video.'
complete -c lavpipe -s n --description 'This is the frame count.'

