# ldapurl
# Autogenerated from man page /usr/share/man/man1/ldapurl.1.gz
complete -c ldapurl -s a --description 'Set a comma-separated list of attribute selectors.'
complete -c ldapurl -s b --description 'Set the searchbase.'
complete -c ldapurl -s e --description 'Specify general extensions with -e \'!\' indicates criticality.'
complete -c ldapurl -s E --description 'Set URL extensions; incompatible with  -H .'
complete -c ldapurl -s f --description 'Set the URL filter.'
complete -c ldapurl -s H --description 'Specify URI to be exploded.'
complete -c ldapurl -s h --description 'Set the host.'
complete -c ldapurl -s p --description 'Set the TCP port.'
complete -c ldapurl -s S --description 'Set the URL scheme.'
complete -c ldapurl -s s --description 'OPTIONS.'

