# locale
# Autogenerated from man page /usr/share/man/man1/locale.1.gz
complete -c locale -s a -l all-locales --description 'Display a list of all available locales.'
complete -c locale -s m -l charmaps --description 'Display the available charmaps (character set description files).'
complete -c locale -s c -l category-name --description 'For a category name argument, write the name of the locale category on a sepa…'
complete -c locale -s k -l keyword-name --description 'For each keyword whose value is being displayed, include also the name of tha…'
complete -c locale -s v -l verbose --description 'Display additional information for some command-line option and argument comb…'
complete -c locale -s '?' -l help --description 'Display a summary of command-line options and arguments and exit.'
complete -c locale -l usage --description 'Display a short usage message and exit.'
complete -c locale -s V -l version --description 'Display the program version and exit.  FILES.'

