# lpoptions
# Autogenerated from man page /usr/share/man/man1/lpoptions.1.gz
complete -c lpoptions -s E --description 'Enables encryption when communicating with the CUPS server.'
complete -c lpoptions -s U --description 'Uses an alternate username.'
complete -c lpoptions -s d --description 'Sets the user default printer to destination.'
complete -c lpoptions -s h --description 'Uses an alternate server.'
complete -c lpoptions -s l --description 'Lists the printer specific options and their current settings.'
complete -c lpoptions -s o --description 'Specifies a new option for the named destination.'
complete -c lpoptions -s p --description 'Sets the destination and instance, if specified, for any options that follow.'
complete -c lpoptions -s r --description 'Removes the specified option from the named destination.'
complete -c lpoptions -s x --description 'Removes the options for the named destination and instance, if specified.'

