# lpq
# Autogenerated from man page /usr/share/man/man1/lpq.1.gz
complete -c lpq -s E --description 'Forces encryption when connecting to the server.'
complete -c lpq -s P --description 'Specifies an alternate printer or class name.'
complete -c lpq -s U --description 'Specifies an alternate username.'
complete -c lpq -s a --description 'Reports jobs on all printers.'
complete -c lpq -s h --description 'Specifies an alternate server.'
complete -c lpq -s l --description 'Requests a more verbose (long) reporting format.'

