# lscp
# Autogenerated from man page /usr/share/man/man1/lscp.1.gz
complete -c lscp -s a -l all --description 'Do not hide minor checkpoints.'
complete -c lscp -s b -l show-block-count --description 'Show number of used blocks instead of appended blocks.'
complete -c lscp -s g -l show-increment --description 'Show number of appended blocks instead of used blocks.'
complete -c lscp -s r -l reverse --description 'Reverse order.'
complete -c lscp -s s -l snapshot --description 'List only snapshots.'
complete -c lscp -s i -l index --description 'Skip index checkpoints (or snapshots) at start of input.'
complete -c lscp -s n -l lines --description 'List only lines input checkpoints (or snapshots).'
complete -c lscp -s h -l help --description 'Display help message and exit.'
complete -c lscp -s V -l version --description 'Display version and exit.'

