# lspcmcia
# Autogenerated from man page /usr/share/man/man8/lspcmcia.8.gz
complete -c lspcmcia -s V --description 'Show version information and exit.'
complete -c lspcmcia -l not --description '.'
complete -c lspcmcia -s v --description 'Increase the verbosity of the ls command.'

