# lssu
# Autogenerated from man page /usr/share/man/man1/lssu.1.gz
complete -c lssu -s a -l all --description 'Do not hide clean segments.'
complete -c lssu -s h -l help --description 'Display help message and exit.'
complete -c lssu -s i -l index --description 'Skip index segments at start of input.'
complete -c lssu -s l -l latest-usage --description 'Print usage status of the moment.'
complete -c lssu -s n -l lines --description 'List only lines input segments.'
complete -c lssu -s p -l protection-period --description 'Specify protection period.'
complete -c lssu -s V -l version --description 'Display version and exit.'

