# mailstat
# Autogenerated from man page /usr/share/man/man1/mailstat.1.gz
complete -c mailstat -s k --description 'keep logfile intact.'
complete -c mailstat -s l --description 'long display format.'
complete -c mailstat -s m --description 'merge any errors into one line.'
complete -c mailstat -s o --description 'use the old logfile.'
complete -c mailstat -s t --description 'terse display format.'
complete -c mailstat -s s --description 'silent in case of no mail NOTES Customise to your heart\'s content, this progr…'

