# makeindex
# Autogenerated from man page /usr/share/man/man1/makeindex.1.gz
complete -c makeindex -s c --description 'Compress intermediate blanks (ignoring leading and trailing blanks and tabs).'
complete -c makeindex -s g --description 'Employ German word ordering in the index, in accord with rules set forth in D…'
complete -c makeindex -s i --description 'Take input from R stdin .'
complete -c makeindex -s l --description 'Letter ordering; by default, word ordering is used (see the \\s-2ORDERING\\s+2 …'
complete -c makeindex -s o --description 'Employ  ind as the output index file.'
complete -c makeindex -s p --description 'Set the starting page number of the output index file to be  num (useful when…'
complete -c makeindex -s q --description 'Quiet mode; send no messages to R stderr .'
complete -c makeindex -s r --description 'Disable implicit page range formation; page ranges must be created by using e…'
complete -c makeindex -s s --description 'Employ  sty as the style file (no default).'
complete -c makeindex -s t --description 'Employ  log as the transcript file.'
complete -c makeindex -s L --description 'sort based on locale settings.  Not available on all systems.'
complete -c makeindex -s T --description 'special support for Thai documents.  Not available on all systems.'
complete -c makeindex -o ms --description 'macros (note that at some sites, this macro should replace a pre-existing mac…'

