# mft
# Autogenerated from man page /usr/share/man/man1/mft.1.gz
complete -c mft -o change --description 'Apply the change file  change_file_name to R mf_file_name . PP.'
complete -c mft -o metapost --description 'Assume  mf_file_name is a \\*(MP source file (this is the default if  mf_file_…'
complete -c mft -o style --description 'Use the style file style_file_name insted of plain. mft (or mplain.'

