# mib2c
# Autogenerated from man page /usr/share/man/man1/mib2c.1.gz
complete -c mib2c -s h --description 'Display a help message.'
complete -c mib2c -s c --description 'Use CONFIGFILE when generating code.'
complete -c mib2c -s I --description 'Search for configuration files in PATH.'
complete -c mib2c -s f --description 'Places the output code into OUTNAME. c and OUTNAME. h.'
complete -c mib2c -s i --description 'Do not run indent on the resulting code.'
complete -c mib2c -s s --description 'Do not look for MIBNODE. sed and run sed on the resulting code.'
complete -c mib2c -s q --description 'Run in "quiet" mode, which minimizes the status messages mib2c generates.'

