# mksubvolume
# Autogenerated from man page /usr/share/man/man8/mksubvolume.8.gz
complete -c mksubvolume -l nocow --description 'Set the no-copy-on-write flag for the subvolume.'
complete -c mksubvolume -s v -l verbose --description 'Increase verbosity.'

