# mktexlsr
# Autogenerated from man page /usr/share/man/man1/mktexlsr.1.gz
complete -c mktexlsr -l help --description 'Print help message and exit.'
complete -c mktexlsr -l version --description 'Print version information and exit.'

