# mkzftree
# Autogenerated from man page /usr/share/man/man1/mkzftree.1.gz
complete -c mkzftree -s f -l force --description 'Always compress all files, even if they get larger when compressed.'
complete -c mkzftree -s z -l level --description 'Select compression level (1-9, default is 9).'
complete -c mkzftree -s u -l uncompress --description 'Uncompress an already compressed tree.'
complete -c mkzftree -s p -l parallelism --description 'Compress in parallel.'
complete -c mkzftree -s x -l one-filesystem --description 'Do not cross filesystem boundaries, but create directory stubs at mount point…'
complete -c mkzftree -s X -l strict-one-filesystem --description 'Do not cross filesystem boundaries, and do not create directory stubs at moun…'
complete -c mkzftree -s C -l crib-path --description 'Steal ("crib") files from another directory if it looks (based on name, size,…'
complete -c mkzftree -s l -l local --description 'Do not recurse into subdirectories, but create the directories themselves.'
complete -c mkzftree -s L -l strict-local --description 'Do not recurse into subdirectories, and do not create directories.'
complete -c mkzftree -s F -l file --description 'Indicates that INPUT may not necessarily be a directory; this allows operatio…'
complete -c mkzftree -s s -l sloppy --description 'Treat file modes, times and ownership data as less than precious information …'
complete -c mkzftree -s v -l verbose --description 'Increase the program verbosity.'
complete -c mkzftree -s V -l verbosity --description 'Set the program verbosity to R value .'
complete -c mkzftree -s q -l quiet --description 'Issue no messages whatsoever, including error messages.'
complete -c mkzftree -s h -l help --description 'Display a brief help message.'
complete -c mkzftree -s w -l version --description 'Display the release version.'

