# mkzimage_cmdline
# Autogenerated from man page /usr/share/man/man8/mkzimage_cmdline.8.gz
complete -c mkzimage_cmdline -s a --description 'activate or deactivate the the cmdline.'
complete -c mkzimage_cmdline -s s --description 'pass this string to the kernel.  It can be up to 511 chars long.'
complete -c mkzimage_cmdline -s c --description 'clear cmdline area in zImage AUTHOR Olaf Hering <olh@suse. de>.'

