# more
# Autogenerated from man page /usr/share/man/man1/more.1.gz
complete -c more -s d --description 'Prompt with "[Press space to continue, \'q\' to quit.'
complete -c more -s l --description 'Do not pause after any line containing a  ^L (form feed).'
complete -c more -s f --description 'Count logical lines, rather than screen lines (i. e.'
complete -c more -s p --description 'Do not scroll.   Instead, clear the whole screen and then display the text.'
complete -c more -s c --description 'Do not scroll.'
complete -c more -s s --description 'Squeeze multiple blank lines into one.'
complete -c more -s u --description 'Suppress underlining.'
complete -c more -l help --description 'Display help text and exit.'
complete -c more -s V -l version --description 'Display version information and exit.'

