# mountstats
# Autogenerated from man page /usr/share/man/man8/mountstats.8.gz
complete -c mountstats -s h -l help --description 'show the help message and exit.'
complete -c mountstats -s v -l version --description 'show program\'s version number and exit.'
complete -c mountstats -s f -l file --description 'Read stats from  infile instead of  R /proc/self/mountstats ".'
complete -c mountstats -s S -l since --description 'Show difference between current stats and those in R sincefile ".'
complete -c mountstats -s r -l rpc --description 'Display only the RPC statistics.'
complete -c mountstats -s R -l raw --description 'Display only the raw statistics.'
complete -c mountstats -s 3 --description 'Show only NFS version 3 statistics.'
complete -c mountstats -s n -l nfs --description 'Display only the NFS statistics.'
complete -c mountstats -s 4 --description 'Show only NFS version 4 statistics.'

