# mp2enc
# Autogenerated from man page /usr/share/man/man1/mp2enc.1.gz
complete -c mp2enc -s o --description 'Specifies the name for the output file.'
complete -c mp2enc -s v --description 'Set verbosity level to num.'
complete -c mp2enc -s '?' --description 'Display a synopsis of the command syntax.'
complete -c mp2enc -s R --description 'Indicate, that the input is raw PCM without header.'
complete -c mp2enc -s b --description '.'
complete -c mp2enc -s r --description 'Sets the audio sampling rate of the reconstructed output signal in Hz.'
complete -c mp2enc -s l --description 'Sets the audio layer.  Legal values are 1 and 2.  The default is layer II.'
complete -c mp2enc -s s --description 'Force stereo output.'
complete -c mp2enc -s m --description 'Force mono output.   A stereo input signal is down-mixed before encoding.'
complete -c mp2enc -s e --description 'Use CRC error protection.'
complete -c mp2enc -s V --description 'Force VCD compatible output.'

