# mv
# Autogenerated from man page /usr/share/man/man1/mv.1.gz
complete -c mv -l backup --description 'make a backup of each existing destination file.'
complete -c mv -s b --description 'like --backup but does not accept an argument.'
complete -c mv -s f -l force --description 'do not prompt before overwriting.'
complete -c mv -s i -l interactive --description 'prompt before overwrite.'
complete -c mv -s n -l no-clobber --description 'do not overwrite an existing file .'
complete -c mv -l strip-trailing-slashes --description 'remove any trailing slashes from each SOURCE argument.'
complete -c mv -s S -l suffix --description 'override the usual backup suffix.'
complete -c mv -s t -l target-directory --description 'move all SOURCE arguments into DIRECTORY.'
complete -c mv -s T -l no-target-directory --description 'treat DEST as a normal file.'
complete -c mv -s u -l update --description 'move only when the SOURCE file is newer than the destination file or when the…'
complete -c mv -s v -l verbose --description 'explain what is being done.'
complete -c mv -s Z -l context --description 'set SELinux security context of destination file to default type.'
complete -c mv -l help --description 'display this help and exit.'
complete -c mv -l version --description 'output version information and exit .'

