# mvxattr
# Autogenerated from man page /usr/share/man/man1/mvxattr.1.gz
complete -c mvxattr -s s -l from --description 'Source xattr name.'
complete -c mvxattr -s d -l to --description 'Destination xattr name.'
complete -c mvxattr -s l -l follow-symlinks --description 'Follow symlinks, the default is to ignore them.'
complete -c mvxattr -s p -l print --description 'Print files where the xattr got renamed.'
complete -c mvxattr -s v -l verbose --description 'Print files as they are checked.'
complete -c mvxattr -s f -l force --description 'Force overwriting of destination xattr.'

