# needs-restarting
# Autogenerated from man page /usr/share/man/man1/needs-restarting.1.gz
complete -c needs-restarting -s h -l help --description '.'
complete -c needs-restarting -s r -l reboothint --description '.'
complete -c needs-restarting -s s -l services --description '.'

