# net-snmp-create-v3-user
# Autogenerated from man page /usr/share/man/man1/net-snmp-create-v3-user.1.gz
complete -c net-snmp-create-v3-user -l version --description 'displays the net-snmp version number.'
complete -c net-snmp-create-v3-user -o ro --description 'create an user with read-only permissions.'
complete -c net-snmp-create-v3-user -s a --description 'specify authentication password.'
complete -c net-snmp-create-v3-user -s x --description 'specify encryption password.'
complete -c net-snmp-create-v3-user -s X --description 'specify encryption algorithm.'

