# nfnl_osf
# Autogenerated from man page /usr/share/man/man8/nfnl_osf.8.gz
complete -c nfnl_osf -s f --description 'Read signatures from file R fingerprints .'
complete -c nfnl_osf -s d --description 'Instead of adding the signatures from fingerprints into the kernel, remove th…'
complete -c nfnl_osf -s 1 --description 'Illegal arguments passed, fingerprints file not readable or failure in netlin…'
complete -c nfnl_osf -o ENOENT --description 'Fingerprints file not specified.'
complete -c nfnl_osf -o EINVAL --description 'Netlink handle initialization failed or fingerprints file format invalid.'

