# nfsiostat
# Autogenerated from man page /usr/share/man/man8/nfsiostat.8.gz
complete -c nfsiostat -s a -l attr --description 'displays statistics related to the attribute cache.'
complete -c nfsiostat -s d -l dir --description 'displays statistics related to directory operations.'
complete -c nfsiostat -s h -l help --description 'shows help message and exit.'
complete -c nfsiostat -s l -l list --description 'only print stats for first LIST mount points.'
complete -c nfsiostat -s p -l page --description 'displays statistics related to the page cache.'
complete -c nfsiostat -s s -l sort --description 'Sort NFS mount points by ops/second.'
complete -c nfsiostat -l version --description 'show program\'s version number and exit FILES.'

