# nice
# Autogenerated from man page /usr/share/man/man1/nice.1.gz
complete -c nice -s n -l adjustment --description 'add integer N to the niceness (default 10).'
complete -c nice -l help --description 'display this help and exit.'
complete -c nice -o 20 --description '.'
complete -c nice -l version --description 'output version information and exit.'

