# nilfs_cleanerd
# Autogenerated from man page /usr/share/man/man8/nilfs_cleanerd.8.gz
complete -c nilfs_cleanerd -s V -l version --description 'Display version and exit.'
complete -c nilfs_cleanerd -s h -l help --description 'Display help message and exit.'
complete -c nilfs_cleanerd -s c -l conf --description 'Specify configuration file.'
complete -c nilfs_cleanerd -s p -l protection-period --description 'Override protection period with the specified number of seconds.'

