# nmbd
# Autogenerated from man page /usr/share/man/man8/nmbd.8.gz
complete -c nmbd -s D -l daemon --description 'If specified, this parameter causes nmbd to operate as a daemon.'
complete -c nmbd -s F -l foreground --description 'If specified, this parameter causes the main nmbd process to not daemonize, i.'
complete -c nmbd -s S -l log-stdout --description 'If specified, this parameter causes nmbd to log to standard output rather tha…'
complete -c nmbd -s i -l interactive --description 'If this parameter is specified it causes the server to run "interactively", n…'
complete -c nmbd -s '?' -l help --description 'Print a summary of command line options.'
complete -c nmbd -l usage --description 'Display brief usage message.'
complete -c nmbd -s H -l hosts --description 'NetBIOS lmhosts file.'
complete -c nmbd -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c nmbd -s V -l version --description 'Prints the program version number.'
complete -c nmbd -s s -l configfile --description 'The file specified contains the configuration details required by the server.'
complete -c nmbd -s l -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c nmbd -l option --description 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line.'
complete -c nmbd -s p -l port --description 'UDP port number is a positive integer value.'
complete -c nmbd -l no-process-group --description 'Do not create a new process group for nmbd.'

