# nop
# Autogenerated from man page /usr/share/man/man1/nop.1.gz
complete -c nop -s p --description 'Produce no output - just check the input for valid DOT.'
complete -c nop -s '?' --description 'Print usage information.'

