# ntfscp
# Autogenerated from man page /usr/share/man/man8/ntfscp.8.gz
complete -c ntfscp -s a -l attribute --description 'Write to this attribute.'
complete -c ntfscp -s i -l inode --description 'Treat  destination as inode number.'
complete -c ntfscp -s m -l min-fragments --description 'Minimize fragmentation when allocating space to the attribute.'
complete -c ntfscp -s N -l attr-name --description 'Write to attribute with this name.'
complete -c ntfscp -s n -l no-action --description 'Use this option to make a test run before doing the real copy operation.'
complete -c ntfscp -s f -l force --description 'This will override some sensible defaults, such as not working with a mounted…'
complete -c ntfscp -s h -l help --description 'Show a list of options with a brief description of each one.'
complete -c ntfscp -s q -l quiet --description 'Suppress some debug/warning/error messages.'
complete -c ntfscp -s V -l version --description 'Show the version number, copyright and license  ntfscp .'
complete -c ntfscp -o fv --description 'is equivalent to.'
complete -c ntfscp -s v --description 'Long named options can be abbreviated to any unique prefix of their name.'
complete -c ntfscp -l verbose --description 'Display more debug/warning/error messages.'

