# ntfsrecover
# Autogenerated from man page /usr/share/man/man8/ntfsrecover.8.gz
complete -c ntfsrecover -s b -l backward --description 'Examine the actions described in the logfile backward from the latest one to …'
complete -c ntfsrecover -s c -l clusters --description 'Restrict the output generated when using options -b -f -u -p to the actions o…'
complete -c ntfsrecover -s f -l forward --description 'Examine the actions described in the logfile forward from the first one to th…'
complete -c ntfsrecover -s h -l help --description 'Show some help information.'
complete -c ntfsrecover -s n -l no-action --description 'Do not apply any modification, useful when using the options -p, -s or -u.'
complete -c ntfsrecover -s p -l play --description 'Undo COUNT transaction sets and redo a single one, a transaction set being al…'
complete -c ntfsrecover -s r -l range --description 'Examine the actions described in the logfile forward restricted to the reques…'
complete -c ntfsrecover -s s -l sync --description 'Sync the file system by applying the committed actions which have not been sy…'
complete -c ntfsrecover -s t -l transactions --description 'Display the transaction parameters when examining the log file with one of th…'
complete -c ntfsrecover -s u -l undo --description 'Undo COUNT transaction sets, thus resetting the file system to some checkpoin…'
complete -c ntfsrecover -s v -l verbose --description 'Display more debug/warning/error messages.'
complete -c ntfsrecover -o bv --description 'is equivalent to.'
complete -c ntfsrecover -s V -l version --description 'Show the version number, copyright and license of ntfsrecover .'

