# ntfslabel
# Autogenerated from man page /usr/share/man/man8/ntfslabel.8.gz
complete -c ntfslabel -s f -l force --description 'This will override some sensible defaults, such as not working with a mounted…'
complete -c ntfslabel -s h -l help --description 'Show a list of options with a brief description of each one.'
complete -c ntfslabel -l new-half-serial --description 'Set a new serial number to the device, either the argument value, or a random…'
complete -c ntfslabel -s n -l no-action --description 'Don\'t actually write to disk.'
complete -c ntfslabel -s q -l quiet --description 'Reduce the amount of output to a minimum.'
complete -c ntfslabel -s v -l verbose --description 'Increase the amount of output that  ntfslabel prints.'
complete -c ntfslabel -s L --description 'option of mkntfs (8) during creation of the file system.'
complete -c ntfslabel -o fv --description 'is equivalent to.'
complete -c ntfslabel -l new-serial --description '.'
complete -c ntfslabel -s V -l version --description 'Show the version number, copyright and license for ntfslabel .'

