# ntfsresize
# Autogenerated from man page /usr/share/man/man8/ntfsresize.8.gz
complete -c ntfsresize -s c -l check --description 'By using this option ntfsresize will only check the device to ensure that it …'
complete -c ntfsresize -s i -l info --description 'By using this option without --expand, ntfsresize will determine the theoreti…'
complete -c ntfsresize -s m -l info-mb-only --description 'Like the info option, only print out the shrinkable size in MB.'
complete -c ntfsresize -s s -l size --description 'Resize filesystem to fit in a partition whose size is SIZE[k|M|G] bytes by sh…'
complete -c ntfsresize -s x -l expand --description 'Expand the filesystem to the current partition size, shifting down its beginn…'
complete -c ntfsresize -s f -l force --description 'Forces ntfsresize to proceed with the resize operation either without prompti…'
complete -c ntfsresize -s n -l no-action --description 'Use this option to make a test run before doing the real resize operation.'
complete -c ntfsresize -s b -l bad-sectors --description 'Support disks having hardware errors, bad sectors with those  ntfsresize woul…'
complete -c ntfsresize -s P -l no-progress-bar --description 'Don\'t show progress bars.'
complete -c ntfsresize -s v -l verbose --description 'More output.'
complete -c ntfsresize -s V -l version --description 'Print the version number of  ntfsresize and exit.'
complete -c ntfsresize -o fv --description 'is equivalent to.'
complete -c ntfsresize -s h -l help --description 'Display help and exit.'

