# ntfscat
# Autogenerated from man page /usr/share/man/man8/ntfscat.8.gz
complete -c ntfscat -s a -l attribute --description 'Display the contents of a particular attribute type.'
complete -c ntfscat -s n -l attribute-name --description 'Display this named attribute, stream.'
complete -c ntfscat -s i -l inode --description 'Specify a file by its inode number instead of its name.'
complete -c ntfscat -s f -l force --description 'This will override some sensible defaults, such as not using a mounted volume.'
complete -c ntfscat -s h -l help --description 'Show a list of options with a brief description of each one.'
complete -c ntfscat -s q -l quiet --description 'Suppress some debug/warning/error messages.'
complete -c ntfscat -s V -l version --description 'Show the version number, copyright and license  ntfscat .'
complete -c ntfscat -o fv --description 'is equivalent to.'
complete -c ntfscat -s v --description 'Long named options can be abbreviated to any unique prefix of their name.'
complete -c ntfscat -l verbose --description 'Display more debug/warning/error messages.'

