# nvme-dsm
# Autogenerated from man page /usr/share/man/man1/nvme-dsm.1.gz
complete -c nvme-dsm -s n -l namespace-id --description 'Sends the command with the requested nsid.'
complete -c nvme-dsm -s a -l ctx-attrs --description 'Comma separated list of the context attributes in each range.'
complete -c nvme-dsm -s b -l blocks --description 'Comma separated list of the number of blocks in each range.'
complete -c nvme-dsm -s s -l slbs --description 'Comma separated list of the starting block in each range.'
complete -c nvme-dsm -s d -l ad --description 'Attribute Deallocate.'
complete -c nvme-dsm -s w -l idw --description 'Attribute Integral Dataset for Write.'
complete -c nvme-dsm -s r -l idr --description 'Attribute Integral Dataset for Read.'
complete -c nvme-dsm -s c -l cdw11 --description 'All the command command dword 11 attributes.'

