# nvme-get-property
# Autogenerated from man page /usr/share/man/man1/nvme-get-property.1.gz
complete -c nvme-get-property -s o -l offset --description 'The offset of the property.'
complete -c nvme-get-property -s H --description '--human-readable: Show the fields packed in the property.'
complete -c nvme-get-property -l human-readable --description '.'

