# nvme-write-zeroes
# Autogenerated from man page /usr/share/man/man1/nvme-write-zeroes.1.gz
complete -c nvme-write-zeroes -l start-block -s s --description 'Start block.'
complete -c nvme-write-zeroes -l block-count -s c --description 'Number of logical blocks to write zeroes.'
complete -c nvme-write-zeroes -l prinfo -s p --description 'Protection Information field definition.'
complete -c nvme-write-zeroes -l ref-tag -s r --description 'Optional reftag when used with protection information.'
complete -c nvme-write-zeroes -l app-tag-mask -s m --description 'Optional application tag mask when used with protection information.'
complete -c nvme-write-zeroes -l app-tag -s a --description 'Optional application tag when used with protection information.'
complete -c nvme-write-zeroes -l limited-retry -s l --description 'Sets the limited retry flag.'
complete -c nvme-write-zeroes -l deac -s d --description 'Sets the DEAC bit, requesting controller deallocate the logical blocks.'
complete -c nvme-write-zeroes -l force-unit-access -s f --description 'Set the force-unit access flag.'
complete -c nvme-write-zeroes -l namespace-id -s n --description 'Namespace ID use in the command.'

