# nvme-netapp-smdevices
# Autogenerated from man page /usr/share/man/man1/nvme-netapp-smdevices.1.gz
complete -c nvme-netapp-smdevices -s o -l output-format --description 'Set the reporting format to normal (default), column, or json.'

