# nvme-telemetry-log
# Autogenerated from man page /usr/share/man/man1/nvme-telemetry-log.1.gz
complete -c nvme-telemetry-log -s o -l output-file --description 'File name to which raw binary data will be saved to.'
complete -c nvme-telemetry-log -s g -l host-generate --description 'If set to 1, controller shall capture the Telemetry Host-Initiated data repre…'
complete -c nvme-telemetry-log -s d -l data-area --description 'Retrieves the specific data area requested.  Valid inputs are 1,2,3.'

