# nvme-wdc-vs-internal-log
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-vs-internal-log.1.gz
complete -c nvme-wdc-vs-internal-log -s o -l output-file --description 'Output file; defaults to device serial number followed by "internal_fw_log<da…'
complete -c nvme-wdc-vs-internal-log -s s -l transfer-size --description 'Transfer size; defaults to 0x10000 (65536 decimal) bytes.'
complete -c nvme-wdc-vs-internal-log -s d -l data-area --description 'DUI data area to retrieve.'
complete -c nvme-wdc-vs-internal-log -s f -l file-size --description 'Specifies the desired size of the data file starting at the passed in offset.'
complete -c nvme-wdc-vs-internal-log -s e -l offset --description 'Specifies the data offset at which to start retrieving the data.'
complete -c nvme-wdc-vs-internal-log -s t -l type --description 'Specifies the telemetry type - NONE, HOST, or CONTROLLER.'
complete -c nvme-wdc-vs-internal-log -s v -l verbose --description 'Provides additional debug messages for certain drives.'

