# nvme-resv-acquire
# Autogenerated from man page /usr/share/man/man1/nvme-resv-acquire.1.gz
complete -c nvme-resv-acquire -s n -l namespace-id --description 'Override the nsid field.'
complete -c nvme-resv-acquire -s c -l crkey --description 'Current Reservation Key: The field specifies the current reservation key asso…'
complete -c nvme-resv-acquire -s p -l prkey --description 'Preempt Reservation Key: If the Reservation Acquire Action is set to 001b (i.'
complete -c nvme-resv-acquire -s t -l rtyep --description 'Reservation Type: This field specifies the type of reservation to be created.'
complete -c nvme-resv-acquire -s a -l racqa --description 'Reservation Acquire Action: This field specifies the action that is performed…'
complete -c nvme-resv-acquire -s i -l iekey --description 'Ignore Existing Key: If this bit is set to a 1, then the Current Reservation …'

