# nvme-intel-smart-log-add
# Autogenerated from man page /usr/share/man/man1/nvme-intel-smart-log-add.1.gz
complete -c nvme-intel-smart-log-add -s n -l namespace-id --description 'Retrieve the Additional SMART log for the given nsid.'
complete -c nvme-intel-smart-log-add -s b -l raw-binary --description 'Print the raw Intel Additional SMART log buffer to stdout.'
complete -c nvme-intel-smart-log-add -s j -l json --description 'Dump output in json format.'

