# nvme-admin-passthru
# Autogenerated from man page /usr/share/man/man1/nvme-admin-passthru.1.gz
complete -c nvme-admin-passthru -s o -l opcode --description 'The NVMe opcode to send to the device in the command.'
complete -c nvme-admin-passthru -s f -l flags --description 'The NVMe command flags to send to the device in the command.'
complete -c nvme-admin-passthru -s R -l rsvd --description 'The value for the reserved field in the command.'
complete -c nvme-admin-passthru -s n -l namespace-id --description 'The value for the ns-id in the command.'
complete -c nvme-admin-passthru -l 'cdw[2-3' --description 'Specifies the command dword value for that specified entry in the command.'
complete -c nvme-admin-passthru -s r -l read -s w -l write --description 'Used for the data-direction for the command and required for commands sending…'
complete -c nvme-admin-passthru -s i -l input-file --description 'If the command is a data-out (write) command, use this file to fill the buffe…'
complete -c nvme-admin-passthru -s l -l data-len --description 'The data length for the buffer used for this command.'
complete -c nvme-admin-passthru -s m -l metadata-len --description 'The metadata length for the buffer used for this command.'
complete -c nvme-admin-passthru -s s -l show-cmd --description 'Print out the command to be sent.'
complete -c nvme-admin-passthru -s d -l dry-run --description 'Do not actually send the command.'
complete -c nvme-admin-passthru -s b -l raw-binary --description 'Print the raw returned buffer to stdout if the command returns a structure.'
complete -c nvme-admin-passthru -s p -l prefill --description 'Prefill the buffer with a predetermined byte value.  Defaults to 0.'

