# nvme-list-subsys
# Autogenerated from man page /usr/share/man/man1/nvme-list-subsys.1.gz
complete -c nvme-list-subsys -s o -l output-format --description 'Set the reporting format to normal or json.'

