# nvme-list-ns
# Autogenerated from man page /usr/share/man/man1/nvme-list-ns.1.gz
complete -c nvme-list-ns -s n -l namespace-id --description 'Retrieve the identify list structure starting with the given nsid.'
complete -c nvme-list-ns -s a -l all --description 'Retrieve the identify list structure for all namespaces in the subsystem, whe…'

