# nvme-sanitize
# Autogenerated from man page /usr/share/man/man1/nvme-sanitize.1.gz
complete -c nvme-sanitize -s d -l no-delloc --description 'No Deallocate After Sanitize: If set, then the controller shall not deallocat…'
complete -c nvme-sanitize -s i -l oipbp --description 'Overwrite Invert Pattern Between Passes: If set, then the Overwrite Pattern s…'
complete -c nvme-sanitize -s n -l owpass --description 'Overwrite Pass Count: This field specifies the number of overwrite passes (i.'
complete -c nvme-sanitize -s u -l ause --description 'Allow Unrestricted Sanitize Exit: If set, then the sanitize operation is perf…'
complete -c nvme-sanitize -s a -l sanact --description 'Sanitize Action: 000b - Reserved 001b - Exit Failure Mode 010b - Start a Bloc…'
complete -c nvme-sanitize -s p -l ovrpat --description 'Overwrite Pattern: This field is ignored unless the Sanitize Action field in …'

