# nvme-wdc-get-crash-dump
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-get-crash-dump.1.gz
complete -c nvme-wdc-get-crash-dump -s o -l output-file --description 'Output file; defaults to device serial number followed by "crash_dump" suffix.'

