# nvme-list-ctrl
# Autogenerated from man page /usr/share/man/man1/nvme-list-ctrl.1.gz
complete -c nvme-list-ctrl -s c -l cntid --description '.'
complete -c nvme-list-ctrl -s n -l namespace-id --description '.'

