# nvme-wdc-vs-telemetry-controller-option
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-vs-telemetry-controller-option.1.gz
complete -c nvme-wdc-vs-telemetry-controller-option -s d -l disable --description 'Disables the controller initiated option of the telemetry log page.'
complete -c nvme-wdc-vs-telemetry-controller-option -s e -l enable --description 'Enables the controller initiated option of the telemetry log page.'
complete -c nvme-wdc-vs-telemetry-controller-option -s s -l status --description 'Returns the current status (enabled or disabled) of the controller initiated …'

