# nvme-changed-ns-list-log
# Autogenerated from man page /usr/share/man/man1/nvme-changed-ns-list-log.1.gz
complete -c nvme-changed-ns-list-log -s b -l raw-binary --description 'Print the raw Changed Namespace List log buffer to stdout.'
complete -c nvme-changed-ns-list-log -s o -l output-format --description 'Set the reporting format to normal, json, or binary.'

