# nvme-list
# Autogenerated from man page /usr/share/man/man1/nvme-list.1.gz
complete -c nvme-list -s o -l output-format --description 'Set the reporting format to normal or json.'
complete -c nvme-list -s v -l verbose --description 'Increase the information in the output, showing nvme subsystems, controllers …'

