# nvme-write-uncor
# Autogenerated from man page /usr/share/man/man1/nvme-write-uncor.1.gz
complete -c nvme-write-uncor -l start-block -s s --description 'Start block.'
complete -c nvme-write-uncor -l block-count -s c --description 'Number of logical blocks to write uncorrectable.'
complete -c nvme-write-uncor -l namespace-id -s n --description 'Namespace ID use in the command.'

