# nvme-endurance-log
# Autogenerated from man page /usr/share/man/man1/nvme-endurance-log.1.gz
complete -c nvme-endurance-log -s g -l group-id --description 'The endurance group identifier.'
complete -c nvme-endurance-log -s o -l output-format --description 'Set the reporting format to normal, json, or binary.'

