# nvme-attach-ns
# Autogenerated from man page /usr/share/man/man1/nvme-attach-ns.1.gz
complete -c nvme-attach-ns -s n -l namespace-id --description 'The namespace identifier to attach.'
complete -c nvme-attach-ns -s c -o controllers --description 'The comma separated list of controller identifiers to attach the namesapce to…'

