# nvme-wdc-id-ctrl
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-id-ctrl.1.gz
complete -c nvme-wdc-id-ctrl -s b -l raw-binary --description 'Print the raw buffer to stdout.  Structure is not parsed by program.'
complete -c nvme-wdc-id-ctrl -s v -l vendor-specific --description 'In addition to parsing known fields, this option will dump the vendor specifi…'
complete -c nvme-wdc-id-ctrl -s H -l human-readable --description 'This option will parse and format many of the bit fields into human-readable …'
complete -c nvme-wdc-id-ctrl -s o -l output-format --description 'Set the reporting format to normal, json, or binary.'

