# nvme-intel-temp-stats
# Autogenerated from man page /usr/share/man/man1/nvme-intel-temp-stats.1.gz
complete -c nvme-intel-temp-stats -s b -l raw-binary --description 'Print the raw temperature stats log buffer to stdout.'

