# nvme-set-property
# Autogenerated from man page /usr/share/man/man1/nvme-set-property.1.gz
complete -c nvme-set-property -s o -l offset --description 'The offset of the property.'
complete -c nvme-set-property -s v --description '--value: The value of the property to be set.'
complete -c nvme-set-property -l value --description '.'

