# nvme-sanitize-log
# Autogenerated from man page /usr/share/man/man1/nvme-sanitize-log.1.gz
complete -c nvme-sanitize-log -s o -l output-format --description 'Set the reporting format to normal, json, or binary.'
complete -c nvme-sanitize-log -s H -l human-readable --description 'This option will parse and format many of the bit fields into human-readable …'
complete -c nvme-sanitize-log -s b -l raw-binary --description 'Print the raw buffer to stdout.  Structure is not parsed by program.'

