# nvme-wdc-vs-nand-stats
# Autogenerated from man page /usr/share/man/man1/nvme-wdc-vs-nand-stats.1.gz
complete -c nvme-wdc-vs-nand-stats -s o -l output-format --description 'Set the reporting format to normal, or json.'

