# nvme-fw-download
# Autogenerated from man page /usr/share/man/man1/nvme-fw-download.1.gz
complete -c nvme-fw-download -s f -l fw --description 'Required argument.'
complete -c nvme-fw-download -s x -l xfer --description 'This specifies the size to split each transfer.'
complete -c nvme-fw-download -s o -l offset --description 'This specifies the starting offset in dwords.'

