# nvme-fw-log
# Autogenerated from man page /usr/share/man/man1/nvme-fw-log.1.gz
complete -c nvme-fw-log -s b -l raw-binary --description 'Print the raw fw log buffer to stdout.'
complete -c nvme-fw-log -s o -l output-format --description 'Set the reporting format to normal, json, or binary.'

