# nvme-security-send
# Autogenerated from man page /usr/share/man/man1/nvme-security-send.1.gz
complete -c nvme-security-send -s n -l namespace-id --description 'Target a specific namespace for this security command.'
complete -c nvme-security-send -s N -l nssf --description 'NVMe Security Specific field.'
complete -c nvme-security-send -s f -l file --description 'Path to file used as the security protocol\\(cqs payload.  Required argument.'
complete -c nvme-security-send -s p -l secp --description 'Security Protocol: This field specifies the security protocol as defined in S…'
complete -c nvme-security-send -s s -l spsp --description 'SP Specific: The value of this field is specific to the Security Protocol as …'
complete -c nvme-security-send -s t -l tl --description 'Transfer Length: The value of this field is specific to the Security Protocol…'

