# nvme-disconnect
# Autogenerated from man page /usr/share/man/man1/nvme-disconnect.1.gz
complete -c nvme-disconnect -s n -l nqn --description 'Indicates that all controllers for the NVMe subsystems specified should be re…'
complete -c nvme-disconnect -s d -l device --description 'Indicates that the controller with the specified name should be removed.'

