# nvme-create-ns
# Autogenerated from man page /usr/share/man/man1/nvme-create-ns.1.gz
complete -c nvme-create-ns -s s -l nsze --description '.'
complete -c nvme-create-ns -s c -l ncap --description '.'
complete -c nvme-create-ns -s f -l flbas --description '.'
complete -c nvme-create-ns -s d -l dps --description '.'
complete -c nvme-create-ns -s m -l nmic --description '.'
complete -c nvme-create-ns -s a -l anagrp-id --description '.'
complete -c nvme-create-ns -s i -l nvmset-id --description '.'
complete -c nvme-create-ns -s b -l block-size --description '.'

