# nvme-resv-release
# Autogenerated from man page /usr/share/man/man1/nvme-resv-release.1.gz
complete -c nvme-resv-release -s n -l namespace-id --description 'Override the nsid field.'
complete -c nvme-resv-release -s c -l crkey --description 'Current Reservation Key: If the Reservation Register Action is 001b (i. e.'
complete -c nvme-resv-release -s t -l rtyep --description 'Reservation Type: This field specifies the type of reservation to be created.'
complete -c nvme-resv-release -s a -l rrela --description 'Reservation Release Action: This field specifies the registration action that…'
complete -c nvme-resv-release -s i -l iekey --description 'Ignore Existing Key: If this bit is set to a 1, then the Current Reservation …'

