# odbc_config
# Autogenerated from man page /usr/share/man/man1/odbc_config.1.gz
complete -c odbc_config -l prefix --description 'Prefix for architecture-independent file tree.'
complete -c odbc_config -l exec-prefix --description 'Prefix for architecture-dependent file tree.'
complete -c odbc_config -l include-prefix --description 'Directory with C header files for unixODBC.'
complete -c odbc_config -l lib-prefix --description 'Directory with object code (. so) libraries.'
complete -c odbc_config -l bin-prefix --description 'Location of user executables.'
complete -c odbc_config -l version --description 'unixODBC version.'
complete -c odbc_config -l libs --description 'Compiler flags for linking dynamic libraries.'
complete -c odbc_config -l static-libs --description 'Absolute file name of static unixODBC library.'
complete -c odbc_config -l libtool-libs --description 'Absolute file name of libtool unixODBC library.'
complete -c odbc_config -l cflags --description 'Compiler flags to find include files and critical compiler flags and defines …'
complete -c odbc_config -l odbcversion --description 'Version of the ODBC specification used by the unixODBC.'
complete -c odbc_config -l odbcini --description 'Absolute file name of the system-wide DSN configuration file R odbc. ini .'
complete -c odbc_config -l odbcinstini --description 'Absolute file name of the driver configuration file R odbcinst. ini .'
complete -c odbc_config -l header --description 'Definitions of used C preprocessor constants.'
complete -c odbc_config -l ulen --description 'Compiler flag for defining SIZEOF_SQLULEN .'

