# ogginfo
# Autogenerated from man page /usr/share/man/man1/ogginfo.1.gz
complete -c ogginfo -s h --description 'Show a help and usage message.'
complete -c ogginfo -s q --description 'Quiet mode.  This may be specified multiple times.'
complete -c ogginfo -s v --description 'Verbose mode.  At the current time, this does not do anything.'

