# openipmish
# Autogenerated from man page /usr/share/man/man1/openipmish.1.gz
complete -c openipmish -l dmsg --description 'Turn on message debugging, this will dump all messages to debug log output.'
complete -c openipmish -l drawmsg --description 'Turn on raw message debugging, this will dump all low-level messages to debug…'
complete -c openipmish -l dmem --description 'Turn on memory debugging, this will cause memory allocation and deallocations…'
complete -c openipmish -l dlock --description 'Turn on lock debugging, this will check lock operations to make sure that loc…'
complete -c openipmish -l snmp --description 'Enable the SNMP trap handler.'
complete -c openipmish -l help --description 'Help output.'

