# openssl-list
# Autogenerated from man page /usr/share/man/man1/openssl-list.1ssl.gz
complete -c openssl-list -o help --description 'Display a usage message.'
complete -c openssl-list -s 1 --description 'List the commands, digest-commands, or cipher-commands in a single column.'
complete -c openssl-list -o commands --description 'Display a list of standard commands.'
complete -c openssl-list -o digest-commands --description 'Display a list of message digest commands, which are typically used as input …'
complete -c openssl-list -o digest-algorithms --description 'Display a list of message digest algorithms.'
complete -c openssl-list -o cipher-commands --description 'Display a list of cipher commands, which are typically used as input to the d…'
complete -c openssl-list -o cipher-algorithms --description 'Display a list of cipher algorithms.'
complete -c openssl-list -o public-key-algorithms --description 'Display a list of public key algorithms, with each algorithm as a block of mu…'
complete -c openssl-list -o public-key-methods --description 'Display a list of public key method OIDs: this also includes public key metho…'

