# openssl-crl
# Autogenerated from man page /usr/share/man/man1/openssl-crl.1ssl.gz
complete -c openssl-crl -o help --description 'Print out a usage message.'
complete -c openssl-crl -o inform --description 'This specifies the input format.'
complete -c openssl-crl -o outform --description 'This specifies the output format, the options have the same meaning and defau…'
complete -c openssl-crl -o in --description 'This specifies the input filename to read from or standard input if this opti…'
complete -c openssl-crl -o out --description 'Specifies the output filename to write to or standard output by default.'
complete -c openssl-crl -o text --description 'Print out the \\s-1CRL\\s0 in text form.'
complete -c openssl-crl -o nameopt --description 'Option which determines how the subject or issuer names are displayed.'
complete -c openssl-crl -o noout --description 'Don\'t output the encoded version of the \\s-1CRL. \\s0.'
complete -c openssl-crl -o hash --description 'Output a hash of the issuer name.'
complete -c openssl-crl -o hash_old --description 'Outputs the \\*(L"hash\\*(R" of the \\s-1CRL\\s0 issuer name using the older algo…'
complete -c openssl-crl -o issuer --description 'Output the issuer name.'
complete -c openssl-crl -o lastupdate --description 'Output the lastUpdate field.'
complete -c openssl-crl -o nextupdate --description 'Output the nextUpdate field.'
complete -c openssl-crl -o CAfile --description 'Verify the signature on a \\s-1CRL\\s0 by looking up the issuing certificate in…'

