# openssl-rand
# Autogenerated from man page /usr/share/man/man1/openssl-rand.1ssl.gz
complete -c openssl-rand -o help --description 'Print out a usage message.'
complete -c openssl-rand -o out --description 'Write to file instead of standard output.'
complete -c openssl-rand -o rand --description 'A file or files containing random data used to seed the random number generat…'
complete -c openssl-rand -o writerand --description 'Writes random data to the specified file upon exit.'
complete -c openssl-rand -o base64 --description 'Perform base64 encoding on the output.'

