# openssl-ec
# Autogenerated from man page /usr/share/man/man1/openssl-ec.1ssl.gz
complete -c openssl-ec -o help --description 'Print out a usage message.'
complete -c openssl-ec -o inform --description 'This specifies the input format.'
complete -c openssl-ec -o outform --description 'This specifies the output format, the options have the same meaning and defau…'
complete -c openssl-ec -o in --description 'This specifies the input filename to read a key from or standard input if thi…'
complete -c openssl-ec -o passin --description 'The input file password source.'
complete -c openssl-ec -o out --description 'This specifies the output filename to write a key to or standard output by is…'
complete -c openssl-ec -o passout --description 'The output file password source.'
complete -c openssl-ec -o des -o des3 -o idea --description 'These options encrypt the private key with the \\s-1DES,\\s0 triple \\s-1DES, ID…'
complete -c openssl-ec -o text --description 'Prints out the public, private key components and parameters.'
complete -c openssl-ec -o noout --description 'This option prevents output of the encoded version of the key.'
complete -c openssl-ec -o pubin --description 'By default, a private key is read from the input file.'
complete -c openssl-ec -o pubout --description 'By default a private key is output.'
complete -c openssl-ec -o conv_form --description 'This specifies how the points on the elliptic curve are converted into octet …'
complete -c openssl-ec -o param_enc --description 'This specifies how the elliptic curve parameters are encoded.'
complete -c openssl-ec -o no_public --description 'This option omits the public key components from the private key output.'
complete -c openssl-ec -o check --description 'This option checks the consistency of an \\s-1EC\\s0 private or public key.'

