# openipmi_eventd
# Autogenerated from man page /usr/share/man/man1/openipmi_eventd.1.gz
complete -c openipmi_eventd -s f -l outfile --description 'Send all events to the given file.'
complete -c openipmi_eventd -s k -l exec-now --description 'Immediately spawn the given program and send the event information to that pr…'
complete -c openipmi_eventd -s i -l event-stdin --description 'Send the event information to the program\'s standard input instead of the com…'
complete -c openipmi_eventd -s e -l delete-events --description 'Delete events from the SEL (System Event Log) once they have been processed.'
complete -c openipmi_eventd -s b -l dont-daemonize --description 'Do not daemonize the program, run it as a foreground process.'
complete -c openipmi_eventd -s d -l debug --description 'Debug the program, turn on output, send all logs to stderr, and do not run th…'

