# ostree-ls
# Autogenerated from man page /usr/share/man/man1/ostree-ls.1.gz
complete -c ostree-ls -l dironly -s d --description 'Do not recurse into directory arguments.'
complete -c ostree-ls -l recursive -s R --description 'Print directories recursively.'
complete -c ostree-ls -l checksum -s C --description 'Print checksum.'
complete -c ostree-ls -l xattrs -s X --description 'Print extended attributes.'
complete -c ostree-ls -l nul-filenames-only --description 'Print only filenames, NUL separated.'

