# ostree-admin-config-diff
# Autogenerated from man page /usr/share/man/man1/ostree-admin-config-diff.1.gz
complete -c ostree-admin-config-diff -l os --description 'Use a different operating system stateroot than the current one.'

