# ostree-admin-deploy
# Autogenerated from man page /usr/share/man/man1/ostree-admin-deploy.1.gz
complete -c ostree-admin-deploy -l os --description 'Use a different operating system root than the current one.'
complete -c ostree-admin-deploy -l origin-file --description 'Use FILENAME as the origin, which is where OSTree will look for updated versi…'
complete -c ostree-admin-deploy -l retain --description 'Do not delete previous deployment.'
complete -c ostree-admin-deploy -l retain-pending --description 'Do not delete pending deployments.'
complete -c ostree-admin-deploy -l retain-rollback --description 'Do not delete rollback deployments.'
complete -c ostree-admin-deploy -l not-as-default --description 'Append rather than prepend new deployment.'
complete -c ostree-admin-deploy -l karg-proc-cmdline --description 'Import current /proc/cmdline.'
complete -c ostree-admin-deploy -l karg --description 'Set kernel argument, like root=/dev/sda1; this overrides any earlier argument…'
complete -c ostree-admin-deploy -l karg-append --description 'Append kernel argument; useful with e. g.'

