# ostree-remote
# Autogenerated from man page /usr/share/man/man1/ostree-remote.1.gz
complete -c ostree-remote -l keyring --description 'nor.'
complete -c ostree-remote -l stdin --description 'options are given, then keys are imported from the users personal GPG keyring.'
complete -c ostree-remote -l set --description '.'
complete -c ostree-remote -l if-not-exists --description '.'
complete -c ostree-remote -l force --description '.'
complete -c ostree-remote -l no-gpg-verify --description '.'
complete -c ostree-remote -l gpg-import --description '.'
complete -c ostree-remote -l collection-id --description '.'
complete -c ostree-remote -s u -l show-urls --description '.'
complete -c ostree-remote -s k --description '.'
complete -c ostree-remote -l raw --description '.'

