# ostree-pull
# Autogenerated from man page /usr/share/man/man1/ostree-pull.1.gz
complete -c ostree-pull -l commit-metadata-only --description 'Fetch only the commit metadata.'
complete -c ostree-pull -l disable-fsync --description 'Do no invoke fsync().'
complete -c ostree-pull -l localcache-repo --description 'Like git\\*(Aqs clone --reference.'
complete -c ostree-pull -l untrusted --description 'Do not trust local sources, verify checksums and don\\*(Aqt hardlink into sour…'
complete -c ostree-pull -l disable-static-deltas --description 'Do not use static deltas.'
complete -c ostree-pull -l mirror --description 'Write refs suitable for a mirror, i. e.'
complete -c ostree-pull -l subpath --description 'Only pull the provided subpath.'
complete -c ostree-pull -l depth --description 'Traverse DEPTH parents (-1=infinite) (default: 0).'
complete -c ostree-pull -l network-retries --description 'Specifies how many times each download should be retried upon error (default:…'

