# ostree-admin-unlock
# Autogenerated from man page /usr/share/man/man1/ostree-admin-unlock.1.gz
complete -c ostree-admin-unlock -l hotfix --description 'If this option is provided, the current deployment will be cloned as a rollba…'

