# ostree-admin-set-origin
# Autogenerated from man page /usr/share/man/man1/ostree-admin-set-origin.1.gz
complete -c ostree-admin-set-origin -l set --description 'Set an option for the remote.'
complete -c ostree-admin-set-origin -l index --description 'Change the origin of the deployment numbered INDEX (starting from 0).'

