# ostree-checkout
# Autogenerated from man page /usr/share/man/man1/ostree-checkout.1.gz
complete -c ostree-checkout -l user-mode -s u --description 'Do not change file ownership or initialize extended attributes.'
complete -c ostree-checkout -l subpath --description 'Checkout sub-directory PATH.'
complete -c ostree-checkout -l union --description 'Keep existing directories and unchanged files, overwrite existing files.'
complete -c ostree-checkout -l union-add --description 'Keep existing directories and files.'
complete -c ostree-checkout -l union-identical --description 'Like --union, but error out if a file would be replaced with a different file.'
complete -c ostree-checkout -l allow-noent --description 'Do nothing if specified path does not exist.'
complete -c ostree-checkout -l from-stdin --description 'Process many checkouts from standard input.'
complete -c ostree-checkout -l from-file --description 'Process many checkouts from input file.'
complete -c ostree-checkout -s H --description '.'

