# ostree-diff
# Autogenerated from man page /usr/share/man/man1/ostree-diff.1.gz
complete -c ostree-diff -l stats --description 'Print various statistics.'
complete -c ostree-diff -l fs-diff --description 'Print filesystem diff.'
complete -c ostree-diff -l owner-uid --description 'Use file ownership user id for local files.'
complete -c ostree-diff -l owner-gid --description 'Use file ownership group id for local files.'

