# ostree-refs
# Autogenerated from man page /usr/share/man/man1/ostree-refs.1.gz
complete -c ostree-refs -l list --description 'For historical reasons, refs without this option will strip the specified pre…'
complete -c ostree-refs -l create --description 'Create a ref pointing to the commit EXISTING.'
complete -c ostree-refs -l delete --description 'Delete refs which match PREFIX, rather than listing them.'
complete -c ostree-refs -l alias -s A --description 'If used with --create, create an alias.  Otherwise just list aliases.'
complete -c ostree-refs -l collections -s c --description 'Enable interactions with refs using the combination of their collection IDs a…'
complete -c ostree-refs -l force --description 'When creating NEWREF with --create, allow an existing ref to be updated inste…'

