# pacman
# Autogenerated from man page /usr/share/man/man6/pacman.6x.gz
complete -c pacman -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c pacman -o root --description 'Draw on the root window.'
complete -c pacman -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c pacman -o install --description 'Install a private colormap for the window.'
complete -c pacman -o visual --description 'Specify which visual to use.'
complete -c pacman -o ncolors --description 'How many colors should be used (if possible).   Default 6.'
complete -c pacman -o size --description 'How big to make Pac-Man and the ghosts.   0 means "default. ".'
complete -c pacman -o fps --description 'Display the current frame rate and CPU load.'

