# palmtopnm
# Autogenerated from man page /usr/share/man/man1/palmtopnm.1.gz
complete -c palmtopnm -o verbose --description 'Display various interesting information about the input file and process.'
complete -c palmtopnm -o transparent --description 'If the Palm Bitmap has a transparent color set,  palmtopnm writes the value f…'
complete -c palmtopnm -o rendition --description 'Palm Bitmaps may contain several different renditions of the same image, with…'
complete -c palmtopnm -o showhist --description 'This option causes palmtopnm to  write a histogram of colors in the input fil…'

