# pamarith
# Autogenerated from man page /usr/share/man/man1/pamarith.1.gz
complete -c pamarith -o divide --description '.'
complete -c pamarith -o difference -o minimum -o maximum -o mean --description 'and -compare.'
complete -c pamarith -o compare --description '(Before Netpbm 10. 14 (February 2003), there was no exception for.'
complete -c pamarith -o 'compare;' --description 'was at least 2, and sometime between 10. 18 and 10.'
complete -c pamarith -o nand -o nor -o xor -o shiftleft --description '.'
complete -c pamarith -o shiftright --description '.'
complete -c pamarith -o subtract --description 'value in the left input image.'
complete -c pamarith -o multiply --description 'tends to produce nonobvious results because of the way pamarith interprets sa…'
complete -c pamarith -o and -o or --description 'consider the input and output images to contain bit strings; they compute bit…'

