# pambackground
# Autogenerated from man page /usr/share/man/man1/pambackground.1.gz
complete -c pambackground -o verbose --description 'Tell interesting facts about the process.  EXAMPLES     $ pambackground test.'

