# pamcomp
# Autogenerated from man page /usr/share/man/man1/pamcomp.1.gz
complete -c pamcomp -o align --description 'This option selects the basic horizontal position of the overlay image with r…'
complete -c pamcomp -o valign --description 'This option selects the basic vertical position of the overlay image with res…'
complete -c pamcomp -o xoff --description 'This option modifies the horizontal positioning of the overlay image with res…'
complete -c pamcomp -o yoff --description 'This option modifies the vertical positioning of the overlay image with respe…'
complete -c pamcomp -o alpha --description 'This option names a file that contains the transparency mask.'
complete -c pamcomp -o invert --description 'This option inverts the sense of the values in the transparency mask, which  …'
complete -c pamcomp -o opacity --description 'This option tells how opaque the overlay image is to be, i. e.'
complete -c pamcomp -o mixtransparency --description 'This option controls what pamcomp does where both the underlying and overlay …'
complete -c pamcomp -o linear --description 'This option indicates that the inputs are not true Netpbm images but rather a…'

