# pamcut
# Autogenerated from man page /usr/share/man/man1/pamcut.1.gz
complete -c pamcut -o left --description 'The column number of the leftmost column to be in the output.'
complete -c pamcut -o right --description 'The column number of the rightmost column to be in the output, numbered the s…'
complete -c pamcut -o top --description 'The row number of the topmost row to be in the output.'
complete -c pamcut -o bottom --description 'The row number of the bottom-most row to be in the output, numbered the same …'
complete -c pamcut -o width --description 'The number of columns to be in the output.   Must be positive.'
complete -c pamcut -o height --description 'The number of rows to be in the output.   Must be positive.'
complete -c pamcut -o pad --description 'If the rectangle you specify is not entirely within the input image, pamcut f…'
complete -c pamcut -o verbose --description 'Print information about the processing to Standard Error.'

