# pamdice
# Autogenerated from man page /usr/share/man/man1/pamdice.1.gz
complete -c pamdice -o outstem --description 'This option determines the names of the output files.'
complete -c pamdice -o width --description 'gives the width in pixels of the output images.'
complete -c pamdice -o height --description 'gives the height in pixels of the output images.'
complete -c pamdice -o hoverlap --description 'gives the horizontal overlap in pixels between output images.'
complete -c pamdice -o voverlap --description 'gives the vertical overlap in pixels between output images.'
complete -c pamdice -o verbose --description 'Print information about the processing to Standard Error.  HISTORY.'

