# pamditherbw
# Autogenerated from man page /usr/share/man/man1/pamditherbw.1.gz
complete -c pamditherbw -o value --description 'This option alters the thresholding value for Floyd-Steinberg, Atkinson, and …'
complete -c pamditherbw -o clump --description 'This option alters the number of pixels in a clump.'
complete -c pamditherbw -o randomseed --description 'This is the seed for the random number generator that generates the pixels.'
complete -c pamditherbw -o atkinson --description 'AUTHOR.'

