# pamfile
# Autogenerated from man page /usr/share/man/man1/pamfile.1.gz
complete -c pamfile -o allimages --description 'This option causes pamfile to describe every image in each input file.'
complete -c pamfile -o comments --description 'This option causes pamfile to include for each PAM image a report of the comm…'
complete -c pamfile -o count --description 'This option causes pamfile to display only a count of how many images are in …'

