# pamfunc
# Autogenerated from man page /usr/share/man/man1/pamfunc.1.gz
complete -c pamfunc -o multiplier --description 'sp This option makes the transfer function that of multiplying by      realnu…'
complete -c pamfunc -o divisor --description 'sp This option makes the transfer function that of dividing by      realnum.'
complete -c pamfunc -o adder --description 'sp This option makes the transfer function that of adding      integer/maxval.'
complete -c pamfunc -o subtractor --description 'sp This option makes the transfer function that of subtracting      integer/m…'
complete -c pamfunc -o min --description 'sp This option makes the transfer function that of taking the maximum of     …'
complete -c pamfunc -o max --description 'sp This option makes the transfer function that of taking the minimum of     …'
complete -c pamfunc -o andmask --description 'sp This option makes the transfer function that of bitwise anding      with h…'
complete -c pamfunc -o ormask --description 'sp This option makes the transfer function that of bitwise      inclusive ori…'
complete -c pamfunc -o xormask --description 'sp This option makes the transfer function that of bitwise      exclusive ori…'
complete -c pamfunc -o not --description 'sp This option makes the transfer function that of bitwise logical      inver…'
complete -c pamfunc -o shiftleft --description 'sp This option makes the transfer function that of bitwise shifting      left…'
complete -c pamfunc -o shiftright --description 'sp This option makes the transfer function that of bitwise shifting      righ…'
complete -c pamfunc -o changemaxval --description '.'

