# pamrubber
# Autogenerated from man page /usr/share/man/man1/pamrubber.1.gz
complete -c pamrubber -o tri -o quad --description 'sp This selects the type of rubber sheeting done.'
complete -c pamrubber -o linear --description 'sp This determines whether pamrubber uses nearest neighbor interpolation or b…'
complete -c pamrubber -o frame --description 'sp This option causes pamrubber to overlay the target image with the edges of…'
complete -c pamrubber -o randomseed --description '.'

