# pamstretch
# Autogenerated from man page /usr/share/man/man1/pamstretch.1.gz
complete -c pamstretch -o xscale --description 'This is the horizontal scale factor.'
complete -c pamstretch -o yscale --description 'This is the vertical scale factor.'
complete -c pamstretch -o blackedge --description 'interpolate to black at right/bottom edges.'
complete -c pamstretch -o dropedge --description 'drop one (source) pixel at right/bottom edges.'

