# pamslice
# Autogenerated from man page /usr/share/man/man1/pamslice.1.gz
complete -c pamslice -o row --description 'This indicates that the slice is to be horizontal -- i. e.'
complete -c pamslice -o column --description 'This indicates that the slice is to be vertical -- i. e.'
complete -c pamslice -o plane --description 'This specifies that you are interested in only one plane of the image      an…'
complete -c pamslice -o xmgr --description '     This option causes pamslice to format the output as input for a      xmg…'

