# pamtilt
# Autogenerated from man page /usr/share/man/man1/pamtilt.1.gz
complete -c pamtilt -o angle --description 'Assume a maximum tilt angle of maxangle (measured in degrees).'
complete -c pamtilt -o fast --description 'Skip the third iteration for speed at the expense of accuracy.'
complete -c pamtilt -o verbose --description 'Show on Standard Error the measurements computed at each tested angle.'
complete -c pamtilt -o quality --description 'Require a signal-to-noise ratio of a least q on the first iteration to report…'
complete -c pamtilt -o hstep --description 'Set the horizontal increment to check every nth column.'
complete -c pamtilt -o vstep --description 'Set the vertical increment to check every nth row.'
complete -c pamtilt -o dstep --description 'Set the vertical distance used when checking pixels in a column.'
complete -c pamtilt -o astep --description 'Set the angle increment of the first iteration, in degrees.'

