# pamtowinicon
# Autogenerated from man page /usr/share/man/man1/pamtowinicon.1.gz
complete -c pamtowinicon -o pngthreshold --description 'pamtowinicon encodes images with resolutions above or equal threshold by thre…'
complete -c pamtowinicon -o truetransparent --description 'Make all pixels outside the opaque area black, avoiding inversion and other e…'
complete -c pamtowinicon -o verbose --description 'Print more messages IMAGES.'

