# pamtodjvurle
# Autogenerated from man page /usr/share/man/man1/pamtodjvurle.1.gz
complete -c pamtodjvurle -o transparent --description 'This option indicates which color in the image should be considered transpare…'

