# pamtohtmltbl
# Autogenerated from man page /usr/share/man/man1/pamtohtmltbl.1.gz
complete -c pamtohtmltbl -o transparent --description 'This option indicates that pixels of the specified color are to be transparen…'
complete -c pamtohtmltbl -o verbose --description 'This option causes pamtohtmltbl to display messages about the conversion proc…'

