# pamtojpeg2k
# Autogenerated from man page /usr/share/man/man1/pamtojpeg2k.1.gz
complete -c pamtojpeg2k -o compression --description 'ratio is a floating point number that specifies the compression ratio.'
complete -c pamtojpeg2k -o verbose --description 'This option causes pamtojpeg2k to issue informational messages about the conv…'
complete -c pamtojpeg2k -o debuglevel --description 'This option controls debug messages from the Jasper library.'

