# pamtogif
# Autogenerated from man page /usr/share/man/man1/pamtogif.1.gz
complete -c pamtogif -o interlace --description 'Produce an interlaced GIF file.'
complete -c pamtogif -o sort --description 'Produce a GIF file with a color map sorted in a predictable order.'
complete -c pamtogif -o mapfile --description 'sp Use the colors found in the file mapfile to create the colormap in the GIF…'
complete -c pamtogif -o transparent --description 'pamtogif marks the specified color as transparent in the GIF image.'
complete -c pamtogif -o alpha --description 'There is no -alpha option.'
complete -c pamtogif -o alphacolor --description 'This specifies the foreground color for transparent pixels.'
complete -c pamtogif -o comment --description 'Include a comment in the GIF output with comment text text.'
complete -c pamtogif -o nolzw --description 'sp This option is mainly of historical interest -- it involves use of a paten…'
complete -c pamtogif -o aspect --description 'This is the aspect ratio of the pixels of the image.'
complete -c pamtogif -o verbose --description 'This option causes pamtogif to display information about the conversion proce…'

