# pamtopnm
# Autogenerated from man page /usr/share/man/man1/pamtopnm.1.gz
complete -c pamtopnm -o assume --description '.'
complete -c pamtopnm -o ass --description 'SEE ALSO pbmtopgm (1)c , pamditherbw (1)c , pgmtoppm (1)c , ppmtopgm (1)c , p…'

