# pamtotiff
# Autogenerated from man page /usr/share/man/man1/pamtotiff.1.gz
complete -c pamtotiff -o append --description 'file is empty.'
complete -c pamtotiff -o g4 -o flate -o adobeflate --description 'override the default and set the compression scheme used in creating the outp…'
complete -c pamtotiff -o lsb2msb --description 'order used in creating the file.'
complete -c pamtotiff -o fill --description 'shall be zero-filled to a byte boundary.'
complete -c pamtotiff -o 2d -o g3 --description 'Fill Order.'
complete -c pamtotiff -o color --description 'opposed to grayscale, TIFF image if the input is PPM, even if it contains onl…'
complete -c pamtotiff -o truecolor --description 'form of TIFF output if it is producing a color TIFF image.'
complete -c pamtotiff -o miniswhite -o minisblack --description 'invalid TIFF images that have the indicated photometric but red, green, and b…'
complete -c pamtotiff -o indexbits --description 'bit widths you allow.'
complete -c pamtotiff -o tag --description 'Output.'
complete -c pamtotiff -o output --description 'pamtotiff writes to Standard Output.'
complete -c pamtotiff -o yresolution -o resolutionunit --description 'default is inches.'

