# pamtofits
# Autogenerated from man page /usr/share/man/man1/pamtofits.1.gz
complete -c pamtofits -o min -o max --description 'values" zero and maxval sample values, respectively, in the input image repre…'

