# pamunlookup
# Autogenerated from man page /usr/share/man/man1/pamunlookup.1.gz
complete -c pamunlookup -o lookupfile --description 'lookupfile names the file that contains the PAM or PNM image that is the look…'

