# pamundice
# Autogenerated from man page /usr/share/man/man1/pamundice.1.gz
complete -c pamundice -o across --description 'This is the number of tiles across in the grid, i. e.'
complete -c pamundice -o down --description 'This is the number of tiles up and down in the grid, i. e.'
complete -c pamundice -o hoverlap --description 'This is the amount in pixels to overlap the tiles horizontally.'
complete -c pamundice -o voverlap --description 'This is analogous to -hoverlap, but pamundice clips the bottom edge of each i…'
complete -c pamundice -o verbose --description 'Print information about the processing to Standard Error.  HISTORY.'

