# partprobe
# Autogenerated from man page /usr/share/man/man8/partprobe.8.gz
complete -c partprobe -s d -l dry-run --description 'Don\'t update the kernel.'
complete -c partprobe -s s -l summary --description 'Show a summary of devices and their partitions.'
complete -c partprobe -s h -l help --description 'Show summary of options.'
complete -c partprobe -s v -l version --description 'Show version of program.  REPORTING BUGS Report bugs to <bug-parted@gnu.'

