# pbmclean
# Autogenerated from man page /usr/share/man/man1/pbmclean.1.gz
complete -c pbmclean -o white --description 'Flip pixels of the specified color.'
complete -c pbmclean -o minneighbors --description 'This determines how many pixels must be in a cluster in order for pbmclean to…'
complete -c pbmclean -o black --description '.'
complete -c pbmclean -o minneighbor --description '.'
complete -c pbmclean -o extended --description 'pbmclean uses extended, as opposed to basic, isolated pixel detection.'

