# pbmtoxbm
# Autogenerated from man page /usr/share/man/man1/pbmtoxbm.1.gz
complete -c pbmtoxbm -o x10 --description 'This option causes pbmtoxbm to generate the X10 version of XBM.'
complete -c pbmtoxbm -o x11 --description 'This option causes pbmtoxbm to generate the X11 version of XBM.'

