# pbmtomda
# Autogenerated from man page /usr/share/man/man1/pbmtomda.1.gz
complete -c pbmtomda -s d --description 'Halve the height of the output file, to compensate for the aspect  ratio used…'
complete -c pbmtomda -s i --description 'Invert the colors used.'

