# pbmtoascii
# Autogenerated from man page /usr/share/man/man1/pbmtoascii.1.gz
complete -c pbmtoascii -o 2x4 --description 'the 1x2 mode you can see the individual pixels, so it\'s useful for previewing…'

