# pbmtomacp
# Autogenerated from man page /usr/share/man/man1/pbmtomacp.1.gz
complete -c pbmtomacp -o norle --description 'This option tells pbmtomacp not to use any run length encoding compression in…'
complete -c pbmtomacp -o left --description '.'
complete -c pbmtomacp -o right --description '.'
complete -c pbmtomacp -o top --description '.'
complete -c pbmtomacp -o bottom --description 'These options let you define a rectangle within the image to convert.'

