# pbmtoescp2
# Autogenerated from man page /usr/share/man/man1/pbmtoescp2.1.gz
complete -c pbmtoescp2 -o compress --description 'This determines the compression mode that pbmtoescp2 uses in its output.'
complete -c pbmtoescp2 -o resolution --description 'This determines the horizontal and the vertical print resolution set in the p…'
complete -c pbmtoescp2 -o stripeheight --description 'This option controls the height in lines of the stripes in the output.'
complete -c pbmtoescp2 -o formfeed --description 'This option causes pbmtoescp2 to place a formfeed command at the end of the o…'
complete -c pbmtoescp2 -o raw --description 'This option causes pbmtoescp2 to generate only the data blocks.'

