# pbmtext
# Autogenerated from man page /usr/share/man/man1/pbmtext.1.gz
complete -c pbmtext -o builtin --description '-builtin selects a font among those built into Netpbm.'
complete -c pbmtext -o space --description 'Add pixels pixels of space between characters.'
complete -c pbmtext -o lspace --description 'Add pixels pixels of space between lines.'
complete -c pbmtext -o nomargins --description 'By default, pbmtext adds margins all around the image as described above.'
complete -c pbmtext -o font --description '.'
complete -c pbmtext -o width --description 'This specifies how much horizontal space the text is supposed to fit into.'
complete -c pbmtext -o invert --description '.'

