# pbuildid
# Autogenerated from man page /usr/share/man/man1/pbuildid.1.gz
complete -c pbuildid -l kernel --description 'Print the build id of the running kernel.'
complete -c pbuildid -l vdso --description 'Also print the build id of the vDSO mapped by the kernel (in core file).'
complete -c pbuildid -l help --description 'Usage information.'
complete -c pbuildid -l debug --description 'Print debug information about what pbuildid is doing.'

