# pcsc-spy
# Autogenerated from man page /usr/share/man/man1/pcsc-spy.1.gz
complete -c pcsc-spy -s d -l diffable --description 'Remove the variable parts (like handler values) from the output so that two e…'
complete -c pcsc-spy -s h -l help --description 'Display a short help text.'
complete -c pcsc-spy -s n -l nocolor --description 'Disable the output colorization (if you want redirect the output in a file fo…'

