# pcxtoppm
# Autogenerated from man page /usr/share/man/man1/pcxtoppm.1.gz
complete -c pcxtoppm -o stdpalette --description 'This option causes pcxtoppm to use its predefined standard  palette even if t…'

