# pdfsig
# Autogenerated from man page /usr/share/man/man1/pdfsig.1.gz
complete -c pdfsig -o nssdir --description 'Specify the database directory containing the certificate and key database fi…'
complete -c pdfsig -o nocert --description 'Do not validate the certificate.'
complete -c pdfsig -o dump --description 'Dump all signatures into current directory.'
complete -c pdfsig -o nick --description 'Use the certificate with the given nickname for signing.'
complete -c pdfsig -o kpw --description 'Use the given password for the signing key (this might be missing if the key …'
complete -c pdfsig -o digest --description 'Use the given digest algorithm for signing (default: SHA256).'
complete -c pdfsig -o reason --description 'Set the given reason string for the signature (default: no reason set).'
complete -c pdfsig -o etsi --description 'Create a signature of type ETSI. CAdES. detached instead of adbe. pkcs7.'
complete -c pdfsig -s v --description 'Print copyright and version information.'
complete -c pdfsig -o sign --description 'Sign the document in the signature field with the given number.'
complete -c pdfsig -s h --description 'Print usage information.  ( -help and.'
complete -c pdfsig -l help --description 'are equivalent.'

