# pgmabel
# Autogenerated from man page /usr/share/man/man1/pgmabel.1.gz
complete -c pgmabel -o help --description 'Prints a help message.'
complete -c pgmabel -o axis --description 'Position of the axis of symmetry in the image in pixels from the left edge of…'
complete -c pgmabel -o factor --description 'User defined factor for enhancement of the output.'
complete -c pgmabel -o pixsize --description 'The size of a pixel for getting scale invariant.   Default is 0. 1.'
complete -c pgmabel -o left --description 'Calculate only the left side of the image.'
complete -c pgmabel -o right --description 'Analogous to -left.'
complete -c pgmabel -o verbose --description 'print information about the calculation.  EXAMPLE.'

