# pgmkernel
# Autogenerated from man page /usr/share/man/man1/pgmkernel.1.gz
complete -c pgmkernel -o weight --description 'The distance from the center is weighted by this; a higher number means the v…'
complete -c pgmkernel -o maxval --description 'The maxval for the PGM kernel.'

