# pgmmedian
# Autogenerated from man page /usr/share/man/man1/pgmmedian.1.gz
complete -c pgmmedian -o cutoff --description 'This option provides the cutoff value that pgmmedian uses to decide between u…'
complete -c pgmmedian -o width --description 'Width of the median mask to apply. sp Default is 3.'
complete -c pgmmedian -o height --description 'Height of the median mask to apply. sp Default is 3.'
complete -c pgmmedian -o type --description 'This option selects which method to use to find median regardless of cutoff v…'

