# pgmnoise
# Autogenerated from man page /usr/share/man/man1/pgmnoise.1.gz
complete -c pgmnoise -o maxval --description 'The maxval of the generated image. sp Default is 255.'
complete -c pgmnoise -o randomseed --description 'This is the seed for the random number generator that generates the pixels.'

