# picttoppm
# Autogenerated from man page /usr/share/man/man1/picttoppm.1.gz
complete -c picttoppm -o fontdir --description 'Make the list of BDF fonts in file available for use by picttoppm when drawin…'
complete -c picttoppm -o fullres --description 'Force any images in the PICT file to be output with at least their full resol…'
complete -c picttoppm -o noheader --description 'Do not assume the first 512 bytes of the file are a header.'
complete -c picttoppm -o quickdraw --description 'Execute only pure quickdraw operations.'
complete -c picttoppm -o verbose --description 'Print a whole bunch of information about the PICT file and the conversion pro…'

