# pidof
# Autogenerated from man page /usr/share/man/man8/pidof.8.gz
complete -c pidof -s s --description 'Single shot - this instructs the program to only return one pid.'
complete -c pidof -s c --description 'Only return process ids that are running with the same root directory.'
complete -c pidof -s n --description 'Avoid  stat (2) system function call on all binaries which are located on net…'
complete -c pidof -s x --description 'Scripts too - this causes the program to also return process id\'s of shells r…'
complete -c pidof -s o --description 'Tells pidof to omit processes with that process id.'

