# pkey
# Autogenerated from man page /usr/share/man/man1/pkey.1ssl.gz
complete -c pkey -o help --description 'Print out a usage message.'
complete -c pkey -o inform --description 'This specifies the input format \\s-1DER\\s0 or \\s-1PEM.'
complete -c pkey -o outform --description 'This specifies the output format, the options have the same meaning and defau…'
complete -c pkey -o in --description 'This specifies the input filename to read a key from or standard input if thi…'
complete -c pkey -o passin --description 'The input file password source.'
complete -c pkey -o out --description 'This specifies the output filename to write a key to or standard output if th…'
complete -c pkey -o passout --description 'The output file password source.'
complete -c pkey -o traditional --description 'Normally a private key is written using standard format: this is PKCS#8 form …'
complete -c pkey -o text --description 'Prints out the various public or private key components in plain text in addi…'
complete -c pkey -o text_pub --description 'Print out only public key components even if a private key is being processed.'
complete -c pkey -o noout --description 'Do not output the encoded version of the key.'
complete -c pkey -o pubin --description 'By default a private key is read from the input file: with this option a publ…'
complete -c pkey -o pubout --description 'By default a private key is output: with this option a public key will be out…'
complete -c pkey -o engine --description 'Specifying an engine (by its unique id string) will cause pkey to attempt to …'
complete -c pkey -o check --description 'This option checks the consistency of a key pair for both public and private …'

