# pkeyparam
# Autogenerated from man page /usr/share/man/man1/pkeyparam.1ssl.gz
complete -c pkeyparam -o help --description 'Print out a usage message.'
complete -c pkeyparam -o in --description 'This specifies the input filename to read parameters from or standard input i…'
complete -c pkeyparam -o out --description 'This specifies the output filename to write parameters to or standard output …'
complete -c pkeyparam -o text --description 'Prints out the parameters in plain text in addition to the encoded version.'
complete -c pkeyparam -o noout --description 'Do not output the encoded version of the parameters.'
complete -c pkeyparam -o engine --description 'Specifying an engine (by its unique id string) will cause pkeyparam to attemp…'

