# pngtopam
# Autogenerated from man page /usr/share/man/man1/pngtopam.1.gz
complete -c pngtopam -o verbose --description 'Display various information about the input PNG image and the conversion proc…'
complete -c pngtopam -o alphapam --description 'Produce a single output image containing the main image (foreground) and the …'
complete -c pngtopam -o alpha --description 'Output the transparency channel or transparency mask of the image.'
complete -c pngtopam -o mix --description 'Compose the image with the transparency or transparency mask against a backgr…'
complete -c pngtopam -o background --description 'This option specifies the background color with which to mix the image when y…'
complete -c pngtopam -o gamma --description 'This option causes pngtopam to respect the image gamma information in the PNG…'
complete -c pngtopam -o text --description 'Writes the tEXt and zTXt chunks to a file, in a format as described in the pn…'
complete -c pngtopam -o time --description 'Prints the tIME chunk to stderr.'
complete -c pngtopam -o byrow --description 'This option can make pngtopam run faster or in environments where it would ot…'
complete -c pngtopam -o orientraw --description 'A TIFF stream contains raster data which can be arranged in the stream variou…'

