# pnmcolormap
# Autogenerated from man page /usr/share/man/man1/pnmcolormap.1.gz
complete -c pnmcolormap -o sort --description 'This option causes the output colormap to be sorted by the red component inte…'
complete -c pnmcolormap -o square --description 'By default, pnmcolormap produces as the color map a PPM image with one row an…'
complete -c pnmcolormap -o verbose --description 'This option causes pnmcolormap to display messages to Standard Error about th…'
complete -c pnmcolormap -o map --description 'OPTIONS.'
complete -c pnmcolormap -o center --description '.'
complete -c pnmcolormap -o meancolor --description '.'
complete -c pnmcolormap -o meanpixel --description '.'
complete -c pnmcolormap -o spreadbrightness --description '.'
complete -c pnmcolormap -o spreadluminosity --description 'These options control the quantization algorithm.   See .'

