# pnmconvol
# Autogenerated from man page /usr/share/man/man1/pnmconvol.1.gz
complete -c pnmconvol -o matrix --description 'The value of the convolution matrix.   See .'
complete -c pnmconvol -o matrixfile --description 'This specifies that you are supplying the convolution matrix in a file and na…'
complete -c pnmconvol -o normalize --description 'This option says to adjust the weights in your convolution matrix so they all…'
complete -c pnmconvol -o bias --description 'sp This specifies an amount to add to the convolved value for each sample.'
complete -c pnmconvol -o nooffset --description 'This is part of the obsolete PNM image method of specifying the convolution m…'

