# pnmgamma
# Autogenerated from man page /usr/share/man/man1/pnmgamma.1.gz
complete -c pnmgamma -o bt709tolinear --description 'Convert the image from BT. 709 luminance to radiance.   I. e.'
complete -c pnmgamma -o lineartobt709 --description 'Convert the image from radiance to BT. 709 luminance.   I. e.'
complete -c pnmgamma -o bt709tosrgb --description 'Convert the image from BT. 709 luminance to SRGB luminance.  I. e.'
complete -c pnmgamma -o srgbtobt709 --description 'Convert the image from SRGB luminance to BT. 709 luminance.  I. e.'
complete -c pnmgamma -o bt709ramp --description 'Same as -lineartobt709, but using the old syntax.'
complete -c pnmgamma -o cieramp --description 'This is an obsolete synonym for -bt709ramp.'
complete -c pnmgamma -o srgbramp --description 'Convert the image from radiance to SRGB luminance.'
complete -c pnmgamma -o ungamma --description 'Apply the inverse of the specified transfer function (i. e.'
complete -c pnmgamma -o gamma --description 'This specifies the gamma value to use in the transfer function.'
complete -c pnmgamma -o bgamma --description 'These options are just like -gamma, except they specify the value for a parti…'
complete -c pnmgamma -o rgamma --description '.'
complete -c pnmgamma -o ggamma --description '.'
complete -c pnmgamma -o maxval --description 'This is the maxval of the output image.'

