# pnmindex
# Autogenerated from man page /usr/share/man/man1/pnmindex.1.gz
complete -c pnmindex -o size --description 'The size of each thumbnail.'
complete -c pnmindex -o across --description 'The number of thumbnails in each row.   Default is 6.'
complete -c pnmindex -o colors --description 'The maximum number of colors allowed in the overall image.'
complete -c pnmindex -o black --description 'This controls the color of the padding between the images; normally it\'s whit…'
complete -c pnmindex -o title --description 'Specifies a title top place at the top of the image.  Default is no title.'
complete -c pnmindex -o quant --description 'Enables quantization (to the number of colors specified by -colors).'
complete -c pnmindex -o noquant --description '.'

