# pnmpsnr
# Autogenerated from man page /usr/share/man/man1/pnmpsnr.1.gz
complete -c pnmpsnr -o rgb --description 'This option causes pnmpsnr to compare the red, green, and blue components of …'
complete -c pnmpsnr -o machine --description 'This option causes pnmpsnr to report the PSNRs in machine-friendly form, so a…'
complete -c pnmpsnr -o max -o max --description 'inf.'

