# pnmrotate
# Autogenerated from man page /usr/share/man/man1/pnmrotate.1.gz
complete -c pnmrotate -o background --description 'This determines the color of the background on which the rotated image sits.'
complete -c pnmrotate -o noantialias --description 'either way, as it keeps a copy of the input image and a copy of the output im…'

