# pnmshear
# Autogenerated from man page /usr/share/man/man1/pnmshear.1.gz
complete -c pnmshear -o background --description 'This determines the color of the background on which the sheared image sits.'
complete -c pnmshear -o noantialias --description 'This option forces pnmshear to simply move pixels around instead  of synthesi…'

