# pnmstitch
# Autogenerated from man page /usr/share/man/man1/pnmstitch.1.gz
complete -c pnmstitch -o yrightpos --description 'These are constraints on where pnmstitch stitches the images together.'
complete -c pnmstitch -o stitcher --description 'LinearSliver} The default is RotateSliver.'
complete -c pnmstitch -o filter --description 'No details available.'
complete -c pnmstitch -o output --description 'Name of output file.'
complete -c pnmstitch -o width --description '.'
complete -c pnmstitch -o height --description '.'
complete -c pnmstitch -o xrightpos --description '.'
complete -c pnmstitch -o verbose --description 'This option causes pnmstitch to issue messages to Standard Error about the st…'

