# pnmtorle
# Autogenerated from man page /usr/share/man/man1/pnmtorle.1.gz
complete -c pnmtorle -s v --description 'This option will cause pnmtorle to operate in verbose mode.'
complete -c pnmtorle -s h --description 'This option allows the header of the Netpbm image to be dumped to "stderr" wi…'
complete -c pnmtorle -s a --description 'This option causes pnmtorle to include an transparency channel in the output …'
complete -c pnmtorle -s o --description 'If you specify this option, pnmtorle writes the output to this file.'

