# pnmtosgi
# Autogenerated from man page /usr/share/man/man1/pnmtosgi.1.gz
complete -c pnmtosgi -o verbatim --description 'Write an uncompressed file.'
complete -c pnmtosgi -o rle --description 'Write a compressed (run length encoded) file.'
complete -c pnmtosgi -o imagename --description 'Write the string "name" into the imagename field of the header.'

