# pnmtopclxl
# Autogenerated from man page /usr/share/man/man1/pnmtopclxl.1.gz
complete -c pnmtopclxl -o dpi --description 'This option selects the resolution of the image (not the printer!).'
complete -c pnmtopclxl -o xoffs --description 'This option and -yoffs determine the location on the page of the upper left c…'
complete -c pnmtopclxl -o yoffs --description 'See -xoffs.'
complete -c pnmtopclxl -o center --description 'This option tells pnmtopclxl to center each image on the page.'
complete -c pnmtopclxl -o duplex --description 'This option causes pnmtopclxl to create a printer stream that prints pages on…'
complete -c pnmtopclxl -o format --description 'This option selects the media (e. g.'
complete -c pnmtopclxl -o feeder --description 'This options selects the media source (e. g.'
complete -c pnmtopclxl -o copies --description 'This option specifies the number of copies that the printer control stream te…'
complete -c pnmtopclxl -o rendergray --description 'This option causes pnmtopclxl to include in the output stream a command to se…'
complete -c pnmtopclxl -o jobsetup --description 'This option causes pnmtopclxl to include arbitrary job setup PJL commands at …'
complete -c pnmtopclxl -o colorok --description 'This option simply tells pnmtopclxl not to warn you if you supply a color inp…'
complete -c pnmtopclxl -o embedded --description 'Without this option, pnmtopclxl generates an entire printer control stream th…'

