# pnmtojbig
# Autogenerated from man page /usr/share/man/man1/pnmtojbig.1.gz
complete -c pnmtojbig -s q --description 'Encode the image in one single resolution layer (sequential mode).'
complete -c pnmtojbig -s x --description 'Specify the maximal horizontal size of the lowest resolution layer.'
complete -c pnmtojbig -s y --description 'Specify the maximal vertical size of the lowest resolution layer.'
complete -c pnmtojbig -s l --description 'Select the lowest resolution layer that will be written to the BIE.'
complete -c pnmtojbig -s h --description 'Select the highest resolution layer that will be written to the BIE.'
complete -c pnmtojbig -s b --description 'Use binary values instead of Gray code words in order to encode pixel values …'
complete -c pnmtojbig -s d --description 'Specify the total number of differential resolution layers into which the inp…'
complete -c pnmtojbig -s s --description 'The JBIG algorithm splits each image into a number of horizontal stripes.'
complete -c pnmtojbig -s m --description 'Select the maximum horizontal offset of the adaptive template pixel.'
complete -c pnmtojbig -s t --description 'Encode only the specified number of most significant bit planes.'
complete -c pnmtojbig -s o --description 'JBIG separates an image into several horizontal stripes, resolution layers an…'
complete -c pnmtojbig -s p --description 'This option allows you to activate or deactivate various optional algorithms …'
complete -c pnmtojbig -s c --description 'The adaptive template pixel movement is determined as suggested in annex C of…'
complete -c pnmtojbig -s v --description 'After pnmtojbig creates the BIE, it lists a few technical details of the crea…'

