# postdrop
# Autogenerated from man page /usr/share/man/man1/postdrop.1.gz
complete -c postdrop -s c --description 'The main.'
complete -c postdrop -s r --description 'Use a Postfix-internal protocol for reading the message from standard input, …'
complete -c postdrop -s v --description 'Enable verbose logging for debugging purposes.'

