# postfix-tls
# Autogenerated from man page /usr/share/man/man1/postfix-tls.1.gz
complete -c postfix-tls -s T --description 'keyfile list uses the values of the corresponding Postfix server TLS key file…'

