# postkick
# Autogenerated from man page /usr/share/man/man1/postkick.1.gz
complete -c postkick -s c --description 'Read the main.'
complete -c postkick -s v --description 'Enable verbose logging for debugging purposes.'

