# postmulti
# Autogenerated from man page /usr/share/man/man1/postmulti.1.gz
complete -c postmulti -s a --description 'Perform the operation on all instances.  This is the default.'
complete -c postmulti -s g --description 'Perform the operation only for members of the named group.'
complete -c postmulti -s i --description 'Perform the operation only for the instance with the specified name.'
complete -c postmulti -s R --description 'Reverse the iteration order.'
complete -c postmulti -s l --description 'List Postfix instances with their instance name, instance group name, enable/…'
complete -c postmulti -s p --description 'Invoke postfix(1) to execute postfix-command.'
complete -c postmulti -s x --description 'Execute the specified unix-command for all Postfix instances.'
complete -c postmulti -s v --description 'Enable verbose logging for debugging purposes.  Multiple.'
complete -c postmulti -s I --description 'Assign the specified instance name to an existing instance, newly-created ins…'
complete -c postmulti -s G --description 'Assign the specified group name to an existing instance or to a newly created…'
complete -c postmulti -s e --description '"Edit" managed instances.  The following actions are supported:.'

