# ppm3d
# Autogenerated from man page /usr/share/man/man1/ppm3d.1.gz
complete -c ppm3d -o offset --description 'This option indicates the amount, in pixels, by which the left and image is o…'
complete -c ppm3d -o color --description 'This option causes ppm3d to generate a color anaglyph stereogram.'

