# ppmbrighten
# Autogenerated from man page /usr/share/man/man1/ppmbrighten.1.gz
complete -c ppmbrighten -o value --description 'This option specifies the amount, as a per centage, by which you want to chan…'
complete -c ppmbrighten -o saturation --description 'This option specifies the amount, as a per centage, by which you want to chan…'
complete -c ppmbrighten -o normalize --description 'This option causes ppmbrighten to linearly remap the Values of the pixels to …'

