# ppmdist
# Autogenerated from man page /usr/share/man/man1/ppmdist.1.gz
complete -c ppmdist -o frequency --description 'Sort input colors by the number of times a color appears in the input, before…'
complete -c ppmdist -o intensity --description 'Sort input colors by their grayscale intensity, before mapping to evenly dist…'

