# ppmforge
# Autogenerated from man page /usr/share/man/man1/ppmforge.1.gz
complete -c ppmforge -o clouds --description 'Generate clouds.   An image of fractal clouds is generated.'
complete -c ppmforge -o dimension --description 'Sets the fractal dimension to the specified dimen, which may be any floating …'
complete -c ppmforge -o glaciers --description 'The floating point level setting controls the extent to which terrain elevati…'
complete -c ppmforge -o hour --description 'When generating a planet, ppmforge uses hour as the "hour angle at the centra…'
complete -c ppmforge -o ice --description 'Sets the extent of the polar ice caps to the given floating point level.'
complete -c ppmforge -o inclination -o tilt --description 'The inclination angle of the planet with regard to its primary star is set to…'
complete -c ppmforge -o mesh --description 'A mesh of size by size will be used for the fast Fourier transform (FFT).'
complete -c ppmforge -o night --description 'A starry sky is generated.'
complete -c ppmforge -o power --description 'Sets the "power factor" used to scale elevations synthesised from the FFT to …'
complete -c ppmforge -o saturation --description 'Controls the degree of color saturation of the stars that surround planet pic…'
complete -c ppmforge -o seed --description 'Sets the seed for the random number generator to the integer num.'
complete -c ppmforge -o stars --description 'Specifies the percentage of pixels, in tenths of a percent, which will appear…'
complete -c ppmforge -o xsize -o width --description 'Sets the width of the generated image to width pixels.'
complete -c ppmforge -o ysize -o height --description 'Sets the height of the generated image to height pixels.'

