# ppmrough
# Autogenerated from man page /usr/share/man/man1/ppmrough.1.gz
complete -c ppmrough -o left --description 'Specifies the mean distance of the border from the left margin (default: no b…'
complete -c ppmrough -o right --description 'Specifies the mean distance of the border from the right margin (default: no …'
complete -c ppmrough -o top --description 'Specifies the mean distance of the border from the top margin (default: no bo…'
complete -c ppmrough -o bottom --description 'Specifies the mean distance of the border from the bottom margin (default: no…'
complete -c ppmrough -o width --description 'Specifies the width of the image (default: 100).'
complete -c ppmrough -o height --description 'Specifies the height of the image (default: 100).'
complete -c ppmrough -o bg --description 'Background color.   colorspec is as described for the . UR libppm.'
complete -c ppmrough -o fg --description 'Foreground color.   colorspec is as described for the . UR libppm.'
complete -c ppmrough -o var --description 'Specifies the variance of the ragged border (default: 10).'
complete -c ppmrough -o randomseed --description 'Use this option to initialize the pseudo-random number generator (the Standar…'
complete -c ppmrough -o verbose --description 'Run ppmrough in verbose mode.   It reports all parameters on Standard Error.'

