# ppmtopcx
# Autogenerated from man page /usr/share/man/man1/ppmtopcx.1.gz
complete -c ppmtopcx -o 24bit --description 'Produce a 24bit truecolor PCX file, even if the image has 256 colors or fewer.'
complete -c ppmtopcx -o 8bit --description 'Produce an 8bit (256 colors) PCX file, even if the image has 16 colors or few…'
complete -c ppmtopcx -o packed --description 'Use "packed pixel" format for files with 16 colors or fewer: 1, 2, or 4 bits/…'
complete -c ppmtopcx -o stdpalette --description 'Instead of computing a palette from the colors in the image, use a standard, …'
complete -c ppmtopcx -o palette --description 'Instead of computing the palette from the colors in the image, use the palett…'
complete -c ppmtopcx -o planes --description 'Generate a PCX file with planes planes, even though the number of colors in t…'
complete -c ppmtopcx -o xpos --description '.'
complete -c ppmtopcx -o ypos --description ' These options set the position of the image in some field (e. g.'

