# ppmtoacad
# Autogenerated from man page /usr/share/man/man1/ppmtoacad.1.gz
complete -c ppmtoacad -o dxb --description 'ppmtoacad writes an Autocad binary database import (. dxb) file.'
complete -c ppmtoacad -o poly --description 'If you don\'t specify the -dxb option, ppmtoacad generates an Autocad slide fi…'
complete -c ppmtoacad -o background --description 'Most Autocad display drivers can be configured to use any available color as …'
complete -c ppmtoacad -o white --description 'Since many Autocad users choose a white screen background, this option is pro…'
complete -c ppmtoacad -o aspect --description 'If the source image had non-square pixels (which means it is not standard PPM…'
complete -c ppmtoacad -s 8 --description 'Restricts the colors in the output file to the 8 RGB shades.  RESTRICTIONS.'

