# ppmtoxpm
# Autogenerated from man page /usr/share/man/man1/ppmtoxpm.1.gz
complete -c ppmtoxpm -o name --description 'This option specifies the prefix string which is specified in the resulting X…'
complete -c ppmtoxpm -o hexonly --description 'This option says never to put color names in the XPM file, but rather to iden…'
complete -c ppmtoxpm -o rgb --description 'This option names the file in which the color dictionary you want to use resi…'
complete -c ppmtoxpm -o alphamask --description ' This option names a PGM file to use as a transparency (alpha) mask.'

