# ppmtopjxl
# Autogenerated from man page /usr/share/man/man1/ppmtopjxl.1.gz
complete -c ppmtopjxl -o dither -o cluster -o diffuse --description 'options select ordered dithering, clustered ordered dithering, or error diffu…'
complete -c ppmtopjxl -o ysize --description 'interpreted as the number of dots to set the width or height to, but you may …'
complete -c ppmtopjxl -o xsize --description '.'
complete -c ppmtopjxl -o yshift --description 'right and down.'

