# ppmtoarbtxt
# Autogenerated from man page /usr/share/man/man1/ppmtoarbtxt.1.gz
complete -c ppmtoarbtxt -o hd --description 'This option specifies a head template (headtmpl is the name of the head templ…'
complete -c ppmtoarbtxt -o tl --description 'This option specifies a tail template; it is analogous to -hd.  EXAMPLES.'

