# printf
# Autogenerated from man page /usr/share/man/man1/printf.1.gz
complete -c printf -l help --description 'display this help and exit.'
complete -c printf -l version --description 'output version information and exit .'

