# procmail
# Autogenerated from man page /usr/share/man/man1/procmail.1.gz
complete -c procmail -s v --description 'Procmail will print its version number, display its compile time configuratio…'
complete -c procmail -s p --description 'Preserve any old environment.'
complete -c procmail -s t --description 'Make procmail fail softly, i. e.'
complete -c procmail -s f --description 'Causes procmail to regenerate the leading `From \' line with  fromwhom as the …'
complete -c procmail -s o --description 'Instead of allowing anyone to generate `From \' lines, simply override the fak…'
complete -c procmail -s Y --description 'Assume traditional Berkeley mailbox format, ignore any  Content-Length: field…'
complete -c procmail -s a --description 'This will set $1 to be equal to R argument .'
complete -c procmail -s d --description 'This turns on explicit delivery mode, delivery will be to the local user R re…'
complete -c procmail -s m --description 'Turns procmail into a general purpose mail filter.'
complete -c procmail -s z --description 'This turns on LMTP mode, wherein procmail acts as an RFC2033 LMTP server.'

