# profiles
# Autogenerated from man page /usr/share/man/man1/profiles.1.gz
complete -c profiles -s v -l verbose --description 'Increases verbosity of messages.'
complete -c profiles -s c -s n -l change-sid -l new-sid --description 'Change all occurrences of SID1 in file by SID2.'
complete -c profiles -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c profiles -s V -l version --description 'Prints the program version number.'
complete -c profiles -s s -l configfile --description 'The file specified contains the configuration details required by the server.'
complete -c profiles -s l -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c profiles -l option --description 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line.'
complete -c profiles -s '?' -l help --description 'Print a summary of command line options.'
complete -c profiles -l usage --description 'Display brief usage message.'

