# psnup
# Autogenerated from man page /usr/share/man/man1/psnup.1.gz
complete -c psnup -s w --description 'option gives the paper width, and the.'
complete -c psnup -s h --description 'option gives the paper height, normally specified in cm or in to convert  Pos…'
complete -c psnup -s p --description 'option can be used as an alternative, to set the paper size to a3, a4, a5, b5…'
complete -c psnup -s W -s H --description 'and.'
complete -c psnup -s P --description 'options set the input paper size, if it is different from the output size.'
complete -c psnup -s l --description 'option should be used for pages which are in landscape orientation (rotated 9…'
complete -c psnup -s r --description 'option should be used for pages which are in seascape orientation (rotated 90…'
complete -c psnup -s f --description 'option should be used for pages which have the width and height interchanged,…'
complete -c psnup -s c --description 'option changes the order to `column-major\', where successive pages are placed…'
complete -c psnup -s m --description 'option.'
complete -c psnup -s b --description 'option is used to specify an additional margin around each page on a sheet.'
complete -c psnup -s d --description 'option draws a line around the border of each page, of the specified width.'
complete -c psnup -s s --description 'option.  This is useful to merge pages which are already reduced.'
complete -c psnup -o nup --description 'option selects the number of logical pages to put on each sheet of paper.'
complete -c psnup -s q --description 'option suppresses this.'

