# psresize
# Autogenerated from man page /usr/share/man/man1/psresize.1.gz
complete -c psresize -s w --description 'option gives the output paper width, and the.'
complete -c psresize -s h --description 'option gives the output paper height, normally specified in cm or in to conve…'
complete -c psresize -s p --description 'option can be used as an alternative, to set the output paper size to a3, a4,…'
complete -c psresize -s W --description 'option gives the input paper width, and the.'
complete -c psresize -s H --description 'option gives the input paper height.  The .'
complete -c psresize -s P --description 'option can be used as an alternative, to set the input paper size.'
complete -c psresize -s q --description 'option suppresses this.'

