# pw-dot
# Autogenerated from man page /usr/share/man/man1/pw-dot.1.gz
complete -c pw-dot -s r -l remote --description 'The name the remote instance to connect to.'
complete -c pw-dot -s h -l help --description 'Show help.'
complete -c pw-dot -l version --description 'Show version information.'
complete -c pw-dot -s a -l all --description 'Show all object types.'
complete -c pw-dot -s s -l smart --description 'Show linked objects only.'
complete -c pw-dot -s d -l detail --description 'Show all object properties.'
complete -c pw-dot -s o -l output --description 'Output file name (Default pw. dot).'

