# pw-profiler
# Autogenerated from man page /usr/share/man/man1/pw-profiler.1.gz
complete -c pw-profiler -s r -l remote --description 'The name the remote instance to monitor.'
complete -c pw-profiler -s h -l help --description 'Show help.'
complete -c pw-profiler -l version --description 'Show version information.'
complete -c pw-profiler -s o -l output --description 'Profiler output name (default "profiler. log").'

