# pygmentize
# Autogenerated from man page /usr/share/man/man1/pygmentize.1.gz
complete -c pygmentize -s l --description 'Set the lexer name.'
complete -c pygmentize -s F --description 'Add a filter to the token stream.'
complete -c pygmentize -s f --description 'Set the formatter name.'
complete -c pygmentize -s o --description 'Set output file.  If not given, stdout is used.'
complete -c pygmentize -s O --description 'With this option, you can give the lexer and formatter a comma-separated list…'
complete -c pygmentize -s P --description 'This option adds lexer and formatter options like the -O option, but you can …'
complete -c pygmentize -s S --description 'Print out style definitions for style <style> and for formatter <formatter>.'
complete -c pygmentize -s L --description 'List lexers, formatters, styles or filters.'
complete -c pygmentize -s H --description 'Print detailed help for the object <name> of type <type>, where <type> is one…'
complete -c pygmentize -s h --description 'Show help screen.'
complete -c pygmentize -s a --description 'is formatter dependent and can be found in the documentation.'
complete -c pygmentize -s V --description 'Show version of the Pygments package.'

