# quotaon
# Autogenerated from man page /usr/share/man/man8/quotaon.8.gz
complete -c quotaon -s F -l format --description 'Report quota for specified format (ie.  don\'t perform format autodetection).'
complete -c quotaon -s a -l all --description 'All automatically mounted (no  noauto option) non-NFS filesystems in  /etc/fs…'
complete -c quotaon -s v -l verbose --description 'Display a message for each filesystem where quotas are turned on.'
complete -c quotaon -s u -l user --description 'Manipulate user quotas.  This is the default.'
complete -c quotaon -s g -l group --description 'Manipulate group quotas.'
complete -c quotaon -s P -l project --description 'Manipulate project quotas.'
complete -c quotaon -s p -l print-state --description 'Instead of turning quotas on just print state of quotas (ie.  whether.'
complete -c quotaon -s x -l xfs-command --description 'Switch on limit enforcement for XFS filesystems.'
complete -c quotaon -s f -l off --description 'Make  quotaon behave like being called as  quotaoff . SS quotaoff.'

