# quotacheck
# Autogenerated from man page /usr/share/man/man8/quotacheck.8.gz
complete -c quotacheck -s b -l backup --description 'Forces  quotacheck to make backups of the quota file before writing the new d…'
complete -c quotacheck -s v -l verbose --description 'quotacheck reports its operation as it progresses.'
complete -c quotacheck -s d -l debug --description 'Enable debugging mode.'
complete -c quotacheck -s u -l user --description 'Only user quotas listed in  /etc/mtab or on the filesystems specified are to …'
complete -c quotacheck -s g -l group --description 'Only group quotas listed in  /etc/mtab or on the filesystems specified are to…'
complete -c quotacheck -s c -l create-files --description 'Don\'t read existing quota files.  Just perform a new scan and save it to disk.'
complete -c quotacheck -s f -l force --description 'Forces checking and writing of new quota files on filesystems with quotas ena…'
complete -c quotacheck -s M -l try-remount --description 'This flag forces checking of filesystem in read-write mode if a remount fails.'
complete -c quotacheck -s m -l no-remount --description 'Don\'t try to remount filesystem read-only.  See comment with option  -M .'
complete -c quotacheck -s i -l interactive --description 'Interactive mode.  By default  quotacheck exits when it finds an error.'
complete -c quotacheck -s n -l use-first-dquot --description 'If the quota files become corrupted, it is possible for duplicate entries for…'
complete -c quotacheck -s F -l format --description 'Check and fix quota files of specified format (ie.'
complete -c quotacheck -s a -l all --description 'Check all mounted non-NFS filesystems in  /etc/mtab.'
complete -c quotacheck -s R -l exclude-root --description 'When used together with the.'

