# rasqal-config
# Autogenerated from man page /usr/share/man/man1/rasqal-config.1.gz
complete -c rasqal-config -l version --description 'Print the currently installed version of rasqal on the standard output.'
complete -c rasqal-config -l version-decimal --description 'Print the currently installed version of rasqal as a decimal integer.'
complete -c rasqal-config -l libs --description 'Print the linker flags that are necessary to link a program with Rasqal.'
complete -c rasqal-config -l libtool-libs --description 'Print the path to the libtool file for rasqal.'
complete -c rasqal-config -l cflags --description 'Print the compiler flags that are necessary to compile a program with the RDF…'
complete -c rasqal-config -l prefix --description 'If specified, use PREFIX instead of the installation prefix that Rasqal was b…'

