# rasttopnm
# Autogenerated from man page /usr/share/man/man1/rasttopnm.1.gz
complete -c rasttopnm -o index --description 'This odd option tells rasttopnm to use the color map indices in the raster as…'

