# rcs2log
# Autogenerated from man page /usr/share/man/man1/rcs2log.1.gz
complete -c rcs2log -s c --description 'Output a change log prefix to changelog (default ChangeLog).'
complete -c rcs2log -s h --description 'Use hostname in change log entries (default current host).'
complete -c rcs2log -s i --description 'Indent change log lines by indent spaces (default 8).'
complete -c rcs2log -s l --description 'Try to limit log lines to length characters (default 79).'
complete -c rcs2log -s R --description 'If no file Ns Li (s) are given and RCS is used, recurse through working direc…'
complete -c rcs2log -s r --description 'Pass option to subsidiary log command.'
complete -c rcs2log -s t --description 'Tab stops are every tabwidth characters (default 8).'
complete -c rcs2log -s u --description 'Assume login has fullname and mailaddr.'
complete -c rcs2log -s v --description 'Append RCS revision to file names in log lines.'
complete -c rcs2log -l help --description 'Output help.'
complete -c rcs2log -l version --description 'Output version number.'

