# red
# Autogenerated from man page /usr/share/man/man1/red.1.gz
complete -c red -s h -l help --description 'display this help and exit.'
complete -c red -s V -l version --description 'output version information and exit.'
complete -c red -s G -l traditional --description 'run in compatibility mode.'
complete -c red -s l -l loose-exit-status --description 'exit with 0 status even if a command fails.'
complete -c red -s p -l prompt --description 'use STRING as an interactive prompt.'
complete -c red -s r -l restricted --description 'run in restricted mode.'
complete -c red -s s -l quiet -l silent --description 'suppress diagnostics, byte counts and \'!\' prompt.'
complete -c red -s v -l verbose --description 'be verbose; equivalent to the \'H\' command.'

