# regdiff
# Autogenerated from man page /usr/share/man/man1/regdiff.1.gz
complete -c regdiff -l help --description 'Show list of available options.'
complete -c regdiff -l backend --description 'Name of backend to load.  Possible values are: creg, regf, dir and rpc.'
complete -c regdiff -l credentials --description 'Credentials to use, if any.'

