# regtree
# Autogenerated from man page /usr/share/man/man1/regtree.1.gz
complete -c regtree -l help --description 'Show list of available options.'
complete -c regtree -l backend --description 'Name of backend to load.  Possible values are: creg, regf, dir and rpc.'
complete -c regtree -l credentials --description 'Credentials to use, if any.'
complete -c regtree -l fullpath --description 'Print the full path to each key instead of only its name.'
complete -c regtree -l no-values --description 'Don\\*(Aqt print values, just keys.'

