# rehash
# Autogenerated from man page /usr/share/man/man1/rehash.1ssl.gz
complete -c rehash -o help -s h --description 'Display a brief usage message.'
complete -c rehash -o old --description 'Use old-style hashing (\\s-1MD5,\\s0 as opposed to \\s-1SHA-1\\s0) for generating…'
complete -c rehash -s n --description 'Do not remove existing links.'
complete -c rehash -o compat --description 'Generate links for both old-style (\\s-1MD5\\s0) and new-style (\\s-1SHA1\\s0) ha…'

