# rendercheck
# Autogenerated from man page /usr/share/man/man1/rendercheck.1.gz
complete -c rendercheck -s d -l displaydisplay --description 'Specifies the display to test against.'
complete -c rendercheck -s i -l iteriterations --description 'Specifies the number of times to repeat each operation before sampling result…'
complete -c rendercheck -l sync --description 'Enables synchronous xlib operation, for debugging.'
complete -c rendercheck -s t -l teststest1 --description 'Enables only a specific subset of the possible tests.'
complete -c rendercheck -s f -l formatsformat1 --description 'Enables only a specific subset of the possible formats.'
complete -c rendercheck -s o -l ops --description 'Enables only a specific subset of the Render operators.'
complete -c rendercheck -s v -l verbose --description 'Enables verbose printing of information on tests run, and successes and failu…'
complete -c rendercheck -l display --description 'Specifies the display to test against.'
complete -c rendercheck -l iter --description 'Specifies the number of times to repeat each operation before sampling result…'
complete -c rendercheck -l tests --description 'Enables only a specific subset of the possible tests.'
complete -c rendercheck -l formats --description 'Enables only a specific subset of the possible formats.'
complete -c rendercheck -l minimalrendering --description 'Disables copying of offscreen destinations to the window, which is on by defa…'

