# resolve_stack_dump
# Autogenerated from man page /usr/share/man/man1/resolve_stack_dump.1.gz
complete -c resolve_stack_dump -l help --description '.'
complete -c resolve_stack_dump -s h --description '.'
complete -c resolve_stack_dump -l numeric-dump-file --description '.'
complete -c resolve_stack_dump -s n --description '.'
complete -c resolve_stack_dump -l symbols-file --description '.'
complete -c resolve_stack_dump -s s --description '.'
complete -c resolve_stack_dump -l version --description '.'
complete -c resolve_stack_dump -s V --description '.'

