# rletopnm
# Autogenerated from man page /usr/share/man/man1/rletopnm.1.gz
complete -c rletopnm -l alphaout --description 'rletopnm  creates a PGM (portable graymap) file containing the transparency c…'
complete -c rletopnm -l verbose --description 'This option causes rletopnm  to operate in verbose mode.'
complete -c rletopnm -l headerdump --description 'This option causes rletopnm to operate in header dump mode.'

