# rmcp_ping
# Autogenerated from man page /usr/share/man/man1/rmcp_ping.1.gz
complete -c rmcp_ping -s p --description 'Set the destination port.   This is the standard RMCP port by default, 623.'
complete -c rmcp_ping -s t --description 'Sets the number of seconds to wait for a response.   Ten by default.'
complete -c rmcp_ping -s s --description 'There is an 8-bit tag value in every ping packet (0-254, 255 is reserved), th…'
complete -c rmcp_ping -s d --description 'Turns on debugging to standard output.'

