# rmdir
# Autogenerated from man page /usr/share/man/man1/rmdir.1.gz
complete -c rmdir -s p -l parents --description 'remove DIRECTORY and its ancestors; e. g.'
complete -c rmdir -s v -l verbose --description 'output a diagnostic for every directory processed.'
complete -c rmdir -l help --description 'display this help and exit.'
complete -c rmdir -l ignore-fail-on-non-empty --description 'ignore each failure that is solely because a directory is non-empty.'
complete -c rmdir -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

