# rmid-java-11-openjdk
# Autogenerated from man page /usr/share/man/man1/rmid-java-11-openjdk.1.gz
complete -c rmid-java-11-openjdk -o Coption --description 'br Specifies an option that is passed as a command-line argument to each chil…'
complete -c rmid-java-11-openjdk -o Joption --description 'br Specifies an option that is passed to the Java interpreter running RMID.'
complete -c rmid-java-11-openjdk -o 'J-Dsun.rmi.activation.execPolicy' --description 'br Specifies the policy that RMID employs to check commands and command-line …'
complete -c rmid-java-11-openjdk -o log --description 'br Specifies the name of the directory the activation system daemon uses to w…'
complete -c rmid-java-11-openjdk -o port --description 'br Specifies the port the registry uses.'
complete -c rmid-java-11-openjdk -o stop --description '.'

