# rndc
# Autogenerated from man page /usr/share/man/man8/rndc.8.gz
complete -c rndc -s 4 --description 'Use IPv4 only.'
complete -c rndc -s 6 --description 'Use IPv6 only.'
complete -c rndc -s b --description 'Use source-address as the source address for the connection to the server.'
complete -c rndc -s c --description 'Use config-file as the configuration file instead of the default, /etc/rndc.'
complete -c rndc -s k --description 'Use key-file as the key file instead of the default, /etc/rndc. key.'
complete -c rndc -s s --description 'server is the name or address of the server which matches a server statement …'
complete -c rndc -s p --description 'Send commands to TCP port port instead of BIND 9\\(aqs default control channel…'
complete -c rndc -s q --description 'Quiet mode: Message text returned by the server will not be printed except wh…'
complete -c rndc -s r --description 'Instructs rndc to print the result code returned by named after executing the…'
complete -c rndc -s V --description 'Enable verbose logging.'
complete -c rndc -s y --description 'Use the key key_id from the configuration file.'
complete -c rndc -s d -s f --description '.'
complete -c rndc -o redirect --description 'would specify a zone called "-redirect". ) LIMITATIONS.'

