# rpcbind
# Autogenerated from man page /usr/share/man/man8/rpcbind.8.gz
complete -c rpcbind -s a --description 'When debugging d, do an abort on errors.'
complete -c rpcbind -s d --description 'Run in debug mode.'
complete -c rpcbind -s f --description 'Do not fork and become a background process.'
complete -c rpcbind -s h --description 'Specify specific IP addresses to bind to for UDP requests.'
complete -c rpcbind -s i --description 'Insecure mode.  Allow calls to SET and UNSET from any host.'
complete -c rpcbind -s l --description 'Turn on libwrap connection logging.'
complete -c rpcbind -s s --description 'Cause rpcbind to change to the user daemon as soon as possible.'
complete -c rpcbind -s w --description 'Cause rpcbind to do a "warm start" by read a state file when rpcbind starts u…'

