# rsyslogd
# Autogenerated from man page /usr/share/man/man8/rsyslogd.8.gz
complete -c rsyslogd -s D --description 'Runs the Bison config parser in debug mode.'
complete -c rsyslogd -s d --description 'Turns on debug mode.  See the DEBUGGING section for more information.'
complete -c rsyslogd -s f --description 'Specify an alternative configuration file instead of R /etc/rsyslog.'
complete -c rsyslogd -s i --description 'Specify an alternative pid file instead of the default one.'
complete -c rsyslogd -s n --description 'Avoid auto-backgrounding.'
complete -c rsyslogd -s N --description 'Do a config check.'
complete -c rsyslogd -s C --description 'This prevents rsyslogd from changing to the root directory.'
complete -c rsyslogd -s v --description 'Print version and exit.'

