# saned
# Autogenerated from man page /usr/share/man/man8/saned.8.gz
complete -c saned -s l --description 'flag requests that saned run in standalone daemon mode.'
complete -c saned -s b --description 'flag tells saned to bind to the address given.   The.'
complete -c saned -s u --description 'flag requests that saned drop root privileges and run as the user (and group)…'
complete -c saned -s D --description 'flag will request saned to detach from the console and run in the background.'
complete -c saned -s a --description 'is equivalent to the combination of.'
complete -c saned -s B --description 'username options.'
complete -c saned -s d --description 'flag sets the level of saned debug output.'
complete -c saned -o d128 --description 'will request output of all debug info.'
complete -c saned -s e --description 'flag will divert saned debug output to stderr instead of the syslog default.'
complete -c saned -s o --description 'flag requests that saned exits after the first client disconnects.'
complete -c saned -s h --description 'flag displays a short help message.'

