# scsi_start
# Autogenerated from man page /usr/share/man/man8/scsi_start.8.gz
complete -c scsi_start -s h -l help --description 'print out the usage message then exit.'
complete -c scsi_start -s v -l verbose --description 'increase level or verbosity.'
complete -c scsi_start -s w -l wait --description 'wait for the spin up (start) on each given DEVICE to complete.'

