# sftp-server
# Autogenerated from man page /usr/share/man/man8/sftp-server.8.gz
complete -c sftp-server -s d --description 'specifies an alternate starting directory for users.'
complete -c sftp-server -s e --description 'Causes sftp-server to print logging information to stderr instead of syslog f…'
complete -c sftp-server -s f --description 'Specifies the facility code that is used when logging messages from sftp-serv…'
complete -c sftp-server -s h --description 'Displays sftp-server usage information.'
complete -c sftp-server -s l --description 'Specifies which messages will be logged by sftp-server.'
complete -c sftp-server -s P --description 'Specify a comma-separated list of SFTP protocol requests that are banned by t…'
complete -c sftp-server -s p --description 'Specify a comma-separated list of SFTP protocol requests that are permitted b…'
complete -c sftp-server -s Q --description 'Query protocol features supported by sftp-server.'
complete -c sftp-server -s R --description 'Places this instance of sftp-server into a read-only mode.'
complete -c sftp-server -s u --description 'Sets an explicit umask 2 to be applied to newly-created files and directories…'
complete -c sftp-server -s m --description 'Sets explicit permissions to be applied to newly-created files and directorie…'

