# sg_decode_sense
# Autogenerated from man page /usr/share/man/man8/sg_decode_sense.8.gz
complete -c sg_decode_sense -s b -l binary --description 'the sense data is read in binary from a file called FN.'
complete -c sg_decode_sense -s c -l cdb --description 'treat the given string of hex arguments as bytes in a SCSI CDB and decode the…'
complete -c sg_decode_sense -s h -l help --description 'output the usage message then exit.'
complete -c sg_decode_sense -s H -l hex --description 'this option is used in conjunction with --write=WFN in order to change the ou…'
complete -c sg_decode_sense -s f -l file --description 'the sense data is read in ASCII hexadecimal from a file called FN.'
complete -c sg_decode_sense -s n -l nospace --description 'expect ASCII hexadecimal to be a string of hexadecimal digits with no spaces …'
complete -c sg_decode_sense -s s -l status --description 'where SS is a SCSI status byte value, given in hexadecimal.'
complete -c sg_decode_sense -s v -l verbose --description 'increase the degree of verbosity (debug messages).'
complete -c sg_decode_sense -s V -l version --description 'output version string then exit.'
complete -c sg_decode_sense -s w -l write --description 'writes the sense data out to a file called WFN.  If necessary WFN is created.'

