# sg_dd
# Autogenerated from man page /usr/share/man/man8/sg_dd.8.gz
complete -c sg_dd -l help --description 'outputs usage message and exits.'
complete -c sg_dd -l version --description 'outputs version number information and exits.'
complete -c sg_dd -s V --description 'outputs version number information and exits.'

