# sg_ident
# Autogenerated from man page /usr/share/man/man8/sg_ident.8.gz
complete -c sg_ident -s A -l ascii --description 'invokes the Report Identifying Information command and if anything is found i…'
complete -c sg_ident -s C -l clear --description 'invokes the Set Identifying Information command with an information length of…'
complete -c sg_ident -s h -l help --description 'output the usage message then exit.'
complete -c sg_ident -s i -l itype --description 'where IT is the information type.  Defaults to zero.'
complete -c sg_ident -s r -l raw --description 'invokes the Report Identifying information command and if anything is found s…'
complete -c sg_ident -s S -l set --description 'first reads stdin until an EOF is detected then invokes the Set Identifying I…'
complete -c sg_ident -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_ident -s V -l version --description 'print the version string and then exit.'

