# sg_luns
# Autogenerated from man page /usr/share/man/man8/sg_luns.8.gz
complete -c sg_luns -s d -l decode --description 'decode LUNs into their component parts, as described in the LUN section of SA…'
complete -c sg_luns -s h -l help --description 'output the usage message then exit.'
complete -c sg_luns -s H -l hex --description '[device mode] when given once this utility will output the SCSI response (i.'
complete -c sg_luns -s l -l linux --description 'this option is only available in Linux.'
complete -c sg_luns -s L -l lu_cong --description 'this option is only considered with --decode.'
complete -c sg_luns -s m -l maxlen --description 'where LEN is the (maximum) response length in bytes.'
complete -c sg_luns -s q -l quiet --description 'output only the ASCII hex rendering of each report LUN, one per line.'
complete -c sg_luns -s r -l raw --description 'output the SCSI response (i. e.  the data-out buffer) in binary (to stdout).'
complete -c sg_luns -s R -l readonly --description 'open the DEVICE read-only (e. g.  in Unix with the O_RDONLY flag).'
complete -c sg_luns -s s -l select --description 'SR is placed in the SELECT REPORT field of the SCSI REPORT LUNS command.'
complete -c sg_luns -s t -l test --description 'ALUN is assumed to be a hexadecimal number in ASCII hex or the letter \'L\' fol…'
complete -c sg_luns -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_luns -s V -l version --description 'print the version string and then exit.'

