# sg_prevent
# Autogenerated from man page /usr/share/man/man8/sg_prevent.8.gz
complete -c sg_prevent -s a -l allow --description 'allow medium removal.  This is equivalent to setting to \'--prevent=2\'.'
complete -c sg_prevent -s h -l help --description 'output the usage message then exit.'
complete -c sg_prevent -s p -l prevent --description 'where PC is a prevent code value.'
complete -c sg_prevent -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_prevent -s V -l version --description 'print the version string and then exit.'

