# sg_read_buffer
# Autogenerated from man page /usr/share/man/man8/sg_read_buffer.8.gz
complete -c sg_read_buffer -s h -l help --description 'output the usage message then exit.'
complete -c sg_read_buffer -s H -l hex --description 'output the response in hexadecimal.'
complete -c sg_read_buffer -s i -l id --description 'this option sets the buffer id field in the cdb.'
complete -c sg_read_buffer -s l -l length --description 'where LEN is the length, in bytes, that is placed in the "allocation length" …'
complete -c sg_read_buffer -s m -l mode --description 'this option sets the mode field in the cdb.'
complete -c sg_read_buffer -s o -l offset --description 'this option sets the buffer offset field in the cdb.'
complete -c sg_read_buffer -s r -l raw --description 'if a response is received then it is sent in binary to stdout.'
complete -c sg_read_buffer -s R -l readonly --description 'open the DEVICE read-only (e. g.  in Unix with the O_RDONLY flag).'
complete -c sg_read_buffer -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_read_buffer -s V -l version --description 'print the version string and then exit.'

