# sg_raw
# Autogenerated from man page /usr/share/man/man8/sg_raw.8.gz
complete -c sg_raw -s b -l binary --description 'Dump data in binary form, even when writing to stdout.'
complete -c sg_raw -s c -l cmdfile --description 'CF is the name of a file which contains the command to be executed.'
complete -c sg_raw -s h -l help --description 'Display usage information and exit.'
complete -c sg_raw -s i -l infile --description 'Read data from IFILE instead of stdin.'
complete -c sg_raw -s n -l nosense --description 'Don\'t display SCSI Sense information.'
complete -c sg_raw -s o -l outfile --description 'Write data received from the DEVICE to OFILE.  The data is written in binary.'
complete -c sg_raw -s R -l readonly --description 'Open DEVICE read-only.'
complete -c sg_raw -s r -l request --description 'Expect to receive up to RLEN bytes of data from the DEVICE.'
complete -c sg_raw -s s -l send --description 'Read SLEN bytes of data, either from stdin or from a file, and send them to t…'
complete -c sg_raw -s k -l skip --description 'Skip the first KLEN bytes of the input file or stream.'
complete -c sg_raw -s t -l timeout --description 'Wait up to SEC seconds for command completion (default: 20).'
complete -c sg_raw -s v -l verbose --description 'Increase level of verbosity.  Can be used multiple times.'
complete -c sg_raw -s V -l version --description 'Display version and license information and exit.'

