# sg_rbuf
# Autogenerated from man page /usr/share/man/man8/sg_rbuf.8.gz
complete -c sg_rbuf -s b -l buffer --description 'where EACH is the number of bytes to be transferred by each READ BUFFER comma…'
complete -c sg_rbuf -s d -l dio --description 'use direct IO if available.'
complete -c sg_rbuf -s h -l help --description 'print usage message then exit.'
complete -c sg_rbuf -s m -l mmap --description 'use memory mapped IO if available.'
complete -c sg_rbuf -s O -l old --description 'Switch to older style options.  Please use as first option.'
complete -c sg_rbuf -s q -l quick --description 'only transfer the data into kernel buffers (typically by DMA from the SCSI ad…'
complete -c sg_rbuf -s s -l size --description 'where OVERALL is the size of total transfer in bytes.'
complete -c sg_rbuf -s t -l time --description 'times the bulk data transfer component of this command.'
complete -c sg_rbuf -s v -l verbose --description 'increase level of verbosity.  Can be used multiple times.'
complete -c sg_rbuf -s V -l version --description 'print out version string then exit.'
complete -c sg_rbuf -s N -l new --description 'Switch to the newer style options.'

