# sg_reassign
# Autogenerated from man page /usr/share/man/man8/sg_reassign.8.gz
complete -c sg_reassign -s a -l address --description 'where A,A.  is a string of comma separated numbers.'
complete -c sg_reassign -s d -l dummy --description 'prepare for but do not execute the SCSI REASSIGN BLOCKS command.'
complete -c sg_reassign -s e -l eight --description 'when value is 1 then it sets the \'LONGLBA\' flag in the command indicating tha…'
complete -c sg_reassign -s g -l grown --description 'use the SCSI READ DEFECT DATA (10) command to determine the number of element…'
complete -c sg_reassign -s h -l help --description 'output the usage message then exit.'
complete -c sg_reassign -s H -l hex --description 'print response in hex (for -g, --grown, -p or --primary).'
complete -c sg_reassign -s l -l longlist --description 'sets the REASSIGN BLOCKS cdb field of the same name to the given value.'
complete -c sg_reassign -s p -l primary --description 'use the SCSI READ DEFECT DATA (10) command to determine the number of element…'
complete -c sg_reassign -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_reassign -s V -l version --description 'print the version string and then exit.'

