# sg_stream_ctl
# Autogenerated from man page /usr/share/man/man8/sg_stream_ctl.8.gz
complete -c sg_stream_ctl -s b -l brief --description 'this option reduces the output of the GET STREAM STATUS command to just one n…'
complete -c sg_stream_ctl -s c -l close --description 'selects the STREAM CONTROL command and sets STR_CTL<--0x2 (i. e.  \'close\').'
complete -c sg_stream_ctl -s C -l ctl --description 'CTL is the value placed in the STR_CTL field of the STREAM CONTROL command (c…'
complete -c sg_stream_ctl -s g -l get --description 'selects the GET STREAM STATUS command.'
complete -c sg_stream_ctl -s h -l help --description 'output the usage message then exit.'
complete -c sg_stream_ctl -s i -l id --description 'SID is a stream id, a value between 1 and 65535.'
complete -c sg_stream_ctl -s m -l maxlen --description 'LEN is the maximum length the response can be.'
complete -c sg_stream_ctl -s o -l open --description 'selects the STREAM CONTROL command and sets STR_CTL<--0x1 (i. e.  \'open\').'
complete -c sg_stream_ctl -s r -l readonly --description 'this option sets a \'read-only\' flag when the underlying operating system open…'
complete -c sg_stream_ctl -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_stream_ctl -s V -l version --description 'print the version string and then exit.'

