# sg_scan
# Autogenerated from man page /usr/share/man/man8/sg_scan.8.gz
complete -c sg_scan -s a --description 'do alphabetical scan (i. e.  sga, sgb, sgc).'
complete -c sg_scan -s i --description 'do a SCSI INQUIRY, output results in a second (indented) line.'
complete -c sg_scan -s n --description 'do numeric scan (i. e.  sg0, sg1. ) [default].'
complete -c sg_scan -s w --description 'use a read/write flag when opening sg device (default is read-only).'
complete -c sg_scan -s x --description 'extra information output about queueing NOTES This utility was written at a t…'

