# sg_seek
# Autogenerated from man page /usr/share/man/man8/sg_seek.8.gz
complete -c sg_seek -s T -l 10 --description 'use a 10 byte cdb command, either SEEK(10) or PRE-FETCH(10) command.'
complete -c sg_seek -s c -l count --description 'NC is the number of commands (one of SEEK(10), PRE-FETCH(10) or PRE-FETCH(16)…'
complete -c sg_seek -s g -l grpnum --description 'GN is the group number, a value between 0 and 63 (in hex: 0x3f).'
complete -c sg_seek -s h -l help --description 'output the usage message then exit.'
complete -c sg_seek -s i -l immed --description 'this option only applies to PRE-FETCH(10) and PRE-FETCH(16), setting the IMME…'
complete -c sg_seek -s l -l lba --description 'LBA is the starting logical block address that is placed in the command descr…'
complete -c sg_seek -s n -l num-blocks --description 'NUM is the number of blocks, starting at and including LBA, to place in the D…'
complete -c sg_seek -s p -l pre-fetch --description 'this option selects either PRE-FETCH(10) or PRE-FETCH(16) commands.'
complete -c sg_seek -s r -l readonly --description 'this option sets a \'read-only\' flag when the underlying operating system open…'
complete -c sg_seek -s s -l skip --description 'SB is the number of logical block addresses to skip, between repeated command…'
complete -c sg_seek -s t -l time --description 'if given the elapsed time to execute NC commands is recorded.'
complete -c sg_seek -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_seek -s V -l version --description 'print the version string and then exit.'
complete -c sg_seek -s w -l wrap-offset --description 'WO is the number of blocks, relative to LBA, that when exceeded, set the next…'

