# sg_sat_phy_event
# Autogenerated from man page /usr/share/man/man8/sg_sat_phy_event.8.gz
complete -c sg_sat_phy_event -s c -l ck_cond --description 'sets the CK_COND bit in the ATA PASS-THROUGH SCSI cdb.'
complete -c sg_sat_phy_event -s e -l extend --description 'sets the EXTEND bit in the ATA PASS-THROUGH SCSI cdb.'
complete -c sg_sat_phy_event -s h -l help --description 'outputs the usage message summarizing command line options then exits.'
complete -c sg_sat_phy_event -s H -l hex --description 'outputs the ATA READ LOG EXT response in hex.  The default action (i. e.'
complete -c sg_sat_phy_event -s i -l ignore --description 'usually the phy counter identifier names are decoded.'
complete -c sg_sat_phy_event -s l -l len --description 'this is the length of the SCSI cdb used for the ATA PASS-THROUGH commands.'
complete -c sg_sat_phy_event -s r -l raw --description 'output the ATA READ LOG EXT response in binary.'
complete -c sg_sat_phy_event -s R -l reset --description 'reset the counters after the current values are returned, decoded and display…'
complete -c sg_sat_phy_event -s v -l verbose --description 'increases the level or verbosity.'
complete -c sg_sat_phy_event -s V -l version --description 'print out version string NOTES The SCSI ATA PASS-THROUGH (12) command\'s opcod…'

