# sg_timestamp
# Autogenerated from man page /usr/share/man/man8/sg_timestamp.8.gz
complete -c sg_timestamp -s h -l help --description 'output the usage message then exit.'
complete -c sg_timestamp -s m -l milliseconds --description 'where MS is the number of milliseconds since 1970-01-01 00:00:00 UTC to set i…'
complete -c sg_timestamp -s o -l origin --description 'the REPORT TIMESTAMP returned parameter data contains a "timestamp origin" fi…'
complete -c sg_timestamp -s r -l raw --description 'output the SCSI REPORT TIMESTAMP response (i. e.'
complete -c sg_timestamp -s R -l readonly --description 'open the DEVICE read-only.'
complete -c sg_timestamp -s s -l seconds --description 'where SEC is the number of seconds since 1970-01-01 00:00:00 UTC to set in th…'
complete -c sg_timestamp -s S -l srep --description 'report the number of seconds since 1970-01-01 00:00:00 UTC.'
complete -c sg_timestamp -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_timestamp -s V -l version --description 'print the version string and then exit.'

