# sg_turs
# Autogenerated from man page /usr/share/man/man8/sg_turs.8.gz
complete -c sg_turs -s h -l help --description 'print out the usage message then exit.'
complete -c sg_turs -s l -l low --description 'when [--progress] is not being used, this utility tries to complete the SCSI …'
complete -c sg_turs -s n -l number --description 'performs TEST UNIT READY NUM times.  If not given defaults to 1.'
complete -c sg_turs -l num --description 'same as --number=NUM.'
complete -c sg_turs -s O -l old --description 'Switch to older style options.  Please use as first option.'
complete -c sg_turs -s p -l progress --description 'show progress indication (a percentage) if available.'
complete -c sg_turs -s t -l time --description 'after completing the requested number of TEST UNIT READY commands, outputs th…'
complete -c sg_turs -s v -l verbose --description 'increase level or verbosity.'
complete -c sg_turs -s V -l version --description 'print version string then exit.'
complete -c sg_turs -s N -l new --description 'Switch to the newer style options.'

