# sg_test_rwbuf
# Autogenerated from man page /usr/share/man/man8/sg_test_rwbuf.8.gz
complete -c sg_test_rwbuf -s r -l addrd --description 'Read an additional AR bytes (more than indicated by SZ) from the data buffer.'
complete -c sg_test_rwbuf -s w -l addwr --description 'Write an additional AW bytes (more than indicated by SZ) of zeros into the da…'
complete -c sg_test_rwbuf -s h -l help --description 'Print out a usage message the exit.'
complete -c sg_test_rwbuf -s q -l quick --description 'Perform a READ BUFFER descriptor command to find out the available data buffe…'
complete -c sg_test_rwbuf -s s -l size --description 'where SZ is the size of buffer in bytes to be written then read and checked.'
complete -c sg_test_rwbuf -s t -l times --description 'where NUM is the number of times to repeat the write/read to buffer test.'
complete -c sg_test_rwbuf -s v -l verbose --description 'increase verbosity of output.'
complete -c sg_test_rwbuf -s V -l version --description 'print version number (and data of last change) then exit.'

