# sg_unmap
# Autogenerated from man page /usr/share/man/man8/sg_unmap.8.gz
complete -c sg_unmap -s a -l anchor --description 'sets the \'Anchor\' bit in the command (introduced in sbc3r22).'
complete -c sg_unmap -s g -l grpnum --description 'sets the \'Group number\' field to GN.  Defaults to a value of zero.'
complete -c sg_unmap -s h -l help --description 'output the usage message then exit.'
complete -c sg_unmap -s I -l in --description 'where FILE is a file name containing pairs of values.'
complete -c sg_unmap -s l -l lba --description 'where LBA,LBA.'
complete -c sg_unmap -s n -l num --description 'where NUM,NUM.'
complete -c sg_unmap -s t -l timeout --description 'where TO is a timeout value (in seconds) for the UNMAP command.'
complete -c sg_unmap -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_unmap -s V -l version --description 'print the version string and then exit.'

