# sg_wr_mode
# Autogenerated from man page /usr/share/man/man8/sg_wr_mode.8.gz
complete -c sg_wr_mode -s c -l contents --description 'where H,H.'
complete -c sg_wr_mode -s d -l dbd --description 'disable block descriptors (DBD flag in cdb).'
complete -c sg_wr_mode -s f -l force --description 'force the contents string to be taken as the new mode page, or at least doesn…'
complete -c sg_wr_mode -s h -l help --description 'output the usage message then exit.'
complete -c sg_wr_mode -s l -l len --description 'length of the SCSI commands (cdb) sent to DEVICE.'
complete -c sg_wr_mode -s m -l mask --description 'where M,M.'
complete -c sg_wr_mode -s p -l page --description 'where PG_H is the page code value to fetch and modify.'
complete -c sg_wr_mode -s s -l save --description 'changes the "saved" mode page when MODE SELECT is successful.  By default (i.'
complete -c sg_wr_mode -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_wr_mode -s V -l version --description 'print the version string and then exit.'

