# sg_write_long
# Autogenerated from man page /usr/share/man/man8/sg_write_long.8.gz
complete -c sg_write_long -s S -l 16 --description 'send a SCSI WRITE LONG (16) command to DEVICE.'
complete -c sg_write_long -s c -l cor_dis --description 'sets the correction disabled (i. e \'COR_DIS\') bit.'
complete -c sg_write_long -s h -l help --description 'output the usage message then exit.'
complete -c sg_write_long -s i -l in --description 'read data (binary) from file named IF and use it for the SCSI WRITE LONG comm…'
complete -c sg_write_long -s l -l lba --description 'where LBA is the logical block address of the sector to overwrite.'
complete -c sg_write_long -s p -l pblock --description 'sets the physical block (i. e \'PBLOCK\') bit.'
complete -c sg_write_long -s v -l verbose --description 'increase the degree of verbosity (debug messages).'
complete -c sg_write_long -s V -l version --description 'output version string then exit.'
complete -c sg_write_long -s w -l wr_uncor --description 'sets the "write uncorrected" (i. e \'WR_UNCOR\') bit.'
complete -c sg_write_long -s x -l xfer_len --description 'where BTL is the byte transfer length (default to 520).'

