# sg_write_buffer
# Autogenerated from man page /usr/share/man/man8/sg_write_buffer.8.gz
complete -c sg_write_buffer -s b -l bpw --description 'where CS is the chunk size in bytes.'
complete -c sg_write_buffer -s d -l dry-run --description 'Do all the command line processing and sanity checks including reading the in…'
complete -c sg_write_buffer -s h -l help --description 'output the usage message then exit.'
complete -c sg_write_buffer -s i -l id --description 'this option sets the buffer id field in the cdb.'
complete -c sg_write_buffer -s I -l in --description 'read data from file FILE that will be sent with the WRITE BUFFER command.'
complete -c sg_write_buffer -s l -l length --description 'where LEN is the length, in bytes, of data to be written to the device.'
complete -c sg_write_buffer -s m -l mode --description 'this option sets the MODE field in the cdb.'
complete -c sg_write_buffer -s o -l offset --description 'this option sets the BUFFER OFFSET field in the cdb.'
complete -c sg_write_buffer -s r -l read-stdin --description 'read data from stdin until an EOF is detected.'
complete -c sg_write_buffer -s s -l skip --description 'this option is only active when --in=FILE is given and FILE is a regular file…'
complete -c sg_write_buffer -s S -l specific --description 'MS is the MODE SPECIFIC field in the cdb.'
complete -c sg_write_buffer -s t -l timeout --description 'TO is the command timeout (in seconds) for each WRITE BUFFER command issued b…'
complete -c sg_write_buffer -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_write_buffer -l raw --description '.'
complete -c sg_write_buffer -s V -l version --description 'print the version string and then exit.'

