# sgp_dd
# Autogenerated from man page /usr/share/man/man8/sgp_dd.8.gz
complete -c sgp_dd -l help --description 'outputs usage message and exits.'
complete -c sgp_dd -l version --description 'outputs version number information and exits.'

