# showfont
# Autogenerated from man page /usr/share/man/man1/showfont.1.gz
complete -c showfont -o server --description 'The X font server to contact.'
complete -c showfont -o fn --description 'The font to display.'
complete -c showfont -o lsb --description 'The bit order of the font should be requested as LSBFirst (least significant …'
complete -c showfont -o msb --description 'The bit order of the font should be requested as MSBFirst (most significant b…'
complete -c showfont -o LSB --description 'The byte order of the font should be requested as LSBFirst (least significant…'
complete -c showfont -o MSB --description 'The byte order of the font should be requested as MSBFirst (most significant …'
complete -c showfont -o ext --description 'Only the character extents should be displayed, but not the bitmaps.'
complete -c showfont -o start --description 'The start of the range of the characters to display (char is a number).'
complete -c showfont -o end --description 'The end of the range of the characters to display (char is a number).'
complete -c showfont -o unit --description 'The scanline unit of the font (8, 16, 32, or 64).'
complete -c showfont -o pad --description 'The scanpad unit of the font (8, 16, 32, or 64).'
complete -c showfont -s b --description 'The bitmap padding unit of the font (0, 1, or 2, where 0 is ImageRectMin, 1 i…'
complete -c showfont -o noprops --description 'Do not show the font properties.'

