# sldtoppm
# Autogenerated from man page /usr/share/man/man1/sldtoppm.1.gz
complete -c sldtoppm -o adjust --description 'If the display on which the slide file was created had non-square pixels, whe…'
complete -c sldtoppm -o dir --description 'The input is assumed to be an AutoCAD slide library file.'
complete -c sldtoppm -o height --description 'Scales the image in the vector domain so it is size pixels in height.'
complete -c sldtoppm -o info --description 'Dump the slide file header on standard error, displaying the original screen …'
complete -c sldtoppm -o lib --description 'Extracts the slide with the given name from the slide library given as input.'
complete -c sldtoppm -o Lib --description 'Extracts the slide with the given name from the slide library given as input.'
complete -c sldtoppm -o scale --description 'Scales the image by factor s, which may be any floating point value greater t…'
complete -c sldtoppm -o verbose --description 'Dumps the slide file header and lists every vector and polygon  to Standard E…'
complete -c sldtoppm -o width --description 'Scales the image in the vector domain so it is size pixels wide.'
complete -c sldtoppm -o xsize --description 'Scales the image in the vector domain so it is size pixels wide.'
complete -c sldtoppm -o ysize --description 'Scales the image in the vector domain so it is size pixels in height.'

