# sm-notify
# Autogenerated from man page /usr/share/man/man8/sm-notify.8.gz
complete -c sm-notify -s d --description 'Keeps  sm-notify attached to its controlling terminal and running in the fore…'
complete -c sm-notify -s f --description 'Send notifications even if  sm-notify has already run since the last system r…'
complete -c sm-notify -s m --description 'Specifies the length of time, in minutes, to continue retrying notifications …'
complete -c sm-notify -s n --description 'Prevents  sm-notify from updating the local system\'s NSM state number.'
complete -c sm-notify -s p --description 'Specifies the source port number  sm-notify should use when sending reboot no…'
complete -c sm-notify -s P -l state-directory-path --description 'Specifies the pathname of the parent directory where NSM state information re…'
complete -c sm-notify -s v --description 'Specifies the network address from which to send reboot notifications, and th…'

