# smbd
# Autogenerated from man page /usr/share/man/man8/smbd.8.gz
complete -c smbd -s D -l daemon --description 'If specified, this parameter causes the server to operate as a daemon.'
complete -c smbd -s F -l foreground --description 'If specified, this parameter causes the main smbd process to not daemonize, i.'
complete -c smbd -s S -l log-stdout --description 'If specified, this parameter causes smbd to log to standard output rather tha…'
complete -c smbd -s i -l interactive --description 'If this parameter is specified it causes the server to run "interactively", n…'
complete -c smbd -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c smbd -s V -l version --description 'Prints the program version number.'
complete -c smbd -s s -l configfile --description 'The file specified contains the configuration details required by the server.'
complete -c smbd -s l -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c smbd -l option --description 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line.'
complete -c smbd -s '?' -l help --description 'Print a summary of command line options.'
complete -c smbd -l usage --description 'Display brief usage message.'
complete -c smbd -l no-process-group --description 'Do not create a new process group for smbd.'
complete -c smbd -s b -l build-options --description 'Prints information about how Samba was built.'
complete -c smbd -s p -l 'port<port' --description 'port number(s) is a space or comma-separated list of TCP ports smbd should li…'
complete -c smbd -s P -l 'profiling-level<profiling' --description 'profiling level is a number specifying the level of profiling data to be coll…'

