# smbtar
# Autogenerated from man page /usr/share/man/man1/smbtar.1.gz
complete -c smbtar -s s --description 'The SMB/CIFS server that the share resides upon.'
complete -c smbtar -s x --description 'The share name on the server to connect to.  The default is "backup".'
complete -c smbtar -s X --description 'Exclude mode.  Exclude filenames.  from tar create or restore.'
complete -c smbtar -s d --description 'Change to initial directory  before restoring / backing up files.'
complete -c smbtar -s v --description 'Verbose mode.'
complete -c smbtar -s p --description 'The password to use to access a share.  Default: none.'
complete -c smbtar -s u --description 'The user id to connect as.  Default: UNIX login name.'
complete -c smbtar -s a --description 'Reset DOS archive bit mode to indicate file has been archived.'
complete -c smbtar -s t --description 'Tape device.  May be regular file or tape device.'
complete -c smbtar -s b --description 'Blocking factor.  Defaults to 20.  See tar(1) for a fuller explanation.'
complete -c smbtar -s N --description 'Backup only files newer than filename.'
complete -c smbtar -s i --description 'Incremental mode; tar files are only backed up if they have the archive bit s…'
complete -c smbtar -s r --description 'Restore.  Files are restored to the share from the tar file.'
complete -c smbtar -s l --description 'Log (debug) level.  Corresponds to the -d flag of smbclient(1).'

