# smp_conf_phy_event
# Autogenerated from man page /usr/share/man/man8/smp_conf_phy_event.8.gz
complete -c smp_conf_phy_event -s C -l clear --description 'sets the CLEAR PEAKS bit the in function request.'
complete -c smp_conf_phy_event -s e -l enumerate --description 'enumerate all of the known Phy Event Source names, one per line preceded by i…'
complete -c smp_conf_phy_event -s E -l expected --description 'set the \'expected expander change count\' field in the SMP request.'
complete -c smp_conf_phy_event -s f -l file --description 'where FILE is a file name containing pairs of values.'
complete -c smp_conf_phy_event -s h -l help --description 'output the usage message then exit.'
complete -c smp_conf_phy_event -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_conf_phy_event -s I -l interface --description 'interface specific parameters.'
complete -c smp_conf_phy_event -s p -l phy --description 'phy identifier.  ID is a value between 0 and 254 (default 0).'
complete -c smp_conf_phy_event -s P -l pes --description 'where PES,PES.'
complete -c smp_conf_phy_event -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_conf_phy_event -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_conf_phy_event -s T -l thres --description 'where THR,THR.'
complete -c smp_conf_phy_event -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_conf_phy_event -s V -l version --description 'print the version string and then exit.'

