# smp_utils
# Autogenerated from man page /usr/share/man/man8/smp_utils.8.gz
complete -c smp_utils -s E -l expected --description 'revision 4a of the SAS-2 draft introduced an \'expected expander change count\'…'
complete -c smp_utils -s h -l help --description 'output the usage message for the utility then exit.'
complete -c smp_utils -s H -l hex --description 'output the response in hexadecimal.'
complete -c smp_utils -s I -l interface --description 'interface specific parameters.'
complete -c smp_utils -s r -l raw --description 'send the response to stdout in binary.'
complete -c smp_utils -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_utils -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_utils -s V -l version --description 'print the version string and then exit.'

