# smp_zoned_broadcast
# Autogenerated from man page /usr/share/man/man8/smp_zoned_broadcast.8.gz
complete -c smp_zoned_broadcast -s b -l broadcast --description 'BT is the broadcast type, an integer in the range 0 (default) to 15.'
complete -c smp_zoned_broadcast -s E -l expected --description 'set the \'expected expander change count\' field in the SMP request.'
complete -c smp_zoned_broadcast -s F -l fszg --description 'where FS is the name of a file which contains one or more source zone groups …'
complete -c smp_zoned_broadcast -s h -l help --description 'output the usage message then exit.'
complete -c smp_zoned_broadcast -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_zoned_broadcast -s I -l interface --description 'interface specific parameters.'
complete -c smp_zoned_broadcast -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_zoned_broadcast -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_zoned_broadcast -s S -l szg --description 'one or more source zone groups for broadcast can appear as a comma separated …'
complete -c smp_zoned_broadcast -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_zoned_broadcast -s V -l version --description 'print the version string and then exit.'

