# smp_zone_activate
# Autogenerated from man page /usr/share/man/man8/smp_zone_activate.8.gz
complete -c smp_zone_activate -s E -l expected --description 'set the \'expected expander change count\' field in the SMP request.'
complete -c smp_zone_activate -s h -l help --description 'output the usage message then exit.'
complete -c smp_zone_activate -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_zone_activate -s I -l interface --description 'interface specific parameters.'
complete -c smp_zone_activate -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_zone_activate -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_zone_activate -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_zone_activate -s V -l version --description 'print the version string and then exit.'

