# smp_conf_zone_phy_info
# Autogenerated from man page /usr/share/man/man8/smp_conf_zone_phy_info.8.gz
complete -c smp_conf_zone_phy_info -s E -l expected --description 'set the \'expected expander change count\' field in the SMP request.'
complete -c smp_conf_zone_phy_info -s h -l help --description 'output the usage message then exit.'
complete -c smp_conf_zone_phy_info -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_conf_zone_phy_info -s I -l interface --description 'interface specific parameters.'
complete -c smp_conf_zone_phy_info -s p -l pconf --description 'FN is a file containing zone phy configuration descriptors in ASCII hexadecim…'
complete -c smp_conf_zone_phy_info -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_conf_zone_phy_info -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_conf_zone_phy_info -s S -l save --description 'set the \'save\' field in the SMP request.'
complete -c smp_conf_zone_phy_info -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_conf_zone_phy_info -s V -l version --description 'print the version string and then exit.'

