# smp_rep_zone_perm_tbl
# Autogenerated from man page /usr/share/man/man8/smp_rep_zone_perm_tbl.8.gz
complete -c smp_rep_zone_perm_tbl -s a -l append --description 'used in conjunction with --permf=FN to append to FN if it already exists.'
complete -c smp_rep_zone_perm_tbl -s B -l bits --description 'This is an alternate zone permission table represention showing single bits w…'
complete -c smp_rep_zone_perm_tbl -s f -l start --description 'starting (first and lowest numbered) source zone group (default: zone group 0…'
complete -c smp_rep_zone_perm_tbl -s h -l help --description 'output the usage message then exit.'
complete -c smp_rep_zone_perm_tbl -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_rep_zone_perm_tbl -s I -l interface --description 'interface specific parameters.'
complete -c smp_rep_zone_perm_tbl -s m -l multiple --description 'starting at source zone group 0 (or SS), multiple REPORT ZONE PERMISSION TABL…'
complete -c smp_rep_zone_perm_tbl -s N -l nocomma --description 'output each zone group descriptor as a long string of hexadecimal digits, two…'
complete -c smp_rep_zone_perm_tbl -s n -l num --description 'where MD is the maximum number of descriptors that can be reported in the one…'
complete -c smp_rep_zone_perm_tbl -s P -l permf --description 'FN is a file to write the zone permission descriptors to.'
complete -c smp_rep_zone_perm_tbl -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_rep_zone_perm_tbl -s R -l report --description 'set the \'report type\' field in the SMP request.'
complete -c smp_rep_zone_perm_tbl -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_rep_zone_perm_tbl -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_rep_zone_perm_tbl -s V -l version --description 'print the version string and then exit.'

