# smp_read_gpio
# Autogenerated from man page /usr/share/man/man8/smp_read_gpio.8.gz
complete -c smp_read_gpio -s c -l count --description 'where CO is the register count.'
complete -c smp_read_gpio -s E -l enhanced --description 'sends a READ GPIO REGISTER ENHANCED function request (default: send a READ GP…'
complete -c smp_read_gpio -s h -l help --description 'output the usage message then exit.'
complete -c smp_read_gpio -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_read_gpio -s i -l index --description 'where IN is the register index.'
complete -c smp_read_gpio -s I -l interface --description 'interface specific parameters.'
complete -c smp_read_gpio -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_read_gpio -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_read_gpio -s t -l type --description 'where TY is the register type.  The default value is 0 (GPIO_CFG).'
complete -c smp_read_gpio -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_read_gpio -s V -l version --description 'print the version string and then exit.'

