# smp_conf_zone_perm_tbl
# Autogenerated from man page /usr/share/man/man8/smp_conf_zone_perm_tbl.8.gz
complete -c smp_conf_zone_perm_tbl -s d -l deduce --description 'deduce number of zone groups from number of bytes on active FN lines.'
complete -c smp_conf_zone_perm_tbl -s E -l expected --description 'set the \'expected expander change count\' field in the SMP request.'
complete -c smp_conf_zone_perm_tbl -s f -l start --description 'starting (first) source zone group (default: zone group 0).'
complete -c smp_conf_zone_perm_tbl -s h -l help --description 'output the usage message then exit.'
complete -c smp_conf_zone_perm_tbl -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_conf_zone_perm_tbl -s I -l interface --description 'interface specific parameters.'
complete -c smp_conf_zone_perm_tbl -s n -l numzg --description 'number of zone groups.  ZG can be 0 (default) or 1.'
complete -c smp_conf_zone_perm_tbl -s P -l permf --description 'FN is a file containing zone permission configuration descriptors in ASCII he…'
complete -c smp_conf_zone_perm_tbl -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_conf_zone_perm_tbl -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_conf_zone_perm_tbl -s S -l save --description 'set the \'save\' field in the SMP request.'
complete -c smp_conf_zone_perm_tbl -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_conf_zone_perm_tbl -s V -l version --description 'print the version string and then exit.'

