# smp_rep_exp_route_tbl
# Autogenerated from man page /usr/share/man/man8/smp_rep_exp_route_tbl.8.gz
complete -c smp_rep_exp_route_tbl -s b -l brief --description 'reduce the decoded response output.'
complete -c smp_rep_exp_route_tbl -s h -l help --description 'output the usage message then exit.'
complete -c smp_rep_exp_route_tbl -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_rep_exp_route_tbl -s i -l index --description 'IN is the starting routed SAS address index.  The default value is 0.'
complete -c smp_rep_exp_route_tbl -s I -l interface --description 'interface specific parameters.'
complete -c smp_rep_exp_route_tbl -s n -l num --description 'maximum number of descriptors to fetch (default is 62).'
complete -c smp_rep_exp_route_tbl -s p -l phy --description 'starting phy identifier within bitmap.'
complete -c smp_rep_exp_route_tbl -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_rep_exp_route_tbl -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_rep_exp_route_tbl -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_rep_exp_route_tbl -s V -l version --description 'print the version string and then exit.'

