# smp_rep_route_info
# Autogenerated from man page /usr/share/man/man8/smp_rep_route_info.8.gz
complete -c smp_rep_route_info -s h -l help --description 'output the usage message then exit.'
complete -c smp_rep_route_info -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_rep_route_info -s i -l index --description 'expander route index.  IN is a value between 0 and 65535.  Default is 0.'
complete -c smp_rep_route_info -s I -l interface --description 'interface specific parameters.'
complete -c smp_rep_route_info -s m -l multiple --description 'call the REPORT ROUTE INFORMATION function multiple times, starting at --inde…'
complete -c smp_rep_route_info -s n -l num --description 'used with --multiple option to specify the maximum number of iterations.'
complete -c smp_rep_route_info -s p -l phy --description 'phy identifier.  ID is a value between 0 and 254.  Default is 0.'
complete -c smp_rep_route_info -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_rep_route_info -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_rep_route_info -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_rep_route_info -s V -l version --description 'print the version string and then exit.'
complete -c smp_rep_route_info -s z -l zero --description 'zero the Allocated Response Length field in the request.'

