# smp_rep_broadcast
# Autogenerated from man page /usr/share/man/man8/smp_rep_broadcast.8.gz
complete -c smp_rep_broadcast -s b -l broadcast --description 'BT is the broadcast type, an integer in the range 0 (default) to 15.'
complete -c smp_rep_broadcast -s h -l help --description 'output the usage message then exit.'
complete -c smp_rep_broadcast -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_rep_broadcast -s I -l interface --description 'interface specific parameters.'
complete -c smp_rep_broadcast -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_rep_broadcast -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_rep_broadcast -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_rep_broadcast -s V -l version --description 'print the version string and then exit.'

