# smp_phy_test
# Autogenerated from man page /usr/share/man/man8/smp_phy_test.8.gz
complete -c smp_phy_test -s c -l control --description 'set the \'phy test pattern dwords control\' field.'
complete -c smp_phy_test -s d -l dwords --description 'set the \'phy test pattern dwords\' field which is 8 bytes long.'
complete -c smp_phy_test -s E -l expected --description 'set the \'expected expander change count\' field in the SMP request.'
complete -c smp_phy_test -s f -l function --description 'set the \'phy test function\' field in the SMP request.'
complete -c smp_phy_test -s h -l help --description 'output the usage message then exit.'
complete -c smp_phy_test -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_phy_test -s I -l interface --description 'interface specific parameters.'
complete -c smp_phy_test -s l -l linkrate --description 'transmits the test pattern at the specified physical link rate: 8 -> 1.'
complete -c smp_phy_test -s P -l pattern --description 'specifies the type of test pattern to transmit.'
complete -c smp_phy_test -s p -l phy --description 'phy identifier.  ID is a value between 0 and 254.  Default is 0.'
complete -c smp_phy_test -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_phy_test -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_phy_test -s t -l sata --description 'set phy test function SATA bit.'
complete -c smp_phy_test -s S -l spread --description 'set the phy test function Spread Spectrum Clocking (SSC) field to SC.'
complete -c smp_phy_test -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_phy_test -s V -l version --description 'print the version string and then exit.'

