# smp_ena_dis_zoning
# Autogenerated from man page /usr/share/man/man8/smp_ena_dis_zoning.8.gz
complete -c smp_ena_dis_zoning -s d -l disable --description 'set the \'enable disable zoning\' field in the SMP request to 2 which will disa…'
complete -c smp_ena_dis_zoning -s e -l ena-dis --description 'set the \'enable disable zoning\' field in the SMP request.'
complete -c smp_ena_dis_zoning -s E -l expected --description 'set the \'expected expander change count\' field in the SMP request.'
complete -c smp_ena_dis_zoning -s h -l help --description 'output the usage message then exit.'
complete -c smp_ena_dis_zoning -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_ena_dis_zoning -s I -l interface --description 'interface specific parameters.'
complete -c smp_ena_dis_zoning -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_ena_dis_zoning -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_ena_dis_zoning -s S -l save --description 'set the \'save\' field in the SMP request.'
complete -c smp_ena_dis_zoning -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_ena_dis_zoning -s V -l version --description 'print the version string and then exit.'

