# smp_rep_general
# Autogenerated from man page /usr/share/man/man8/smp_rep_general.8.gz
complete -c smp_rep_general -s b -l brief --description 'reports (prints to stdout) only a few important fields from the response.'
complete -c smp_rep_general -s c -l changecount --description 'reports (prints to stdout) the value of the expander change count field from …'
complete -c smp_rep_general -s h -l help --description 'output the usage message then exit.'
complete -c smp_rep_general -s H -l hex --description 'output the response (less the CRC field) in hexadecimal.'
complete -c smp_rep_general -s I -l interface --description 'interface specific parameters.'
complete -c smp_rep_general -s r -l raw --description 'send the response (less the CRC field) to stdout in binary.'
complete -c smp_rep_general -s s -l sa --description 'specifies the SAS address of the SMP target device.'
complete -c smp_rep_general -s v -l verbose --description 'increase the verbosity of the output.  Can be used multiple times.'
complete -c smp_rep_general -s V -l version --description 'print the version string and then exit.'
complete -c smp_rep_general -s z -l zero --description 'zero the Allocated Response Length field in the request.'

