# snmpbulkwalk
# Autogenerated from man page /usr/share/man/man1/snmpbulkwalk.1.gz
complete -c snmpbulkwalk -o Cc --description 'Do not check whether the returned OIDs are increasing.'
complete -c snmpbulkwalk -o Ci --description 'Include the given OID in the search range.'
complete -c snmpbulkwalk -o Cn --description 'Set the  non-repeaters field in the GETBULK PDUs.'
complete -c snmpbulkwalk -o Cp --description 'Upon completion of the walk, print the number of variables found.'
complete -c snmpbulkwalk -o Cr --description 'Set the max-repetitions field in the GETBULK PDUs.'

