# snmpdelta
# Autogenerated from man page /usr/share/man/man1/snmpdelta.1.gz
complete -c snmpdelta -o Cf --description 'Don\'t fix errors and retry the request.'
complete -c snmpdelta -o Ct --description 'Flag will determine time interval from the monitored entity.'
complete -c snmpdelta -o Cs --description 'Flag will display a timestamp.'
complete -c snmpdelta -o CS --description 'Generates a "sum count" in addition to the individual instance counts.'
complete -c snmpdelta -o Cm --description 'Prints the max value ever attained.'
complete -c snmpdelta -o CF --description 'Tells  snmpdelta to read it\'s configuration from the specified file.'
complete -c snmpdelta -o Cl --description 'Tells  snmpdelta to write it\'s configuration to files whose names correspond …'
complete -c snmpdelta -o Cp --description 'Specifies the number of seconds between polling periods.'
complete -c snmpdelta -o CP --description 'Specifies the reporting period in number of polling periods.'
complete -c snmpdelta -o Ck --description 'When the polling period (-Cp) is an increment of 60 seconds and the timestamp…'
complete -c snmpdelta -o CT --description 'Makes   snmpdelta print its output in tabular form.'
complete -c snmpdelta -o Cv --description 'Specifies the maximum number of oids allowed to be packaged in a single PDU.'

