# snmpnetstat
# Autogenerated from man page /usr/share/man/man1/snmpnetstat.1.gz
complete -c snmpnetstat -o CL --description 'use the legacy SNMP MIB elements, not the modern IP version agnostic tables.'
complete -c snmpnetstat -o Ca --description 'With the default display, show the state of all sockets; normally sockets use…'
complete -c snmpnetstat -o Cf --description 'Only show entries for the selected address family (inet, inet6).'
complete -c snmpnetstat -o Ci --description 'Show the state of all of the network interfaces.'
complete -c snmpnetstat -o Cd --description 'Add dropped packets to the interface display.'
complete -c snmpnetstat -o Cb --description 'Show an extended interface status, giving octets in addition to packets.'
complete -c snmpnetstat -o Co --description 'Show an abbreviated interface status, giving octets in place of packets.'
complete -c snmpnetstat -o CI --description 'Show information only about this interface; used with an interval as describe…'
complete -c snmpnetstat -o Cn --description 'Show network addresses as numbers (normally  snmpnetstat interprets addresses…'
complete -c snmpnetstat -o Cv --description 'Allow long host or service names to break the columnar output.'
complete -c snmpnetstat -o Cp --description 'Show statistics about  protocol, which is either a well-known name for a prot…'
complete -c snmpnetstat -o Cs --description 'Show per-protocol statistics.'
complete -c snmpnetstat -o Cr --description 'Show the routing tables.'
complete -c snmpnetstat -o CR --description 'For GETBULK requests, repeaters specifies the max-repeaters value to use.'

