# snmpconf
# Autogenerated from man page /usr/share/man/man1/snmpconf.1.gz
complete -c snmpconf -s g --description 'switch, which walks a user through a specific set of configuration questions.'
complete -c snmpconf -s f --description 'Force overwriting existing files in the current directory without prompting t…'
complete -c snmpconf -s i --description 'When finished, install the files into the location where the global system co…'
complete -c snmpconf -s p --description 'When finished, install the files into the users home directory\'s .'
complete -c snmpconf -s I --description 'When finished, install the files into the directory  DIRECTORY .'
complete -c snmpconf -s a --description 'Don\'t ask any questions.'
complete -c snmpconf -s r --description 'Read in either all or none of the found configuration files.'
complete -c snmpconf -s R --description 'Read in a specific list of configuration files.'
complete -c snmpconf -s G --description 'List all the known groups.'
complete -c snmpconf -s c --description 'snmpconf uses a directory of configuration information to learn about the fil…'
complete -c snmpconf -s q --description 'Run slightly more quietly.'
complete -c snmpconf -s d --description 'Turn on  lots of debugging output.'
complete -c snmpconf -s D --description 'Add  even more debugging output in the form of Perl variable dumps.'

