# speaker-test
# Autogenerated from man page /usr/share/man/man1/speaker-test.1.gz
complete -c speaker-test -s c -l channels --description 'NUM channels in stream.'
complete -c speaker-test -s D -l device --description 'PCM device name NAME.'
complete -c speaker-test -s f -l frequency --description 'sine wave of FREQ Hz.'
complete -c speaker-test -l help --description 'Print usage help.'
complete -c speaker-test -s b -l buffer --description 'Use buffer size of TIME microseconds.'
complete -c speaker-test -s p -l period --description 'Use period size of TIME microseconds.'
complete -c speaker-test -s P -l nperiods --description 'Use number of periods.   The default value is 4.'
complete -c speaker-test -s r -l rate --description 'stream of RATE Hz.'
complete -c speaker-test -s t -l test --description '-t pink means use pink noise (default).'
complete -c speaker-test -s l -l nloops --description 'Specifies the number of loops.   Zero means to run infinitely.'
complete -c speaker-test -s s -l speaker --description 'Do a single-shot speaker test for the given channel.'
complete -c speaker-test -s w -l wavfile --description 'Use the given WAV file for the playback instead of pre-defined WAV files.'
complete -c speaker-test -s W -l wavdir --description 'Specify the directory containing WAV files for playback.'
complete -c speaker-test -s m -l chmap --description 'Pass the channel map to override.'
complete -c speaker-test -s X -l force-frequency --description 'Allow supplied FREQ to be outside the default range of 30-8000Hz.'

