# spottopgm
# Autogenerated from man page /usr/share/man/man1/spottopgm.1.gz
complete -c spottopgm -s 1 --description '.'
complete -c spottopgm -s 2 --description '.'
complete -c spottopgm -s 3 --description 'Extract the given color from the SPOT image.'

