# ssh-agent
# Autogenerated from man page /usr/share/man/man1/ssh-agent.1.gz
complete -c ssh-agent -s a --description 'Bind the agent to the -domain socket bind_address.'
complete -c ssh-agent -s c --description 'Generate C-shell commands on stdout.'
complete -c ssh-agent -s D --description 'Foreground mode.  When this option is specified ssh-agent will not fork.'
complete -c ssh-agent -s d --description 'Debug mode.'
complete -c ssh-agent -s E --description 'Specifies the hash algorithm used when displaying key fingerprints.'
complete -c ssh-agent -s k --description 'Kill the current agent (given by the SSH_AGENT_PID environment variable).'
complete -c ssh-agent -s P --description 'Specify a pattern-list of acceptable paths for PKCS#11 shared libraries that …'
complete -c ssh-agent -s s --description 'Generate Bourne shell commands on stdout.'
complete -c ssh-agent -s t --description 'Set a default value for the maximum lifetime of identities added to the agent.'

