# startpar
# Autogenerated from man page /usr/share/man/man8/startpar.8.gz
complete -c startpar -s p --description 'option, the default is full parallelism.'
complete -c startpar -s a --description 'option.'
complete -c startpar -s i --description 'can be used to specify another value.   The amount.'
complete -c startpar -s t --description 'option is used as buffer timeout.'
complete -c startpar -s T --description 'option timeout works more globally.'
complete -c startpar -s M --description 'option switches startpar into a make (1) like behaviour.'

