# statd
# Autogenerated from man page /usr/share/man/man8/statd.8.gz
complete -c statd -s d -l no-syslog --description 'Causes  rpc.'
complete -c statd -s F -l foreground --description 'Keeps  rpc.'
complete -c statd -s h -s '?' -l help --description 'Causes  rpc. statd to display usage information on  stderr and then exit.'
complete -c statd -s H -l ha-callout --description 'Specifies a high availability callout program.'
complete -c statd -s L -l no-notify --description 'Prevents  rpc.'
complete -c statd -s n -l name --description 'Specifies the bind address used for RPC listener sockets.'
complete -c statd -s N --description 'Causes  rpc. statd to run the  sm-notify command, and then exit.'
complete -c statd -s o -l outgoing-port --description 'Specifies the source port number the  sm-notify command should use when sendi…'
complete -c statd -s p -l port --description 'Specifies the port number used for RPC listener sockets.'
complete -c statd -s T -l nlm-port --description 'Specifies the port number that  lockd should listen on for  NLM requests.'
complete -c statd -s U -l nlm-udp-port --description 'Specifies the UDP port number that  lockd should listen on for  NLM requests.'
complete -c statd -s P -l state-directory-path --description 'Specifies the pathname of the parent directory where NSM state information re…'
complete -c statd -s v -s V -l version --description 'Causes rpc. statd to display version information on stderr and then exit.'

