# substrate
# Autogenerated from man page /usr/share/man/man6/substrate.6x.gz
complete -c substrate -o wireframe --description 'Don\'t draw sand-painting colored effects, only make a wireframe.'
complete -c substrate -o max-cycles --description 'Maximum number of growth cycles before restarting.'
complete -c substrate -o growth-delay --description 'Delay in ms between growth cycles.'
complete -c substrate -o initial-cracks --description 'Initial number of cracks in the substrate.'
complete -c substrate -o max-cracks --description 'Maximum number of cracks in the substrate at a single time.'
complete -c substrate -o sand-grains --description 'Number of sand grains dropped during coloring.'
complete -c substrate -o circle-percent --description 'The percentage of the cracks will be circular.'
complete -c substrate -o fps --description 'Display the current frame rate and CPU load.'

