# susetags2solv
# Autogenerated from man page /usr/share/man/man1/susetags2solv.1.gz
complete -c susetags2solv -s c --description '.'
complete -c susetags2solv -s q --description '.'
complete -c susetags2solv -s M --description '.'
complete -c susetags2solv -s X --description '.'

