# susepaste-screenshot
# Autogenerated from man page /usr/share/man/man1/susepaste-screenshot.1.gz
complete -c susepaste-screenshot -l all --description 'takes screenshot of whole desktop instean.'
complete -c susepaste-screenshot -s n --description 'nickname of the author of the paste.'
complete -c susepaste-screenshot -s t --description 'name of the paste.'
complete -c susepaste-screenshot -s k --description 'API key to paste as you.'
complete -c susepaste-screenshot -s e --description 'for how log will be paste stored on the server.'

