# synclient
# Autogenerated from man page /usr/share/man/man1/synclient.1.gz
complete -c synclient -s l --description 'List current user settings.  This is the default if no option is given.'
complete -c synclient -s V --description 'Print version number and exit.'
complete -c synclient -s '?' --description 'Show the help message.'

