# syndaemon
# Autogenerated from man page /usr/share/man/man1/syndaemon.1.gz
complete -c syndaemon -s i --description 'How many seconds to wait after the last key press before enabling the touchpa…'
complete -c syndaemon -s m --description 'How many milliseconds to wait between two polling intervals.'
complete -c syndaemon -s d --description 'Start as a daemon, ie in the background. LP.'
complete -c syndaemon -s p --description 'Create a pid file with the specified filename.'
complete -c syndaemon -s t --description 'Only disable tapping and scrolling, not mouse movements, in response to keybo…'
complete -c syndaemon -s k --description 'Ignore modifier keys when monitoring keyboard activity. LP.'
complete -c syndaemon -s K --description 'Like -k but also ignore Modifier+Key combos. LP.'
complete -c syndaemon -s R --description 'Use the XRecord extension for detecting keyboard activity instead of polling …'

