# systemd-udevd
# Autogenerated from man page /usr/share/man/man8/systemd-udevd.service.8.gz
complete -c systemd-udevd -l daemon --description 'Detach and run in the background.'
complete -c systemd-udevd -l debug --description 'Print debug messages to standard error.'
complete -c systemd-udevd -l children-max --description 'Limit the number of events executed in parallel.'
complete -c systemd-udevd -l exec-delay --description 'Delay the execution of RUN instructions by the given number of seconds.'
complete -c systemd-udevd -l event-timeout --description 'Set the number of seconds to wait for events to finish.'
complete -c systemd-udevd -l resolve-names --description 'Specify when systemd-udevd should resolve names of users and groups.'
complete -c systemd-udevd -l help --description 'Print a short help text and exit.'
complete -c systemd-udevd -l version --description 'Print a short version string and exit.'

