# tabs
# Autogenerated from man page /usr/share/man/man1/tabs.1.gz
complete -c tabs -s T --description 'Tell tabs which terminal type to use.'
complete -c tabs -s d --description 'The debugging option shows a ruler line, followed by two data lines.'
complete -c tabs -s n --description 'This option tells tabs to check the options and run any debugging option, but…'
complete -c tabs -s V --description 'reports the version of ncurses which was used in this program, and exits.'
complete -c tabs -s a --description 'Assembler, IBM S/370, first format.'
complete -c tabs -o a2 --description 'Assembler, IBM S/370, second format.'
complete -c tabs -s c --description 'COBOL, normal format.'
complete -c tabs -o c2 --description 'COBOL compact format.'
complete -c tabs -o c3 --description 'COBOL compact format extended.'
complete -c tabs -s f --description 'FORTRAN.'
complete -c tabs -s p --description 'PL/I.'
complete -c tabs -s s --description 'SNOBOL.'
complete -c tabs -s u --description 'UNIVAC 1100 Assembler PORTABILITY.'

