# tail
# Autogenerated from man page /usr/share/man/man1/tail.1.gz
complete -c tail -s c -l bytes --description 'output the last NUM bytes; or use -c +NUM to output starting with byte NUM of…'
complete -c tail -s f -l follow --description 'output appended data as the file grows; P an absent option argument means \'de…'
complete -c tail -s F --description 'same as --follow=\\,name\\/ --retry.'
complete -c tail -s n -l lines --description 'output the last NUM lines, instead of the last 10; or use -n +NUM to output s…'
complete -c tail -l max-unchanged-stats --description 'with --follow=\\,name\\/, reopen a FILE which has not P changed size after N (d…'
complete -c tail -l pid --description 'with -f, terminate after process ID, PID dies.'
complete -c tail -s q -l quiet -l silent --description 'never output headers giving file names.'
complete -c tail -l retry --description 'keep trying to open a file if it is inaccessible.'
complete -c tail -s s -l sleep-interval --description 'with -f, sleep for approximately N seconds (default 1.'
complete -c tail -s v -l verbose --description 'always output headers giving file names.'
complete -c tail -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c tail -l help --description 'display this help and exit.'
complete -c tail -l version --description 'output version information and exit.'

