# tapestat
# Autogenerated from man page /usr/share/man/man1/tapestat.1.gz
complete -c tapestat -l human --description 'Print sizes in human readable format (e. g.  1. 0k, 1. 2M, etc.'
complete -c tapestat -s k --description 'Show the amount of data written or read in kilobytes per second instead of me…'
complete -c tapestat -s m --description 'Show the amount of data written or read in megabytes per second instead of ki…'
complete -c tapestat -s t --description 'Display time stamps.'
complete -c tapestat -s V --description 'Print version and exit.'
complete -c tapestat -s y --description 'Omit the initial statistic showing values since boot.'
complete -c tapestat -s z --description 'Tell tapestat to omit output for any tapes for which there was no activity du…'

