# test-runner
# Autogenerated from man page /usr/share/man/man1/test-runner.1.gz
complete -c test-runner -s c -s w --description 'the command line, adding them to the list for this run.'
complete -c test-runner -s d --description 'Dry run mode.'
complete -c test-runner -s g --description 'Create test groups from any directories found while searching for tests.'
complete -c test-runner -s o --description 'Specify the directory in which to write test results.'
complete -c test-runner -s p --description 'Run script prior to any test or test group.'
complete -c test-runner -s P --description 'Run script after any test or test group.'
complete -c test-runner -s q --description 'Print only the results summary to the standard output.'
complete -c test-runner -s s --description 'Run script as a failsafe after any test is killed.'
complete -c test-runner -s S --description 'Execute the failsafe script as username.'
complete -c test-runner -s t --description 'Specify a timeout value of n seconds per test.'
complete -c test-runner -s u --description 'Execute tests or test groups as username.'
complete -c test-runner -s x --description 'Execute the pre script as username.'
complete -c test-runner -s X --description 'Execute the post script as username.  EXAMPLES.'

