# testsolv
# Autogenerated from man page /usr/share/man/man1/testsolv.1.gz
complete -c testsolv -s v --description '.'
complete -c testsolv -s r --description '.'
complete -c testsolv -s l --description '.'
complete -c testsolv -s s --description '.'

