# texlinks
# Autogenerated from man page /usr/share/man/man1/texlinks.1.gz
complete -c texlinks -l cnffile -s f --description 'use file as configuration file (default: fmtutil. cnf).'
complete -c texlinks -l help -s h --description 'show some help text.'
complete -c texlinks -l multiplatform -s m --description 'operate in all platform-specific directories (default: operate only in the di…'
complete -c texlinks -l silent -s s --description 'silently skip over existing scripts/binaries instead of printing a warning.'
complete -c texlinks -l unlink -s u --description 'Unlink previously created symlinks.'

