# tgatoppm
# Autogenerated from man page /usr/share/man/man1/tgatoppm.1.gz
complete -c tgatoppm -l alphaout --description 'tgatoppm  creates a PGM image containing the transparency channel values in t…'
complete -c tgatoppm -l headerdump --description 'Causes tgatoppm to dump information from the TGA header to Standard Error.'

