# tipc
# Autogenerated from man page /usr/share/man/man8/tipc.8.gz
complete -c tipc -s h -l help --description 'Show help about last given command.'
complete -c tipc -s j -o json --description 'Output results in JavaScript Object Notation (JSON).'
complete -c tipc -s p -o pretty --description 'The default JSON format is compact and more efficient to parse but hard for m…'

