# tlp-stat
# Autogenerated from man page /usr/share/man/man8/tlp-stat.8.gz
complete -c tlp-stat -s b -l battery --description 'Show battery data.'
complete -c tlp-stat -s c -l config --description 'Show configuration.'
complete -c tlp-stat -s d -l disk --description 'Show disk data.'
complete -c tlp-stat -s e -l pcie --description 'Show PCI(e) device data.'
complete -c tlp-stat -s g -l graphics --description 'Show graphics card data.'
complete -c tlp-stat -s p -l processor --description 'Show processor data.'
complete -c tlp-stat -s r -l rfkill --description 'Show radio device data.'
complete -c tlp-stat -s s -l system --description 'Show system information.'
complete -c tlp-stat -s t -l temp --description 'Show temperatures and fan speed.'
complete -c tlp-stat -s u -l usb --description 'Show USB device data.'
complete -c tlp-stat -s w -l warn --description 'Show warnings.'
complete -c tlp-stat -s P -l pev --description 'Monitor power supply udev events.'
complete -c tlp-stat -l psup --description 'Show power supply diagnostic.'
complete -c tlp-stat -s T -l trace --description 'Show trace output.'
complete -c tlp-stat -s v -l verbose --description 'Be more verbose.'

