# tput
# Autogenerated from man page /usr/share/man/man1/tput.1.gz
complete -c tput -s S --description 'allows more than one capability per invocation of tput.'
complete -c tput -o Ttype --description 'indicates the type of terminal.'
complete -c tput -s V --description 'reports the version of ncurses which was used in this program, and exits.'
complete -c tput -s x --description 'do not attempt to clear the terminal\'s scrollback buffer using the extended \\…'

