# tr
# Autogenerated from man page /usr/share/man/man1/tr.1.gz
complete -c tr -s c -s C -l complement --description 'use the complement of SET1.'
complete -c tr -s d -l delete --description 'delete characters in SET1, do not translate.'
complete -c tr -s s -l squeeze-repeats --description 'replace each sequence of a repeated character that is listed in the last spec…'
complete -c tr -s t -l truncate-set1 --description 'first truncate SET1 to length of SET2.'
complete -c tr -l help --description 'display this help and exit.'
complete -c tr -l version --description 'output version information and exit .'

