# tsig-keygen
# Autogenerated from man page /usr/share/man/man8/tsig-keygen.8.gz
complete -c tsig-keygen -s a --description 'Specifies the algorithm to use for the TSIG key.'
complete -c tsig-keygen -s h --description 'Prints a short summary of options and arguments.'
complete -c tsig-keygen -s k --description 'Specifies the key name of the DDNS authentication key.'
complete -c tsig-keygen -s q --description '(ddns-confgen only.'
complete -c tsig-keygen -s s --description '(ddns-confgen only.'
complete -c tsig-keygen -s z --description '(ddns-confgen only.'

