# tuned
# Autogenerated from man page /usr/share/man/man8/tuned.8.gz
complete -c tuned -s d -l daemon --description 'This options starts tuned as a daemon as opposed to in the foreground without…'
complete -c tuned -s D -l debug --description 'Sets the highest logging level.'
complete -c tuned -s h -l help --description 'Show this help.'
complete -c tuned -s l -l log --description 'Log to the file LOG.  If no LOG file is specified /var/log/tuned/tuned.'
complete -c tuned -l no-dbus --description 'Do not attach to DBus.'
complete -c tuned -s P -l pid --description 'Write process ID to the PID file.'
complete -c tuned -s p -l profile --description 'Tunning profile to be activated.  It will override other settings (e. g.'
complete -c tuned -s v -l version --description 'Show version information.  FILES.'

