# uname
# Autogenerated from man page /usr/share/man/man1/uname.1.gz
complete -c uname -s a -l all --description 'print all information, in the following order, except omit -p and -i if unkno…'
complete -c uname -s s -l kernel-name --description 'print the kernel name.'
complete -c uname -s n -l nodename --description 'print the network node hostname.'
complete -c uname -s r -l kernel-release --description 'print the kernel release.'
complete -c uname -s v -l kernel-version --description 'print the kernel version.'
complete -c uname -s m -l machine --description 'print the machine hardware name.'
complete -c uname -s p -l processor --description 'print the processor type (non-portable).'
complete -c uname -s i -l hardware-platform --description 'print the hardware platform (non-portable).'
complete -c uname -s o -l operating-system --description 'print the operating system.'
complete -c uname -l help --description 'display this help and exit.'
complete -c uname -l version --description 'output version information and exit AUTHOR Written by David MacKenzie.'

