# unpack200-java-11-openjdk
# Autogenerated from man page /usr/share/man/man1/unpack200-java-11-openjdk.1.gz
complete -c unpack200-java-11-openjdk -o Hvalue -l deflate-hint --description 'br Sets the deflation to be \\f3true, \\f3false, or \\f3keep on all entries with…'
complete -c unpack200-java-11-openjdk -s r -l remove-pack-file --description 'br Removes the input pack file.'
complete -c unpack200-java-11-openjdk -s v -l verbose --description 'br Displays minimal messages.'
complete -c unpack200-java-11-openjdk -s q -l quiet --description 'br Specifies quiet operation with no messages.'
complete -c unpack200-java-11-openjdk -o lfilename -l log-file --description 'br Specifies a log file where output messages are logged.'
complete -c unpack200-java-11-openjdk -s '?' -s h -l help --description 'br Prints help information about the \\f3unpack200 command.'
complete -c unpack200-java-11-openjdk -s V -l version --description 'br Prints version information about the \\f3unpack200 command.'
complete -c unpack200-java-11-openjdk -o Joption --description '.'

