# unzipsfx
# Autogenerated from man page /usr/share/man/man1/unzipsfx.1.gz
complete -c unzipsfx -s j -s V --description 'following operating-system specific options:  -X (restore VMS owner/protectio…'

