# update-ca-certificates
# Autogenerated from man page /usr/share/man/man8/update-ca-certificates.8.gz
complete -c update-ca-certificates -s h -l help --description 'Show summary of options.'
complete -c update-ca-certificates -s v -l verbose --description 'Be verbose.  Output c_rehash.'
complete -c update-ca-certificates -s f -l fresh --description 'Fresh updates.  Don\'t update stores incrementally but create from scratch.'

