# uptime
# Autogenerated from man page /usr/share/man/man1/uptime.1.gz
complete -c uptime -l help --description 'display this help and exit.'
complete -c uptime -l version --description 'output version information and exit AUTHOR Written by Joseph Arceneaux, David…'

