# uxterm
# Autogenerated from man page /usr/share/man/man1/uxterm.1.gz
complete -c uxterm -o class --description 'and.'
complete -c uxterm -o u8 --description 'options should not be specified because they are used by the wrapper.'

