# vttest
# Autogenerated from man page /usr/share/man/man1/vttest.1.gz
complete -c vttest -s f --description 'specify a file containing a DRCS (soft character definition) string.'
complete -c vttest -s l --description 'log test results to vttest. log.'
complete -c vttest -s p --description 'use padding, e. g. , for a VT100 connected to a high-speed line.'
complete -c vttest -s s --description 'add time-delay in selected panning/scrolling options to show details.'
complete -c vttest -s 8 --description 'use 8-bit controls (this can be changed with a menu option).'

