# vwebp
# Autogenerated from man page /usr/local/share/man/man1/vwebp.1
complete -c vwebp -s h --description 'Print usage summary.'
complete -c vwebp -o version --description 'Print version number and exit.'
complete -c vwebp -o noicc --description 'Don\'t use the ICC profile if present.'
complete -c vwebp -o nofancy --description 'Don\'t use the fancy YUV420 upscaler.'
complete -c vwebp -o nofilter --description 'Disable in-loop filtering.'
complete -c vwebp -o dither --description 'Specify a dithering strength between 0 and 100.'
complete -c vwebp -o noalphadither --description 'By default, quantized transparency planes are dithered during decompression, …'
complete -c vwebp -o usebgcolor --description 'Fill transparent areas with the bitstream\'s own background color instead of c…'
complete -c vwebp -o mt --description 'Use multi-threading for decoding, if possible.'
complete -c vwebp -o info --description 'Display image information on top of the decoded image.'

