# warnquota
# Autogenerated from man page /usr/share/man/man8/warnquota.8.gz
complete -c warnquota -s F -l format --description 'Perform setting for specified format (ie.'
complete -c warnquota -s q -l quota-tab --description 'Use  quotatab instead of  /etc/quotatab as file with device description strin…'
complete -c warnquota -s c -l config --description 'Use  configfile instead of  /etc/warnquota.'
complete -c warnquota -s a -l admins-file --description 'Use  adminsfile instead of  /etc/quotagrpadmins as a file with administrators…'
complete -c warnquota -s u -l user --description 'check whether users are not exceeding quotas (default).'
complete -c warnquota -s g -l group --description 'check whether groups are not exceeding quotas.'
complete -c warnquota -s s -l human-readable --description 'Try to report used space, number of used inodes and limits in more appropriat…'
complete -c warnquota -s i -l no-autofs --description 'ignore mountpoints mounted by automounter.'
complete -c warnquota -s d -l no-details --description 'do not attach quota report in email.  FILES aquota.'

