# wish
# Autogenerated from man page /usr/share/man/man1/wish.1.gz
complete -c wish -o encoding --description 'Specifies the encoding of the text stored in fileName.'
complete -c wish -o colormap --description 'Specifies that the window should have a new private colormap instead of using…'
complete -c wish -o display --description 'Display (and screen) on which to display window.'
complete -c wish -o geometry --description 'Initial geometry to use for window.'
complete -c wish -o name --description 'Use name as the title to be displayed in the window, and as the name of the i…'
complete -c wish -o sync --description 'Execute all X server commands synchronously, so that errors are reported imme…'
complete -c wish -o use --description 'Specifies that the main window for the application is to be embedded in the w…'
complete -c wish -o visual --description 'Specifies the visual to use for the window.'
complete -c wish -o container --description '.'

