# xbiff
# Autogenerated from man page /usr/share/man/man1/xbiff.1.gz
complete -c xbiff -o help --description 'This option indicates that a brief summary of the allowed options should be p…'
complete -c xbiff -o update --description 'This option specifies the frequency in seconds at which xbiff should update i…'
complete -c xbiff -o file --description 'This option specifies the name of the file which should be monitored.'
complete -c xbiff -o volume --description 'This option specifies how loud the bell should be rung when new mail comes in.'
complete -c xbiff -o shape --description 'This option indicates that the mailbox window should be shaped if masks for t…'
complete -c xbiff -o display --description 'This option specifies the X server to contact.'
complete -c xbiff -o geometry --description 'This option specifies the preferred size and position of the mailbox window.'
complete -c xbiff -o bg --description 'This option specifies the color to use for the background of the window.'
complete -c xbiff -o bd --description 'This option specifies the color to use for the border of the window.'
complete -c xbiff -o bw --description 'This option specifies the width in pixels of the border surrounding the windo…'
complete -c xbiff -o fg --description 'This option specifies the color to use for the foreground of the window.'
complete -c xbiff -o rv --description 'This option indicates that reverse video should be simulated by swapping the …'
complete -c xbiff -o xrm --description 'This option specifies a resource string to be used.'

