# xcompmgr
# Autogenerated from man page /usr/share/man/man1/xcompmgr.1.gz
complete -c xcompmgr -s d --description 'Specifies the display to manage.'
complete -c xcompmgr -s r --description 'Specifies the blur radius for client-side shadows.'
complete -c xcompmgr -s o --description 'Specifies the opacity for client-side shadows.'
complete -c xcompmgr -s l --description 'Specifies the left offset for client-side shadows.'
complete -c xcompmgr -s t --description 'Specifies the top offset for client-side shadows.'
complete -c xcompmgr -s I --description 'Specifies the opacity change between steps while fading in.'
complete -c xcompmgr -s O --description 'Specifies the opacity change between steps while fading out.'
complete -c xcompmgr -s D --description 'Specifies the time (in milliseconds) between steps in a fade.'
complete -c xcompmgr -s a --description 'Automatic server-side compositing.'
complete -c xcompmgr -s c --description 'Client-side compositing with soft shadows and translucency support.'
complete -c xcompmgr -s f --description 'When -c is specified, enables a smooth fade effect for transient windows like…'
complete -c xcompmgr -s n --description 'Simple client-side compositing.  This is the default mode.'
complete -c xcompmgr -s s --description 'Server-side compositing with hard-edged shadows.'
complete -c xcompmgr -s C --description 'When -c is specified, attempts to avoid painting shadows on panels and docks.'
complete -c xcompmgr -s F --description 'When -f is specified, also enables the fade effect when windows change their …'
complete -c xcompmgr -s S --description 'Enables synchronous operation.   Useful for debugging.'

