# xconsole
# Autogenerated from man page /usr/share/man/man1/xconsole.1.gz
complete -c xconsole -o file --description 'To monitor some other device, use this option to specify the device name.'
complete -c xconsole -o notify -o nonotify --description 'When new data are received from the console and the notify option is set, the…'
complete -c xconsole -o daemon --description 'This option causes  xconsole to place itself in the background, using fork/ex…'
complete -c xconsole -o verbose --description 'When set, this option directs  xconsole to display an informative message in …'
complete -c xconsole -o exitOnFail --description 'When set, this option directs  xconsole to exit when it is unable to redirect…'
complete -c xconsole -o saveLines --description 'When set, xconsole only preserves count lines of message history instead of g…'

