# xdbedizzy
# Autogenerated from man page /usr/share/man/man1/xdbedizzy.1.gz
complete -c xdbedizzy -o display --description 'This option specifies the X server to contact.'
complete -c xdbedizzy -o class --description 'Name of visual to choose.'
complete -c xdbedizzy -o depth --description 'Depth of visual to use.'
complete -c xdbedizzy -o visid --description 'Visual ID to use (ignore -class, -depth).'
complete -c xdbedizzy -o list --description 'List double buffer capable visuals.'
complete -c xdbedizzy -o nodb --description 'Single buffer (ignore -class, -depth, -visid).'
complete -c xdbedizzy -o help --description 'Prints usage and exists.'
complete -c xdbedizzy -o speed --description 'Defines the time to delay between frames as delay=2sec/speed.'
complete -c xdbedizzy -o sync --description 'Use synchronous X connection.'
complete -c xdbedizzy -o spokes --description 'Specify number of spokes to draw.  The default value is 12.'
complete -c xdbedizzy -o verbose --description 'Print verbose output.'

