# xditview
# Autogenerated from man page /usr/share/man/man1/xditview.1.gz
complete -c xditview -o page --description 'This option specifies the page number of the document to be displayed at star…'
complete -c xditview -o resolution --description 'This specifies the desired screen resolution to use; fonts will be opened by …'
complete -c xditview -o noPolyText --description 'Some X servers incorrectly implement PolyText with multiple strings per reque…'
complete -c xditview -o backingStore --description 'Redisplay can take up to a second or so; this option causes the server to sav…'
complete -c xditview -o bg --description 'This option specifies the color to use for the background of the window.'
complete -c xditview -o bd --description 'This option specifies the color to use for the border of the window.'
complete -c xditview -o bw --description 'This option specifies the width in pixels of the border surrounding the windo…'
complete -c xditview -o fg --description 'This option specifies the color to use for displaying text.'
complete -c xditview -o fn --description 'This option specifies the font to be used for displaying widget text.'
complete -c xditview -o rv --description 'This option indicates that reverse video should be simulated by swapping the …'
complete -c xditview -o geometry --description 'This option specifies the preferred size and position of the window.'
complete -c xditview -o display --description 'This option specifies the X server to contact.'
complete -c xditview -o xrm --description 'This option specifies a resource string to be used.'

