# xfindproxy
# Autogenerated from man page /usr/share/man/man1/xfindproxy.1.gz
complete -c xfindproxy -o manager --description 'argument is required, and it specifies the network address of the proxy manag…'
complete -c xfindproxy -o name --description 'argument is required, and it specifies the name of the desired proxy service …'
complete -c xfindproxy -o server --description 'argument is also required, and it specifies the address of the target server.'
complete -c xfindproxy -o auth --description 'argument is optional.'
complete -c xfindproxy -o host --description 'argument is optional.'
complete -c xfindproxy -o options --description 'argument is optional.'
complete -c xfindproxy -o version --description 'argument prints the program version and exits.'

