# ximtoppm
# Autogenerated from man page /usr/share/man/man1/ximtoppm.1.gz
complete -c ximtoppm -l alphaout --description 'ximtoppm creates a PGM file containing the transparency channel values in the…'

