# xlito
# Autogenerated from man page /usr/share/man/man1/xlito.1x.gz
complete -c xlito -s c --description 'This adds or changes the embedded string to option_string.'
complete -c xlito -s d --description 'Delete any embedded trailing option strings in the given files.'
complete -c xlito -s x --description 'Process the files and create a command line string suitable for use by xloadi…'
complete -c xlito -o name --description 'EXAMPLES If fred.'

