# xml_pp
# Autogenerated from man page /usr/share/man/man1/xml_pp.1.gz
complete -c xml_pp -s i --description 'edits the file(s) in place, if an extension is provided (no space between  \\f…'
complete -c xml_pp -s s --description 'the style to use for pretty printing: none, nsgmls, nice, indented, record, o…'
complete -c xml_pp -s p --description 'preserves white spaces in tags.'
complete -c xml_pp -s e --description 'use XML::Twig output_encoding (based on Text::Iconv or Unicode::Map8 and  Uni…'
complete -c xml_pp -s l --description 'loads the documents in memory instead of outputting them as they are being pa…'
complete -c xml_pp -s f --description 'read the list of files to process from <file>, one per line.'
complete -c xml_pp -s v --description 'verbose (list the current file being processed).'

