# xml_merge
# Autogenerated from man page /usr/share/man/man1/xml_merge.1.gz
complete -c xml_merge -s o --description 'unless this option is used the program output goes to \\s-1STDOUT\\s0.'
complete -c xml_merge -s i --description 'the files use XInclude instead of processing instructions (they were created …'
complete -c xml_merge -s v --description 'verbose output.'
complete -c xml_merge -s V --description 'outputs version and exit.'
complete -c xml_merge -s h --description 'short help.'

