# xml_split
# Autogenerated from man page /usr/share/man/man1/xml_split.1.gz
complete -c xml_split -s l --description 'level to cut at: 1 generates a file for each child of the root, 2 for each gr…'
complete -c xml_split -s c --description 'generate a file for each element that passes the condition .'
complete -c xml_split -s s --description 'generates files of (approximately) <size>.'
complete -c xml_split -s g --description 'groups <nb> elements in a single file.'
complete -c xml_split -s b --description 'base name for the output, files will be named <base>-<nb><. ext> .'
complete -c xml_split -s n --description 'number of digits in the sequence number for each file .'
complete -c xml_split -s e --description 'extension to use for generated files .'
complete -c xml_split -s i --description 'use XInclude elements instead of Processing Instructions to mark where sub fi…'
complete -c xml_split -s v --description 'verbose output .'
complete -c xml_split -s V --description 'outputs version and exit.'
complete -c xml_split -s h --description 'short help.'

