# xprehashprinterlist
# Autogenerated from man page /usr/share/man/man1/xprehashprinterlist.1x.gz
complete -c xprehashprinterlist -s v --description 'generate verbose output.'
complete -c xprehashprinterlist -s h -s '?' --description 'print usage ENVIRONMENT.'

