# xscreensaver-demo
# Autogenerated from man page /usr/share/man/man1/xscreensaver-demo.1.gz
complete -c xscreensaver-demo -o display --description 'The X display to use.'
complete -c xscreensaver-demo -o prefs --description 'Start up with the Advanced tab selected by default instead of the Display Mod…'
complete -c xscreensaver-demo -o debug --description 'Causes lots of diagnostics to be printed on stderr.'

