# xscreensaver-command
# Autogenerated from man page /usr/share/man/man1/xscreensaver-command.1.gz
complete -c xscreensaver-command -o help --description 'Prints a brief summary of command-line options.'
complete -c xscreensaver-command -o demo --description 'This just launches the  xscreensaver-demo (1) program, in which one can exper…'
complete -c xscreensaver-command -o prefs --description 'Like the no-argument form of -demo, but brings up that program\'s Preferences …'
complete -c xscreensaver-command -o activate --description 'Tell xscreensaver to turn on immediately (that is, blank the screen, as if th…'
complete -c xscreensaver-command -o deactivate --description 'This tells xscreensaver to pretend that there has just been user activity.'
complete -c xscreensaver-command -o cycle --description 'If the screensaver is active (the screen is blanked), then stop the current g…'
complete -c xscreensaver-command -o next --description 'This is like either -activate or -cycle, depending on which is more appropria…'
complete -c xscreensaver-command -o prev --description 'This is like -next, but cycles in the other direction.'
complete -c xscreensaver-command -o select --description 'Like -activate, but runs the Nth element in the list of hacks.'
complete -c xscreensaver-command -o exit --description 'Causes the xscreensaver process to exit gracefully.'
complete -c xscreensaver-command -o lock --description 'Tells the running xscreensaver process to lock the screen immediately.'
complete -c xscreensaver-command -o suspend --description 'Like -activate, but ignores lockTimeout and immediately powers off the screen…'
complete -c xscreensaver-command -o version --description 'Prints the version of xscreensaver that is currently running on the display: …'
complete -c xscreensaver-command -o time --description 'Prints the time at which the screensaver last activated or  deactivated (roug…'
complete -c xscreensaver-command -o restart --description 'Causes the screensaver process to exit and then restart with the same command…'
complete -c xscreensaver-command -o watch --description 'Prints a line each time the screensaver changes state: when the screen blanks…'

