# xsettingsd
# Autogenerated from man page /usr/share/man/man1/xsettingsd.1.gz
complete -c xsettingsd -s c -l config --description 'Load settings from FILE (default is ~/. xsettingsd).'
complete -c xsettingsd -s h -l help --description 'Display a help message and exit.'
complete -c xsettingsd -s s -l screen --description 'Use the X screen numbered SCREEN (default of -1 means all screens).'

