# xsetwacom
# Autogenerated from man page /usr/share/man/man1/xsetwacom.1.gz
complete -c xsetwacom -s d -l display --description 'Connect to the X server specified in display_name; see X(7).'
complete -c xsetwacom -s h -l help --description 'Prints a short help.'
complete -c xsetwacom -s v -l verbose --description 'Enable verbose output, useful for debugging.'
complete -c xsetwacom -s V -l version --description 'Display version number and exit.'
complete -c xsetwacom -l list --description 'is equivalent to.'
complete -c xsetwacom -o list --description 'and list.'
complete -c xsetwacom -s s -l shell --description 'Display the output in shell format, i. e.'
complete -c xsetwacom -s x -l xconf --description 'Display the output in xorg. conf format, i. e.'

