# xtables-monitor
# Autogenerated from man page /usr/share/man/man8/xtables-monitor.8.gz
complete -c xtables-monitor -s t -l trace --description 'Watch for trace events generated by packets that have been tagged using the T…'
complete -c xtables-monitor -s 4 --description 'Restrict output to IPv4.'
complete -c xtables-monitor -s e -l event --description '.'
complete -c xtables-monitor -s 6 --description 'Restrict output to IPv6.  EXAMPLE OUTPUT.'

