# xtermset
# Autogenerated from man page /usr/share/man/man1/xtermset.1.gz
complete -c xtermset -o store --description 'This option will save all the other command line options given to the filenam…'
complete -c xtermset -o default --description 'This option will load options from the specified filename.'
complete -c xtermset -s f -o force --description 'xtermset normally checks if you are using it on a correct terminal (xterm (de…'
complete -c xtermset -s T -o title --description 'Sets the window title.'
complete -c xtermset -s n --description 'Sets the icon name.'
complete -c xtermset -o fg --description 'Sets the VT100 foreground color.'
complete -c xtermset -o bg --description 'Sets the VT100 background color.'
complete -c xtermset -o mousefg --description 'Sets the mouse pointer foreground color.'
complete -c xtermset -o mousebg --description 'Sets the mouse pointer background color.'
complete -c xtermset -o tekfg --description 'Sets the Tektronix emulation window foreground color.'
complete -c xtermset -o tekbg --description 'Sets the Tektronix emulation window background color.'
complete -c xtermset -o cr --description 'Sets the text cursor color.'
complete -c xtermset -o hc --description 'Sets the color for highlighted (selected) text.'
complete -c xtermset -o fn -o font --description 'Sets the font.'
complete -c xtermset -o geom -o geometry --description 'Sets the window size and position; see X(1) for details.  FILES ~/.'

