# xtrap
# Autogenerated from man page /usr/share/man/man1/xtrap.1.gz
complete -c xtrap -s d --description 'Specifies the server to record from or playback to; see . PN X(1). PP.'
complete -c xtrap -s e --description 'Record only (and all) events.   Should be used when creating input for .'
complete -c xtrap -s f --description 'The pathname of the script to be recorded / played back. PP.'
complete -c xtrap -s v --description 'Verbose mode.'

