# xznew
# Autogenerated from man page /usr/share/man/man1/xznew.1.gz
complete -c xznew -s f --description 'Force recompression from . gz to . xz format even if a .'
complete -c xznew -s t --description 'Tests the new files before deleting originals.'
complete -c xznew -s v --description 'Verbose.  Display the name and percentage reduction for each file compressed.'
complete -c xznew -s 9 --description 'Use the slowest compression method (optimal compression).'
complete -c xznew -s P --description 'Use pipes for the conversion to reduce disk space usage.'
complete -c xznew -s K --description 'Keep a . gz file when it is smaller than the .'

