# y4mdenoise
# Autogenerated from man page /usr/share/man/man1/y4mdenoise.1.gz
complete -c y4mdenoise -s v --description '0 = none, 1 = normal (per-frame pixel-detection totals), 2=debug.'
complete -c y4mdenoise -s p --description 'Controls the level of parallelism.'
complete -c y4mdenoise -s r --description 'The search radius, i. e.'
complete -c y4mdenoise -s R --description 'The search radius to use for color.'
complete -c y4mdenoise -s t --description 'The largest difference between two pixels that\'s accepted for the two pixels …'
complete -c y4mdenoise -s T --description 'The default is whatever the main error-tolerance was set to.'
complete -c y4mdenoise -s z --description 'The error-tolerance used on pixels that haven\'t moved.'
complete -c y4mdenoise -s Z --description 'The default is whatever the main zero-motion error-tolerance was set to.'
complete -c y4mdenoise -s m --description 'The maximum number of pixel-group matches (within the search radius) to consi…'
complete -c y4mdenoise -s M --description 'The minimum size of the flood-filled region generated from a match.'
complete -c y4mdenoise -s f --description 'The number of reference frames to keep.'
complete -c y4mdenoise -s B --description 'Black-and-white mode.'
complete -c y4mdenoise -s I --description 'Set interlacing type.   Default is taken from the YUV4MPEG2 stream.'

