# yast
# Autogenerated from man page /usr/share/man/man8/yast.8.gz
complete -c yast -l qt --description 'Run YaST in the QT graphical frontend . \\".'
complete -c yast -l gtk --description 'Run YaST in the GTK graphical frontend . \\".'
complete -c yast -l ncurses --description 'Run YaST in the ncurses text-mode frontend . \\".'
complete -c yast -s g -l geometry --description 'Default window size (QT frontend only). \\".'
complete -c yast -s h -l help --description 'Print a usage and exit. \\".'
complete -c yast -s i -l install --description 'Install an RPM package.  The  package can be a single short package name (e.'
complete -c yast -l remove --description 'Remove an RPM package.  The  package can be short package names (e. g.'
complete -c yast -s l -l list --description 'List all available modules.'

