# yp_dump_binding
# Autogenerated from man page /usr/share/man/man8/yp_dump_binding.8.gz
complete -c yp_dump_binding -s d --description 'Specify a domain other than the default domainname as returned by  domainname…'
complete -c yp_dump_binding -s p --description 'Specify an alternate path to the binding files.'
complete -c yp_dump_binding -s v --description 'Display only the binding file of a specific protocol version.'

