# ypcat
# Autogenerated from man page /usr/share/man/man1/ypcat.1.gz
complete -c ypcat -s d --description 'Specify a domain other than the default domain as returned by  domainname (8).'
complete -c ypcat -s h --description 'Specify a hostname other than the default one as found by  ypbind (8).'
complete -c ypcat -s k --description 'Display map keys.'
complete -c ypcat -s t --description 'This option inhibits map nickname translation.'
complete -c ypcat -s x --description 'Display the map nickname translation table.  FILES.'

