# ypmatch
# Autogenerated from man page /usr/share/man/man1/ypmatch.1.gz
complete -c ypmatch -s d --description 'Specify a domain other than the default domain as returned by  domainname (8).'
complete -c ypmatch -s k --description 'Display map keys.'
complete -c ypmatch -s t --description 'This option inhibits map nickname translation.'
complete -c ypmatch -s x --description 'Display the map nickname translation table.  FILES.'

