# ypset
# Autogenerated from man page /usr/share/man/man8/ypset.8.gz
complete -c ypset -s d --description 'Specify a domain other than the default domain as returned by  domainname (8).'
complete -c ypset -o ypset --description 'or.'
complete -c ypset -o ypsetme --description 'options.   See ypbind (8).'
complete -c ypset -s h --description 'Set the NIS binding on host hostname  instead of the local machine.'

