# yuvkineco
# Autogenerated from man page /usr/share/man/man1/yuvkineco.1.gz
complete -c yuvkineco -s F --description 'Set output fps code (default: same as input).'
complete -c yuvkineco -s C --description 'Specify 2-3 pull down cycle list file name to write.'
complete -c yuvkineco -s O --description 'Specify cycle list name to read with old yuv stream to retry.'
complete -c yuvkineco -s N --description 'Specify cycle list name to read with new yuv stream to repair.'
complete -c yuvkineco -s S --description 'Use yuvycsnoise(1) as preprocessor and specify minimum threshold.'
complete -c yuvkineco -s n --description 'Specify noise level of input (default: 10).'
complete -c yuvkineco -s c --description 'Specify threshold to decide pictures in 2 frames are same (default: 4).'
complete -c yuvkineco -s i --description 'yuvkineco deinterlaces each frame after 2-3 pulldown reverting process, speci…'
complete -c yuvkineco -s u --description 'Set interlace information in header of output to unknown (default: non-interl…'

