# zed
# Autogenerated from man page /usr/share/man/man8/zed.8.gz
complete -c zed -s h --description 'Display a summary of the command-line options.'
complete -c zed -s L --description 'Display license information.'
complete -c zed -s V --description 'Display version information.'
complete -c zed -s v --description 'Be verbose.'
complete -c zed -s f --description 'Force the daemon to run if at all possible, disabling security checks and thr…'
complete -c zed -s F --description 'Run the daemon in the foreground.'
complete -c zed -s M --description 'Lock all current and future pages in the virtual memory address space.'
complete -c zed -s I --description 'Request that the daemon idle rather than exit when the kernel modules are not…'
complete -c zed -s Z --description 'Zero the daemon\'s state, thereby allowing zevents still within the kernel to …'
complete -c zed -s c --description '\\" Read the configuration from the specified file.'
complete -c zed -s d --description 'Read the enabled ZEDLETs from the specified directory.'
complete -c zed -s p --description 'Write the daemon\'s process ID to the specified file.'
complete -c zed -s P --description 'Custom $PATH for zedlets to use.'
complete -c zed -s s --description 'Write the daemon\'s state to the specified file.  ZEVENTS.'

