# zfs-destroy
# Autogenerated from man page /usr/share/man/man8/zfs-destroy.8.gz
complete -c zfs-destroy -s R --description 'Recursively destroy all dependents, including cloned file systems outside the…'
complete -c zfs-destroy -s f --description 'Force an unmount of any file systems using the zfs-destroy unmount Fl f comma…'
complete -c zfs-destroy -s n --description 'Do a dry-run No-op deletion.  No data will be deleted.'
complete -c zfs-destroy -s p --description 'Print machine-parsable verbose information about the deleted data.'
complete -c zfs-destroy -s r --description 'Recursively destroy all children.'
complete -c zfs-destroy -s v --description 'Print verbose information about the deleted data.'
complete -c zfs-destroy -s d --description 'Destroy immediately.'

