# zfs-upgrade
# Autogenerated from man page /usr/share/man/man8/zfs-upgrade.8.gz
complete -c zfs-upgrade -s V --description 'Upgrade to the specified version.'
complete -c zfs-upgrade -s a --description 'Upgrade all file systems on all imported pools.'
complete -c zfs-upgrade -s r --description 'Upgrade the specified file system and all descendent file systems.'

