# zfs-project
# Autogenerated from man page /usr/share/man/man8/zfs-project.8.gz
complete -c zfs-project -s d --description 'Show the directory project ID and inherit flag, not its children.'
complete -c zfs-project -s r --description 'Show on subdirectories recursively.'
complete -c zfs-project -s k --description 'Keep the project ID unchanged.'
complete -c zfs-project -s 0 --description 'Print file name with a trailing NUL instead of newline (by default), like "fi…'
complete -c zfs-project -s p --description 'Specify the referenced ID for comparing with the target file(s) or directorie…'
complete -c zfs-project -s s --description 'Set project inherit flag on the given file(s) or directories.'

