# zfs-projectspace
# Autogenerated from man page /usr/share/man/man8/zfs-projectspace.8.gz
complete -c zfs-projectspace -s H --description 'Do not print headers, use tab-delimited output.'
complete -c zfs-projectspace -s S --description 'Sort by this field in reverse order.  See s.'
complete -c zfs-projectspace -s i --description 'Translate SID to POSIX ID.'
complete -c zfs-projectspace -s n --description 'Print numeric ID instead of user/group name.'
complete -c zfs-projectspace -s o --description 'Display only the specified fields from the following set: type, name, used, q…'
complete -c zfs-projectspace -s p --description 'Use exact parsable numeric output.'
complete -c zfs-projectspace -s s --description 'Sort output by this field.'
complete -c zfs-projectspace -s t --description 'Print only the specified types from the following set: all, posixuser, smbuse…'

