# zfs-redact
# Autogenerated from man page /usr/share/man/man8/zfs-redact.8.gz
complete -c zfs-redact -s D --description 'Deduplicated send is no longer supported.'
complete -c zfs-redact -s I --description 'Generate a stream package that sends all intermediary snapshots from the firs…'
complete -c zfs-redact -s L --description 'Generate a stream which may contain blocks larger than 128KB.'
complete -c zfs-redact -s P --description 'Print machine-parsable verbose information about the stream package generated.'
complete -c zfs-redact -s R --description 'Generate a replication stream package, which will replicate the specified fil…'
complete -c zfs-redact -s e --description 'Generate a more compact stream by using WRITE_EMBEDDED records for blocks whi…'
complete -c zfs-redact -s b --description 'Sends only received property values whether or not they are overridden by loc…'
complete -c zfs-redact -s c --description 'Generate a more compact stream by using compressed WRITE records for blocks w…'
complete -c zfs-redact -s w --description 'For encrypted datasets, send data exactly as it exists on disk.'
complete -c zfs-redact -s h --description 'Generate a stream package that includes any snapshot holds (created with the …'
complete -c zfs-redact -s i --description 'Generate an incremental stream from the first snapshot the incremental source…'
complete -c zfs-redact -s n --description 'Do a dry-run No-op send.  Do not generate any actual send data.'
complete -c zfs-redact -s p --description 'Include the dataset\'s properties in the stream.'
complete -c zfs-redact -s v --description 'Print verbose information about the stream package generated.'
complete -c zfs-redact -s S --description 'This flag requires that the specified filesystem previously received a resuma…'

