# zfs-release
# Autogenerated from man page /usr/share/man/man8/zfs-release.8.gz
complete -c zfs-release -s r --description 'Specifies that a hold with the given tag is applied recursively to the snapsh…'
complete -c zfs-release -s H --description 'Do not print headers, use tab-delimited output.'

