# zfs-unallow
# Autogenerated from man page /usr/share/man/man8/zfs-unallow.8.gz
complete -c zfs-unallow -s d --description 'Allow only for the descendent file systems.'
complete -c zfs-unallow -s e --description 'Specifies that the permissions be delegated to everyone.'
complete -c zfs-unallow -s g --description 'Explicitly specify that permissions are delegated to the group.'
complete -c zfs-unallow -s l --description 'Allow locally only for the specified file system.'
complete -c zfs-unallow -s u --description 'Explicitly specify that permissions are delegated to the user.'
complete -c zfs-unallow -s r --description 'Recursively remove the permissions from this file system and all descendents.'

