# zfs-unmount
# Autogenerated from man page /usr/share/man/man8/zfs-unmount.8.gz
complete -c zfs-unmount -s O --description 'Perform an overlay mount.  Allows mounting in non-empty mountpoint.'
complete -c zfs-unmount -s a --description 'Mount all available ZFS file systems.'
complete -c zfs-unmount -s o --description 'An optional, comma-separated list of mount options to use temporarily for the…'
complete -c zfs-unmount -s l --description 'Load keys for encrypted filesystems as they are being mounted.'
complete -c zfs-unmount -s v --description 'Report mount progress.'
complete -c zfs-unmount -s f --description 'Attempt to force mounting of all filesystems, even those that couldn\'t normal…'
complete -c zfs-unmount -s u --description 'Unload keys for any encryption roots unmounted by this command.'

