# zfs-load-key
# Autogenerated from man page /usr/share/man/man8/zfs-load-key.8.gz
complete -c zfs-load-key -s r --description 'Recursively loads the keys for the specified filesystem and all descendent en…'
complete -c zfs-load-key -s a --description 'Loads the keys for all encryption roots in all imported pools.'
complete -c zfs-load-key -s n --description 'Do a dry-run No-op load-key.'
complete -c zfs-load-key -s L --description 'Use keylocation instead of the keylocation property.'
complete -c zfs-load-key -s l --description 'Ensures the key is loaded before attempting to change the key.'
complete -c zfs-load-key -s o --description 'Allows the user to set encryption key properties ( keyformat, keylocation, an…'
complete -c zfs-load-key -s i --description 'Indicates that zfs should make filesystem inherit the key of its parent.'

