# zfs-mount
# Autogenerated from man page /usr/share/man/man8/zfs-mount.8.gz
complete -c zfs-mount -s O --description 'Perform an overlay mount.  Allows mounting in non-empty mountpoint.'
complete -c zfs-mount -s a --description 'Mount all available ZFS file systems.'
complete -c zfs-mount -s o --description 'An optional, comma-separated list of mount options to use temporarily for the…'
complete -c zfs-mount -s l --description 'Load keys for encrypted filesystems as they are being mounted.'
complete -c zfs-mount -s v --description 'Report mount progress.'
complete -c zfs-mount -s f --description 'Attempt to force mounting of all filesystems, even those that couldn\'t normal…'
complete -c zfs-mount -s u --description 'Unload keys for any encryption roots unmounted by this command.'

