# zfs-set
# Autogenerated from man page /usr/share/man/man8/zfs-set.8.gz
complete -c zfs-set -s H --description 'Display output in a form more easily parsed by scripts.'
complete -c zfs-set -s d --description 'Recursively display any children of the dataset, limiting the recursion to de…'
complete -c zfs-set -s o --description 'A comma-separated list of columns to display.'
complete -c zfs-set -s p --description 'Display numbers in parsable exact values.'
complete -c zfs-set -s r --description 'Recursively display properties for any children.'
complete -c zfs-set -s s --description 'A comma-separated list of sources to display.'
complete -c zfs-set -s t --description 'A comma-separated list of types to display, where type is one of filesystem, …'
complete -c zfs-set -s S --description 'Revert the property to the received value if one exists; otherwise operate as…'

