# zfs-program
# Autogenerated from man page /usr/share/man/man8/zfs-program.8.gz
complete -c zfs-program -s j --description 'Display channel program output in JSON format.'
complete -c zfs-program -s n --description 'Executes a read-only channel program, which runs faster.'
complete -c zfs-program -s t --description 'Limit the number of Lua instructions to execute.'
complete -c zfs-program -s m --description 'Memory limit, in bytes.'

