# zfs-create
# Autogenerated from man page /usr/share/man/man8/zfs-create.8.gz
complete -c zfs-create -s o --description 'Sets the specified property as if the command zfs-create zfs Cm set Ar proper…'
complete -c zfs-create -s p --description 'Creates all the non-existing parent datasets.'
complete -c zfs-create -s n --description 'Do a dry-run No-op creation.  No datasets will be created.'
complete -c zfs-create -s P --description 'Print machine-parsable verbose information about the created dataset.'
complete -c zfs-create -s v --description 'Print verbose information about the created dataset.'
complete -c zfs-create -s b --description 'Equivalent to o Sy volblocksize Ns = Ns Ar blocksize.'
complete -c zfs-create -s s --description 'Creates a sparse volume with no reservation.'

