# zfs-recv
# Autogenerated from man page /usr/share/man/man8/zfs-recv.8.gz
complete -c zfs-recv -s F --description 'Force a rollback of the file system to the most recent snapshot before perfor…'
complete -c zfs-recv -s d --description 'Discard the first element of the sent snapshot\'s file system name, using the …'
complete -c zfs-recv -s e --description 'Discard all but the last element of the sent snapshot\'s file system name, usi…'
complete -c zfs-recv -s h --description 'Skip the receive of holds.   There is no effect if holds are not sent.'
complete -c zfs-recv -s M --description 'Force an unmount of the file system while receiving a snapshot.'
complete -c zfs-recv -s n --description 'Do not actually receive the stream.'
complete -c zfs-recv -s o --description 'Forces the stream to be received as a clone of the given snapshot.'
complete -c zfs-recv -s s --description 'If the receive is interrupted, save the partially received state, rather than…'
complete -c zfs-recv -s u --description 'File system that is associated with the received stream is not mounted.'
complete -c zfs-recv -s v --description 'Print verbose information about the stream and the time required to perform t…'
complete -c zfs-recv -s x --description 'Ensures that the effective value of the specified property after the receive …'

