# zfs-rollback
# Autogenerated from man page /usr/share/man/man8/zfs-rollback.8.gz
complete -c zfs-rollback -s R --description 'Destroy any more recent snapshots and bookmarks, as well as any clones of tho…'
complete -c zfs-rollback -s f --description 'Used with the R option to force an unmount of any clone file systems that are…'
complete -c zfs-rollback -s r --description 'Destroy any snapshots and bookmarks more recent than the one specified.'

