# zipinfo
# Autogenerated from man page /usr/share/man/man1/zipinfo.1.gz
complete -c zipinfo -s 1 --description 'list filenames only, one per line.'
complete -c zipinfo -s 2 --description 'list filenames only, one per line, but allow headers (-h), trailers (-t) and …'
complete -c zipinfo -s s --description 'list zipfile info in short Unix ``\\fCls -l\'\' format.'
complete -c zipinfo -s S --description 'suppress the conversion of file name encodings.'
complete -c zipinfo -s m --description 'list zipfile info in medium Unix ``\\fCls -l\'\' format.'
complete -c zipinfo -s l --description 'list zipfile info in long Unix ``\\fCls -l\'\' format.'
complete -c zipinfo -s v --description 'list zipfile information in verbose, multi-page format.'
complete -c zipinfo -s h --description 'list header line.'
complete -c zipinfo -s M --description 'pipe all output through an internal pager similar to the Unix more(1) command.'
complete -c zipinfo -s t --description 'list totals for files listed or for all files.'
complete -c zipinfo -s T --description 'print the file dates and times in a sortable decimal format (yymmdd. hhmmss).'
complete -c zipinfo -s U --description '[UNICODE_SUPPORT only] modify or disable UTF-8 handling.'
complete -c zipinfo -o UU --description 'encoded filenames.'
complete -c zipinfo -s z --description 'include the archive comment (if any) in the listing.'

