# zpool-list
# Autogenerated from man page /usr/share/man/man8/zpool-list.8.gz
complete -c zpool-list -s g --description 'Display vdev GUIDs instead of the normal device names.'
complete -c zpool-list -s H --description 'Scripted mode.'
complete -c zpool-list -s o --description 'Comma-separated list of properties to display.'
complete -c zpool-list -s L --description 'Display real paths for vdevs resolving all symbolic links.'
complete -c zpool-list -s p --description 'Display numbers in parsable exact values.'
complete -c zpool-list -s P --description 'Display full paths for vdevs instead of only the last component of the path.'
complete -c zpool-list -s T --description 'Display a time stamp.'
complete -c zpool-list -s v --description 'Verbose statistics.'

