# zpool-online
# Autogenerated from man page /usr/share/man/man8/zpool-online.8.gz
complete -c zpool-online -s f --description 'Force fault.  Instead of offlining the disk, put it into a faulted state.'
complete -c zpool-online -s t --description 'Temporary.'
complete -c zpool-online -s e --description 'Expand the device to use all available space.'

