# zpool-get
# Autogenerated from man page /usr/share/man/man8/zpool-get.8.gz
complete -c zpool-get -s H --description 'Scripted mode.'
complete -c zpool-get -s o --description 'A comma-separated list of columns to display.'
complete -c zpool-get -s p --description 'Display numbers in parsable (exact) values.'

