# zpool-checkpoint
# Autogenerated from man page /usr/share/man/man8/zpool-checkpoint.8.gz
complete -c zpool-checkpoint -s d --description 'Discards an existing checkpoint from pool.'
complete -c zpool-checkpoint -s w --description 'Waits until the checkpoint has finished being discarded before returning.'

