# zpool-scrub
# Autogenerated from man page /usr/share/man/man8/zpool-scrub.8.gz
complete -c zpool-scrub -s s --description 'Stop scrubbing.  El -tag -width Ds.'
complete -c zpool-scrub -s p --description 'Pause scrubbing.'
complete -c zpool-scrub -s w --description 'Wait until scrub has completed before returning.'

