# zpool-initialize
# Autogenerated from man page /usr/share/man/man8/zpool-initialize.8.gz
complete -c zpool-initialize -s c --description 'Cancel initializing on the specified devices, or all eligible devices if none…'
complete -c zpool-initialize -s s --description 'Suspend initializing on the specified devices, or all eligible devices if non…'
complete -c zpool-initialize -s w --description 'Wait until the devices have finished initializing before returning.'

