# zpool-destroy
# Autogenerated from man page /usr/share/man/man8/zpool-destroy.8.gz
complete -c zpool-destroy -s f --description 'Forces any active datasets contained within the pool to be unmounted.  El El.'

