# zpool-replace
# Autogenerated from man page /usr/share/man/man8/zpool-replace.8.gz
complete -c zpool-replace -s f --description 'Forces use of new_device, even if it appears to be in use.'
complete -c zpool-replace -s o --description 'Sets the given pool properties.'
complete -c zpool-replace -s s --description 'The new_device is reconstructed sequentially to restore redundancy as quickly…'
complete -c zpool-replace -s w --description 'Waits until the replacement has completed before returning.'

