# zpool-attach
# Autogenerated from man page /usr/share/man/man8/zpool-attach.8.gz
complete -c zpool-attach -s f --description 'Forces use of new_device, even if it appears to be in use.'
complete -c zpool-attach -s o --description 'Sets the given pool properties.'
complete -c zpool-attach -s s --description 'The new_device is reconstructed sequentially to restore redundancy as quickly…'
complete -c zpool-attach -s w --description 'Waits until new_device has finished resilvering before returning.'

