# zpool-create
# Autogenerated from man page /usr/share/man/man8/zpool-create.8.gz
complete -c zpool-create -s d --description 'Do not enable any features on the new pool.'
complete -c zpool-create -s f --description 'Forces use of vdev Ns s, even if they appear in use or specify a conflicting …'
complete -c zpool-create -s m --description 'Sets the mount point for the root dataset.'
complete -c zpool-create -s n --description 'Displays the configuration that would be used without actually creating the p…'
complete -c zpool-create -s o --description 'Sets the given pool properties.'
complete -c zpool-create -s O --description 'Sets the given file system properties in the root file system of the pool.'
complete -c zpool-create -s R --description 'Equivalent to o Sy cachefile Ns = Ns Sy none Fl o Sy altroot Ns = Ns Ar root.'
complete -c zpool-create -s t --description 'Sets the in-core pool name to tname while the on-disk name will be the name s…'

