# zpool-remove
# Autogenerated from man page /usr/share/man/man8/zpool-remove.8.gz
complete -c zpool-remove -s n --description 'Do not actually perform the removal ("no-op").'
complete -c zpool-remove -s p --description 'Used in conjunction with the n flag, displays numbers as parsable (exact) val…'
complete -c zpool-remove -s w --description 'Waits until the removal has completed before returning.'

