# zpool-set
# Autogenerated from man page /usr/share/man/man8/zpool-set.8.gz
complete -c zpool-set -s H --description 'Scripted mode.'
complete -c zpool-set -s o --description 'A comma-separated list of columns to display.'
complete -c zpool-set -s p --description 'Display numbers in parsable (exact) values.'

