# zpool-status
# Autogenerated from man page /usr/share/man/man8/zpool-status.8.gz
complete -c zpool-status -s c --description 'Run a script (or scripts) on each vdev and include the output as a new column…'
complete -c zpool-status -s i --description 'Display vdev initialization status.'
complete -c zpool-status -s g --description 'Display vdev GUIDs instead of the normal device names.'
complete -c zpool-status -s L --description 'Display real paths for vdevs resolving all symbolic links.'
complete -c zpool-status -s p --description 'Display numbers in parsable (exact) values.'
complete -c zpool-status -s P --description 'Display full paths for vdevs instead of only the last component of the path.'
complete -c zpool-status -s D --description 'Display a histogram of deduplication statistics, showing the allocated physic…'
complete -c zpool-status -s s --description 'Display the number of leaf VDEV slow IOs.'
complete -c zpool-status -s t --description 'Display vdev TRIM status.'
complete -c zpool-status -s T --description 'Display a time stamp.'
complete -c zpool-status -s v --description 'Displays verbose data error information, printing out a complete list of all …'
complete -c zpool-status -s x --description 'Only display status for pools that are exhibiting errors or are otherwise una…'

