# zypper-log
# Autogenerated from man page /usr/share/man/man8/zypper-log.8.gz
complete -c zypper-log -s d --description '.'
complete -c zypper-log -s l --description '.'
complete -c zypper-log -s r --description '.'
complete -c zypper-log -l help --description '.'

