#!/bin/sh

INTERFACE="${instance:-_first_}"
FORMAT_UP="${format_up:- %ip (%speed)}"
FORMAT_DOWN="${format_down:- }"

_first_ () {
  for i in /sys/class/net/*
  do
    if test -d $i/device -a ! -d $i/wireless
    then
      basename $i
      break
    fi
  done
}

if [ "$INTERFACE" = "_first_" ]
then
  INTERFACE="$(_first_)"
fi

ip () {
  ifconfig "$INTERFACE" | grep -w inet | awk '{ print $2 }'
}

speed () {
  sed -e 's,$, MBit/s,' "/sys/class/net/$INTERFACE/speed"
}

if grep -wq up "/sys/class/net/$INTERFACE/operstate"
then
  echo "$FORMAT_UP" | sed \
    -e "s,%ip,$(ip),g" \
    -e "s,%speed,$(speed),g" \
    -e q
  echo
  echo '#00FF00'
else
  echo "$FORMAT_DOWN"
  echo
  echo '#FF0000'
fi

exit
