#!/bin/sh

INTERFACE="${instance:-_first_}"
FORMAT_UP="${format_up:- (%quality at %essid) %ip}"
FORMAT_DOWN="${format_down:- }"
FORMAT_QUALITY="${format_quality:-%3d%s}"

if [ "$INTERFACE" = "_first_" ]
then
  INTERFACE="$(cat /proc/net/wireless | sed -n 3p | cut -d: -f1 | sed -e 's/^[[:space:]]*//')"
fi

bitrate () {
  iwlist "$INTERFACE" bitrate | grep Current | cut -d= -f2
}

essid () {
  iwgetid "$INTERFACE" | sed -e 's,^.*ESSID:",,' -e 's,"$,,'
}

frequency () {
  iwgetid "$INTERFACE" --freq | cut -d: -f2
}

ip () {
  ifconfig "$INTERFACE" | grep -w inet | awk '{ print $2 }'
}

link_quality () {
  iwconfig "$INTERFACE" | grep 'Link ' | sed 's,.*Quality=\([0-9]\+/[0-9]\+\) .*,100*\1,' | bc
}

quality () {
  printf "$FORMAT_QUALITY" "$(link_quality)" "%"
}

if grep -wq up "/sys/class/net/$INTERFACE/operstate"
then
  echo "$FORMAT_UP" | sed \
    -e "s,%bitrate,$(bitrate),g" \
    -e "s,%essid,$(essid),g" \
    -e "s,%frequency,$(frequency),g" \
    -e "s,%ip,$(ip),g" \
    -e "s,%quality,$(quality),g" \
    -e q
  echo
  echo '#00FF00'
else
  echo "$FORMAT_DOWN"
  echo
  echo '#FF0000'
fi

exit
