#!/bin/bash
#
# Sample .xinitrc for SUSE Linux
# This script is called from 'startx' when you start an X session
#

#
# In case everything goes wrong, we at least fall back to a plain xterm
#
failsafe="xterm -ls -T Failsafe -geometry 80x24-0-0"
trap "exec $failsafe" EXIT SIGHUP SIGINT SIGPIPE SIGTERM SIGIO

#
# Some bash (1 and 2) settings to avoid trouble on a
# failed program call.
#
set +e > /dev/null 2>&1
set +u > /dev/null 2>&1
set +o posix  > /dev/null 2>&1
if type shopt > /dev/null 2>&1 ; then
    shopt -s execfail
else
    no_exit_on_failed_exec=1
fi

#
# Source common code shared between the
# X session and X init scripts
#
#[[ -f /etc/X11/xinit/xinitrc.common ]]

if [[ -f /etc/X11/xinit/xinitrc.common ]]
then
    . /etc/X11/xinit/xinitrc.common
fi

#
# Special for twm
#
case "$WINDOWMANAGER" in
    *twm) xsetroot -solid darkslateblue
esac

#
# Uncomment next lines to activate asking for ssh passphrase
#
# if test -S "$SSH_AUTH_SOCK" -a -x "$SSH_ASKPASS"; then
#       ssh-add < /dev/null
# fi

#
# Add your own lines here...
#

# Set laptop monitor as primary
#xrandr --output LVDS1 --mode 1366x768 --rate 60 --primary
# Look for external monitor, if found, set it to the left...
#xrandr --output VGA1 --mode 1600x900 --rate 60 --left-of LVDS1

# nitrogen wallpaper setting refresh
#nitrogen --restore &

# day planer deamon
# pland &

#
# finally start the window manager
#
unset WINDOW_MANAGER STARTUP
exec $WINDOWMANAGER ${1+"$@"}

# call failsafe
exit 0
