.\" Manpage for git-stats
.\" Contact wih me to correct errors or typos.
.TH man 8 "10 Oct 2020" "0.1" "git stats man page"
.SH NAME
git stats \- Show repository statistics.
.SH SYNOPSIS
git stats
.SH DESCRIPTION
It is Zaryob's subcommand that shows your repository statistics to terminal.
.SH OPTIONS
.TP
.BR --help
Shows that help message.
.I
.SH SEE ALSO
git-for-each-ref(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Suleyman Poyraz (zaryob.dev@gmail.com)
