.\" Manpage for git-removve-sensitive.
.\" Contact wih me to correct errors or typos.
.TH man 8 "11 Oct 2020" "0.1" "git remove-sensitive man page"
.SH NAME
git remove-sensitive \- Remove sensitive data with cleaning from history and diff data.
.SH SYNOPSIS
git remove-sensitive filename
.SH DESCRIPTION
It is Zaryob's subcommand that removes sensitive data and its history.
.SH OPTIONS
.TP
.BR --help
Shows that help message.
.I
.SH SEE ALSO
git-for-each-ref(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Suleyman Poyraz (zaryob.dev@gmail.com)
