.\" Manpage for git-ignore.
.\" Contact wih me to correct errors or typos.
.TH man 8 "28 Apr 2021" "0.1" "git ignore man page"
.SH NAME
git ignore \- Ignore given file.
.SH SYNOPSIS
git ignore file_name
.SH DESCRIPTION
It is Zaryob's subcommand that adding file to your .gitignore file.
.SH OPTIONS
.TP
.BR --help
Shows that help message.
.I
.SH SEE ALSO
git-for-each-ref(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Suleyman Poyraz (zaryob.dev@gmail.com)
