.\" Manpage for git-stats
.\" Contact wih me to correct errors or typos.
.TH man 8 "3 Jul 2021" "0.1" "git getb man page"
.SH NAME
git getb \- Get all repository branches from remotes.
.SH SYNOPSIS
git getb
.SH DESCRIPTION
It is Zaryob's subcommand that gets all branches from remotes
.SH OPTIONS
.TP
.BR --help
Shows that help message.
.I
.SH SEE ALSO
git-for-each-ref(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Suleyman Poyraz (zaryob.dev@gmail.com)
