.\" Manpage for git-browse.
.\" Contact wih me to correct errors or typos.
.TH man 8 "28 Sep 2020" "0.1" "git browse man page"
.SH NAME
git browse \- Show remote repository in web browser.
.SH SYNOPSIS
git browse remote-name
.SH DESCRIPTION
It is Zaryob's subcommand that shows your remote repository with opening web browser giving url of remote.
.SH OPTIONS
.TP
.BR --help
Shows that help message.
.I
.SH SEE ALSO
git-for-each-ref(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Suleyman Poyraz (zaryob.dev@gmail.com)
