.\" Manpage for git-license.
.\" Contact wih me to correct errors or typos.
.TH man 8 "10 Oct 2020" "0.1" "git license man page"
.SH NAME
git license \- License your repository with given licenses.
.SH SYNOPSIS
git browse license-name
.SH DESCRIPTION
It is Zaryob's subcommand that licenses your code repository.
.SH OPTIONS
.TP
.BR \-l ", " \-\-list
Lists all license agreements comes with that command.
.TP
.BR \-r ", "\-\-read
Reads given license agreement.
.TP
.BR --help
Shows that help message.
.I
.SH SEE ALSO
git-for-each-ref(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Suleyman Poyraz (zaryob.dev@gmail.com)
